// Code generated by ent, DO NOT EDIT.

package stickymessage

import (
	"alt-bot/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldLTE(FieldID, id))
}

// GuildID applies equality check predicate on the "guild_id" field. It's identical to GuildIDEQ.
func GuildID(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldGuildID, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldChannelID, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldContent, v))
}

// LastMessageID applies equality check predicate on the "last_message_id" field. It's identical to LastMessageIDEQ.
func LastMessageID(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldLastMessageID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldEnabled, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// GuildIDEQ applies the EQ predicate on the "guild_id" field.
func GuildIDEQ(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldGuildID, v))
}

// GuildIDNEQ applies the NEQ predicate on the "guild_id" field.
func GuildIDNEQ(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNEQ(FieldGuildID, v))
}

// GuildIDIn applies the In predicate on the "guild_id" field.
func GuildIDIn(vs ...string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldIn(FieldGuildID, vs...))
}

// GuildIDNotIn applies the NotIn predicate on the "guild_id" field.
func GuildIDNotIn(vs ...string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNotIn(FieldGuildID, vs...))
}

// GuildIDGT applies the GT predicate on the "guild_id" field.
func GuildIDGT(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldGT(FieldGuildID, v))
}

// GuildIDGTE applies the GTE predicate on the "guild_id" field.
func GuildIDGTE(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldGTE(FieldGuildID, v))
}

// GuildIDLT applies the LT predicate on the "guild_id" field.
func GuildIDLT(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldLT(FieldGuildID, v))
}

// GuildIDLTE applies the LTE predicate on the "guild_id" field.
func GuildIDLTE(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldLTE(FieldGuildID, v))
}

// GuildIDContains applies the Contains predicate on the "guild_id" field.
func GuildIDContains(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldContains(FieldGuildID, v))
}

// GuildIDHasPrefix applies the HasPrefix predicate on the "guild_id" field.
func GuildIDHasPrefix(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldHasPrefix(FieldGuildID, v))
}

// GuildIDHasSuffix applies the HasSuffix predicate on the "guild_id" field.
func GuildIDHasSuffix(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldHasSuffix(FieldGuildID, v))
}

// GuildIDEqualFold applies the EqualFold predicate on the "guild_id" field.
func GuildIDEqualFold(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEqualFold(FieldGuildID, v))
}

// GuildIDContainsFold applies the ContainsFold predicate on the "guild_id" field.
func GuildIDContainsFold(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldContainsFold(FieldGuildID, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNotIn(FieldChannelID, vs...))
}

// ChannelIDGT applies the GT predicate on the "channel_id" field.
func ChannelIDGT(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldGT(FieldChannelID, v))
}

// ChannelIDGTE applies the GTE predicate on the "channel_id" field.
func ChannelIDGTE(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldGTE(FieldChannelID, v))
}

// ChannelIDLT applies the LT predicate on the "channel_id" field.
func ChannelIDLT(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldLT(FieldChannelID, v))
}

// ChannelIDLTE applies the LTE predicate on the "channel_id" field.
func ChannelIDLTE(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldLTE(FieldChannelID, v))
}

// ChannelIDContains applies the Contains predicate on the "channel_id" field.
func ChannelIDContains(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldContains(FieldChannelID, v))
}

// ChannelIDHasPrefix applies the HasPrefix predicate on the "channel_id" field.
func ChannelIDHasPrefix(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldHasPrefix(FieldChannelID, v))
}

// ChannelIDHasSuffix applies the HasSuffix predicate on the "channel_id" field.
func ChannelIDHasSuffix(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldHasSuffix(FieldChannelID, v))
}

// ChannelIDEqualFold applies the EqualFold predicate on the "channel_id" field.
func ChannelIDEqualFold(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEqualFold(FieldChannelID, v))
}

// ChannelIDContainsFold applies the ContainsFold predicate on the "channel_id" field.
func ChannelIDContainsFold(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldContainsFold(FieldChannelID, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldContainsFold(FieldContent, v))
}

// LastMessageIDEQ applies the EQ predicate on the "last_message_id" field.
func LastMessageIDEQ(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldLastMessageID, v))
}

// LastMessageIDNEQ applies the NEQ predicate on the "last_message_id" field.
func LastMessageIDNEQ(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNEQ(FieldLastMessageID, v))
}

// LastMessageIDIn applies the In predicate on the "last_message_id" field.
func LastMessageIDIn(vs ...string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldIn(FieldLastMessageID, vs...))
}

// LastMessageIDNotIn applies the NotIn predicate on the "last_message_id" field.
func LastMessageIDNotIn(vs ...string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNotIn(FieldLastMessageID, vs...))
}

// LastMessageIDGT applies the GT predicate on the "last_message_id" field.
func LastMessageIDGT(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldGT(FieldLastMessageID, v))
}

// LastMessageIDGTE applies the GTE predicate on the "last_message_id" field.
func LastMessageIDGTE(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldGTE(FieldLastMessageID, v))
}

// LastMessageIDLT applies the LT predicate on the "last_message_id" field.
func LastMessageIDLT(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldLT(FieldLastMessageID, v))
}

// LastMessageIDLTE applies the LTE predicate on the "last_message_id" field.
func LastMessageIDLTE(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldLTE(FieldLastMessageID, v))
}

// LastMessageIDContains applies the Contains predicate on the "last_message_id" field.
func LastMessageIDContains(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldContains(FieldLastMessageID, v))
}

// LastMessageIDHasPrefix applies the HasPrefix predicate on the "last_message_id" field.
func LastMessageIDHasPrefix(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldHasPrefix(FieldLastMessageID, v))
}

// LastMessageIDHasSuffix applies the HasSuffix predicate on the "last_message_id" field.
func LastMessageIDHasSuffix(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldHasSuffix(FieldLastMessageID, v))
}

// LastMessageIDEqualFold applies the EqualFold predicate on the "last_message_id" field.
func LastMessageIDEqualFold(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEqualFold(FieldLastMessageID, v))
}

// LastMessageIDContainsFold applies the ContainsFold predicate on the "last_message_id" field.
func LastMessageIDContainsFold(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldContainsFold(FieldLastMessageID, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldContainsFold(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.StickyMessage {
	return predicate.StickyMessage(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StickyMessage) predicate.StickyMessage {
	return predicate.StickyMessage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StickyMessage) predicate.StickyMessage {
	return predicate.StickyMessage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StickyMessage) predicate.StickyMessage {
	return predicate.StickyMessage(sql.NotPredicates(p))
}
