// Code generated by ent, DO NOT EDIT.

package marketstate

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the marketstate type in the database.
	Label = "market_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCurrentEvent holds the string denoting the current_event field in the database.
	FieldCurrentEvent = "current_event"
	// FieldEventRemainingTicks holds the string denoting the event_remaining_ticks field in the database.
	FieldEventRemainingTicks = "event_remaining_ticks"
	// FieldPityCounter holds the string denoting the pity_counter field in the database.
	FieldPityCounter = "pity_counter"
	// FieldCircuitLevel holds the string denoting the circuit_level field in the database.
	FieldCircuitLevel = "circuit_level"
	// FieldLastBreachAt holds the string denoting the last_breach_at field in the database.
	FieldLastBreachAt = "last_breach_at"
	// FieldLastPrice holds the string denoting the last_price field in the database.
	FieldLastPrice = "last_price"
	// FieldReserveBalance holds the string denoting the reserve_balance field in the database.
	FieldReserveBalance = "reserve_balance"
	// FieldRevenueBalance holds the string denoting the revenue_balance field in the database.
	FieldRevenueBalance = "revenue_balance"
	// FieldBurnedTotal holds the string denoting the burned_total field in the database.
	FieldBurnedTotal = "burned_total"
	// FieldDailyIssuanceDate holds the string denoting the daily_issuance_date field in the database.
	FieldDailyIssuanceDate = "daily_issuance_date"
	// FieldDailyIssued holds the string denoting the daily_issued field in the database.
	FieldDailyIssued = "daily_issued"
	// FieldDailyCap holds the string denoting the daily_cap field in the database.
	FieldDailyCap = "daily_cap"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the marketstate in the database.
	Table = "market_states"
)

// Columns holds all SQL columns for marketstate fields.
var Columns = []string{
	FieldID,
	FieldCurrentEvent,
	FieldEventRemainingTicks,
	FieldPityCounter,
	FieldCircuitLevel,
	FieldLastBreachAt,
	FieldLastPrice,
	FieldReserveBalance,
	FieldRevenueBalance,
	FieldBurnedTotal,
	FieldDailyIssuanceDate,
	FieldDailyIssued,
	FieldDailyCap,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCurrentEvent holds the default value on creation for the "current_event" field.
	DefaultCurrentEvent string
	// DefaultEventRemainingTicks holds the default value on creation for the "event_remaining_ticks" field.
	DefaultEventRemainingTicks int
	// DefaultPityCounter holds the default value on creation for the "pity_counter" field.
	DefaultPityCounter int
	// DefaultCircuitLevel holds the default value on creation for the "circuit_level" field.
	DefaultCircuitLevel string
	// DefaultLastPrice holds the default value on creation for the "last_price" field.
	DefaultLastPrice float64
	// DefaultReserveBalance holds the default value on creation for the "reserve_balance" field.
	DefaultReserveBalance int64
	// DefaultRevenueBalance holds the default value on creation for the "revenue_balance" field.
	DefaultRevenueBalance int64
	// DefaultBurnedTotal holds the default value on creation for the "burned_total" field.
	DefaultBurnedTotal int64
	// DefaultDailyIssuanceDate holds the default value on creation for the "daily_issuance_date" field.
	DefaultDailyIssuanceDate string
	// DefaultDailyIssued holds the default value on creation for the "daily_issued" field.
	DefaultDailyIssued int64
	// DefaultDailyCap holds the default value on creation for the "daily_cap" field.
	DefaultDailyCap int64
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the MarketState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCurrentEvent orders the results by the current_event field.
func ByCurrentEvent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentEvent, opts...).ToFunc()
}

// ByEventRemainingTicks orders the results by the event_remaining_ticks field.
func ByEventRemainingTicks(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventRemainingTicks, opts...).ToFunc()
}

// ByPityCounter orders the results by the pity_counter field.
func ByPityCounter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPityCounter, opts...).ToFunc()
}

// ByCircuitLevel orders the results by the circuit_level field.
func ByCircuitLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCircuitLevel, opts...).ToFunc()
}

// ByLastBreachAt orders the results by the last_breach_at field.
func ByLastBreachAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastBreachAt, opts...).ToFunc()
}

// ByLastPrice orders the results by the last_price field.
func ByLastPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPrice, opts...).ToFunc()
}

// ByReserveBalance orders the results by the reserve_balance field.
func ByReserveBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReserveBalance, opts...).ToFunc()
}

// ByRevenueBalance orders the results by the revenue_balance field.
func ByRevenueBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevenueBalance, opts...).ToFunc()
}

// ByBurnedTotal orders the results by the burned_total field.
func ByBurnedTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBurnedTotal, opts...).ToFunc()
}

// ByDailyIssuanceDate orders the results by the daily_issuance_date field.
func ByDailyIssuanceDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyIssuanceDate, opts...).ToFunc()
}

// ByDailyIssued orders the results by the daily_issued field.
func ByDailyIssued(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyIssued, opts...).ToFunc()
}

// ByDailyCap orders the results by the daily_cap field.
func ByDailyCap(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyCap, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
