// Code generated by ent, DO NOT EDIT.

package marketstate

import (
	"alt-bot/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MarketState {
	return predicate.MarketState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MarketState {
	return predicate.MarketState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MarketState {
	return predicate.MarketState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MarketState {
	return predicate.MarketState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MarketState {
	return predicate.MarketState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MarketState {
	return predicate.MarketState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MarketState {
	return predicate.MarketState(sql.FieldLTE(FieldID, id))
}

// CurrentEvent applies equality check predicate on the "current_event" field. It's identical to CurrentEventEQ.
func CurrentEvent(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldCurrentEvent, v))
}

// EventRemainingTicks applies equality check predicate on the "event_remaining_ticks" field. It's identical to EventRemainingTicksEQ.
func EventRemainingTicks(v int) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldEventRemainingTicks, v))
}

// PityCounter applies equality check predicate on the "pity_counter" field. It's identical to PityCounterEQ.
func PityCounter(v int) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldPityCounter, v))
}

// CircuitLevel applies equality check predicate on the "circuit_level" field. It's identical to CircuitLevelEQ.
func CircuitLevel(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldCircuitLevel, v))
}

// LastBreachAt applies equality check predicate on the "last_breach_at" field. It's identical to LastBreachAtEQ.
func LastBreachAt(v time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldLastBreachAt, v))
}

// LastPrice applies equality check predicate on the "last_price" field. It's identical to LastPriceEQ.
func LastPrice(v float64) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldLastPrice, v))
}

// ReserveBalance applies equality check predicate on the "reserve_balance" field. It's identical to ReserveBalanceEQ.
func ReserveBalance(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldReserveBalance, v))
}

// RevenueBalance applies equality check predicate on the "revenue_balance" field. It's identical to RevenueBalanceEQ.
func RevenueBalance(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldRevenueBalance, v))
}

// BurnedTotal applies equality check predicate on the "burned_total" field. It's identical to BurnedTotalEQ.
func BurnedTotal(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldBurnedTotal, v))
}

// DailyIssuanceDate applies equality check predicate on the "daily_issuance_date" field. It's identical to DailyIssuanceDateEQ.
func DailyIssuanceDate(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldDailyIssuanceDate, v))
}

// DailyIssued applies equality check predicate on the "daily_issued" field. It's identical to DailyIssuedEQ.
func DailyIssued(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldDailyIssued, v))
}

// DailyCap applies equality check predicate on the "daily_cap" field. It's identical to DailyCapEQ.
func DailyCap(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldDailyCap, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldUpdatedAt, v))
}

// CurrentEventEQ applies the EQ predicate on the "current_event" field.
func CurrentEventEQ(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldCurrentEvent, v))
}

// CurrentEventNEQ applies the NEQ predicate on the "current_event" field.
func CurrentEventNEQ(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldNEQ(FieldCurrentEvent, v))
}

// CurrentEventIn applies the In predicate on the "current_event" field.
func CurrentEventIn(vs ...string) predicate.MarketState {
	return predicate.MarketState(sql.FieldIn(FieldCurrentEvent, vs...))
}

// CurrentEventNotIn applies the NotIn predicate on the "current_event" field.
func CurrentEventNotIn(vs ...string) predicate.MarketState {
	return predicate.MarketState(sql.FieldNotIn(FieldCurrentEvent, vs...))
}

// CurrentEventGT applies the GT predicate on the "current_event" field.
func CurrentEventGT(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldGT(FieldCurrentEvent, v))
}

// CurrentEventGTE applies the GTE predicate on the "current_event" field.
func CurrentEventGTE(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldGTE(FieldCurrentEvent, v))
}

// CurrentEventLT applies the LT predicate on the "current_event" field.
func CurrentEventLT(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldLT(FieldCurrentEvent, v))
}

// CurrentEventLTE applies the LTE predicate on the "current_event" field.
func CurrentEventLTE(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldLTE(FieldCurrentEvent, v))
}

// CurrentEventContains applies the Contains predicate on the "current_event" field.
func CurrentEventContains(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldContains(FieldCurrentEvent, v))
}

// CurrentEventHasPrefix applies the HasPrefix predicate on the "current_event" field.
func CurrentEventHasPrefix(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldHasPrefix(FieldCurrentEvent, v))
}

// CurrentEventHasSuffix applies the HasSuffix predicate on the "current_event" field.
func CurrentEventHasSuffix(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldHasSuffix(FieldCurrentEvent, v))
}

// CurrentEventEqualFold applies the EqualFold predicate on the "current_event" field.
func CurrentEventEqualFold(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldEqualFold(FieldCurrentEvent, v))
}

// CurrentEventContainsFold applies the ContainsFold predicate on the "current_event" field.
func CurrentEventContainsFold(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldContainsFold(FieldCurrentEvent, v))
}

// EventRemainingTicksEQ applies the EQ predicate on the "event_remaining_ticks" field.
func EventRemainingTicksEQ(v int) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldEventRemainingTicks, v))
}

// EventRemainingTicksNEQ applies the NEQ predicate on the "event_remaining_ticks" field.
func EventRemainingTicksNEQ(v int) predicate.MarketState {
	return predicate.MarketState(sql.FieldNEQ(FieldEventRemainingTicks, v))
}

// EventRemainingTicksIn applies the In predicate on the "event_remaining_ticks" field.
func EventRemainingTicksIn(vs ...int) predicate.MarketState {
	return predicate.MarketState(sql.FieldIn(FieldEventRemainingTicks, vs...))
}

// EventRemainingTicksNotIn applies the NotIn predicate on the "event_remaining_ticks" field.
func EventRemainingTicksNotIn(vs ...int) predicate.MarketState {
	return predicate.MarketState(sql.FieldNotIn(FieldEventRemainingTicks, vs...))
}

// EventRemainingTicksGT applies the GT predicate on the "event_remaining_ticks" field.
func EventRemainingTicksGT(v int) predicate.MarketState {
	return predicate.MarketState(sql.FieldGT(FieldEventRemainingTicks, v))
}

// EventRemainingTicksGTE applies the GTE predicate on the "event_remaining_ticks" field.
func EventRemainingTicksGTE(v int) predicate.MarketState {
	return predicate.MarketState(sql.FieldGTE(FieldEventRemainingTicks, v))
}

// EventRemainingTicksLT applies the LT predicate on the "event_remaining_ticks" field.
func EventRemainingTicksLT(v int) predicate.MarketState {
	return predicate.MarketState(sql.FieldLT(FieldEventRemainingTicks, v))
}

// EventRemainingTicksLTE applies the LTE predicate on the "event_remaining_ticks" field.
func EventRemainingTicksLTE(v int) predicate.MarketState {
	return predicate.MarketState(sql.FieldLTE(FieldEventRemainingTicks, v))
}

// PityCounterEQ applies the EQ predicate on the "pity_counter" field.
func PityCounterEQ(v int) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldPityCounter, v))
}

// PityCounterNEQ applies the NEQ predicate on the "pity_counter" field.
func PityCounterNEQ(v int) predicate.MarketState {
	return predicate.MarketState(sql.FieldNEQ(FieldPityCounter, v))
}

// PityCounterIn applies the In predicate on the "pity_counter" field.
func PityCounterIn(vs ...int) predicate.MarketState {
	return predicate.MarketState(sql.FieldIn(FieldPityCounter, vs...))
}

// PityCounterNotIn applies the NotIn predicate on the "pity_counter" field.
func PityCounterNotIn(vs ...int) predicate.MarketState {
	return predicate.MarketState(sql.FieldNotIn(FieldPityCounter, vs...))
}

// PityCounterGT applies the GT predicate on the "pity_counter" field.
func PityCounterGT(v int) predicate.MarketState {
	return predicate.MarketState(sql.FieldGT(FieldPityCounter, v))
}

// PityCounterGTE applies the GTE predicate on the "pity_counter" field.
func PityCounterGTE(v int) predicate.MarketState {
	return predicate.MarketState(sql.FieldGTE(FieldPityCounter, v))
}

// PityCounterLT applies the LT predicate on the "pity_counter" field.
func PityCounterLT(v int) predicate.MarketState {
	return predicate.MarketState(sql.FieldLT(FieldPityCounter, v))
}

// PityCounterLTE applies the LTE predicate on the "pity_counter" field.
func PityCounterLTE(v int) predicate.MarketState {
	return predicate.MarketState(sql.FieldLTE(FieldPityCounter, v))
}

// CircuitLevelEQ applies the EQ predicate on the "circuit_level" field.
func CircuitLevelEQ(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldCircuitLevel, v))
}

// CircuitLevelNEQ applies the NEQ predicate on the "circuit_level" field.
func CircuitLevelNEQ(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldNEQ(FieldCircuitLevel, v))
}

// CircuitLevelIn applies the In predicate on the "circuit_level" field.
func CircuitLevelIn(vs ...string) predicate.MarketState {
	return predicate.MarketState(sql.FieldIn(FieldCircuitLevel, vs...))
}

// CircuitLevelNotIn applies the NotIn predicate on the "circuit_level" field.
func CircuitLevelNotIn(vs ...string) predicate.MarketState {
	return predicate.MarketState(sql.FieldNotIn(FieldCircuitLevel, vs...))
}

// CircuitLevelGT applies the GT predicate on the "circuit_level" field.
func CircuitLevelGT(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldGT(FieldCircuitLevel, v))
}

// CircuitLevelGTE applies the GTE predicate on the "circuit_level" field.
func CircuitLevelGTE(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldGTE(FieldCircuitLevel, v))
}

// CircuitLevelLT applies the LT predicate on the "circuit_level" field.
func CircuitLevelLT(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldLT(FieldCircuitLevel, v))
}

// CircuitLevelLTE applies the LTE predicate on the "circuit_level" field.
func CircuitLevelLTE(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldLTE(FieldCircuitLevel, v))
}

// CircuitLevelContains applies the Contains predicate on the "circuit_level" field.
func CircuitLevelContains(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldContains(FieldCircuitLevel, v))
}

// CircuitLevelHasPrefix applies the HasPrefix predicate on the "circuit_level" field.
func CircuitLevelHasPrefix(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldHasPrefix(FieldCircuitLevel, v))
}

// CircuitLevelHasSuffix applies the HasSuffix predicate on the "circuit_level" field.
func CircuitLevelHasSuffix(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldHasSuffix(FieldCircuitLevel, v))
}

// CircuitLevelEqualFold applies the EqualFold predicate on the "circuit_level" field.
func CircuitLevelEqualFold(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldEqualFold(FieldCircuitLevel, v))
}

// CircuitLevelContainsFold applies the ContainsFold predicate on the "circuit_level" field.
func CircuitLevelContainsFold(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldContainsFold(FieldCircuitLevel, v))
}

// LastBreachAtEQ applies the EQ predicate on the "last_breach_at" field.
func LastBreachAtEQ(v time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldLastBreachAt, v))
}

// LastBreachAtNEQ applies the NEQ predicate on the "last_breach_at" field.
func LastBreachAtNEQ(v time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldNEQ(FieldLastBreachAt, v))
}

// LastBreachAtIn applies the In predicate on the "last_breach_at" field.
func LastBreachAtIn(vs ...time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldIn(FieldLastBreachAt, vs...))
}

// LastBreachAtNotIn applies the NotIn predicate on the "last_breach_at" field.
func LastBreachAtNotIn(vs ...time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldNotIn(FieldLastBreachAt, vs...))
}

// LastBreachAtGT applies the GT predicate on the "last_breach_at" field.
func LastBreachAtGT(v time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldGT(FieldLastBreachAt, v))
}

// LastBreachAtGTE applies the GTE predicate on the "last_breach_at" field.
func LastBreachAtGTE(v time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldGTE(FieldLastBreachAt, v))
}

// LastBreachAtLT applies the LT predicate on the "last_breach_at" field.
func LastBreachAtLT(v time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldLT(FieldLastBreachAt, v))
}

// LastBreachAtLTE applies the LTE predicate on the "last_breach_at" field.
func LastBreachAtLTE(v time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldLTE(FieldLastBreachAt, v))
}

// LastBreachAtIsNil applies the IsNil predicate on the "last_breach_at" field.
func LastBreachAtIsNil() predicate.MarketState {
	return predicate.MarketState(sql.FieldIsNull(FieldLastBreachAt))
}

// LastBreachAtNotNil applies the NotNil predicate on the "last_breach_at" field.
func LastBreachAtNotNil() predicate.MarketState {
	return predicate.MarketState(sql.FieldNotNull(FieldLastBreachAt))
}

// LastPriceEQ applies the EQ predicate on the "last_price" field.
func LastPriceEQ(v float64) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldLastPrice, v))
}

// LastPriceNEQ applies the NEQ predicate on the "last_price" field.
func LastPriceNEQ(v float64) predicate.MarketState {
	return predicate.MarketState(sql.FieldNEQ(FieldLastPrice, v))
}

// LastPriceIn applies the In predicate on the "last_price" field.
func LastPriceIn(vs ...float64) predicate.MarketState {
	return predicate.MarketState(sql.FieldIn(FieldLastPrice, vs...))
}

// LastPriceNotIn applies the NotIn predicate on the "last_price" field.
func LastPriceNotIn(vs ...float64) predicate.MarketState {
	return predicate.MarketState(sql.FieldNotIn(FieldLastPrice, vs...))
}

// LastPriceGT applies the GT predicate on the "last_price" field.
func LastPriceGT(v float64) predicate.MarketState {
	return predicate.MarketState(sql.FieldGT(FieldLastPrice, v))
}

// LastPriceGTE applies the GTE predicate on the "last_price" field.
func LastPriceGTE(v float64) predicate.MarketState {
	return predicate.MarketState(sql.FieldGTE(FieldLastPrice, v))
}

// LastPriceLT applies the LT predicate on the "last_price" field.
func LastPriceLT(v float64) predicate.MarketState {
	return predicate.MarketState(sql.FieldLT(FieldLastPrice, v))
}

// LastPriceLTE applies the LTE predicate on the "last_price" field.
func LastPriceLTE(v float64) predicate.MarketState {
	return predicate.MarketState(sql.FieldLTE(FieldLastPrice, v))
}

// ReserveBalanceEQ applies the EQ predicate on the "reserve_balance" field.
func ReserveBalanceEQ(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldReserveBalance, v))
}

// ReserveBalanceNEQ applies the NEQ predicate on the "reserve_balance" field.
func ReserveBalanceNEQ(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldNEQ(FieldReserveBalance, v))
}

// ReserveBalanceIn applies the In predicate on the "reserve_balance" field.
func ReserveBalanceIn(vs ...int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldIn(FieldReserveBalance, vs...))
}

// ReserveBalanceNotIn applies the NotIn predicate on the "reserve_balance" field.
func ReserveBalanceNotIn(vs ...int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldNotIn(FieldReserveBalance, vs...))
}

// ReserveBalanceGT applies the GT predicate on the "reserve_balance" field.
func ReserveBalanceGT(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldGT(FieldReserveBalance, v))
}

// ReserveBalanceGTE applies the GTE predicate on the "reserve_balance" field.
func ReserveBalanceGTE(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldGTE(FieldReserveBalance, v))
}

// ReserveBalanceLT applies the LT predicate on the "reserve_balance" field.
func ReserveBalanceLT(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldLT(FieldReserveBalance, v))
}

// ReserveBalanceLTE applies the LTE predicate on the "reserve_balance" field.
func ReserveBalanceLTE(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldLTE(FieldReserveBalance, v))
}

// RevenueBalanceEQ applies the EQ predicate on the "revenue_balance" field.
func RevenueBalanceEQ(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldRevenueBalance, v))
}

// RevenueBalanceNEQ applies the NEQ predicate on the "revenue_balance" field.
func RevenueBalanceNEQ(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldNEQ(FieldRevenueBalance, v))
}

// RevenueBalanceIn applies the In predicate on the "revenue_balance" field.
func RevenueBalanceIn(vs ...int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldIn(FieldRevenueBalance, vs...))
}

// RevenueBalanceNotIn applies the NotIn predicate on the "revenue_balance" field.
func RevenueBalanceNotIn(vs ...int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldNotIn(FieldRevenueBalance, vs...))
}

// RevenueBalanceGT applies the GT predicate on the "revenue_balance" field.
func RevenueBalanceGT(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldGT(FieldRevenueBalance, v))
}

// RevenueBalanceGTE applies the GTE predicate on the "revenue_balance" field.
func RevenueBalanceGTE(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldGTE(FieldRevenueBalance, v))
}

// RevenueBalanceLT applies the LT predicate on the "revenue_balance" field.
func RevenueBalanceLT(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldLT(FieldRevenueBalance, v))
}

// RevenueBalanceLTE applies the LTE predicate on the "revenue_balance" field.
func RevenueBalanceLTE(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldLTE(FieldRevenueBalance, v))
}

// BurnedTotalEQ applies the EQ predicate on the "burned_total" field.
func BurnedTotalEQ(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldBurnedTotal, v))
}

// BurnedTotalNEQ applies the NEQ predicate on the "burned_total" field.
func BurnedTotalNEQ(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldNEQ(FieldBurnedTotal, v))
}

// BurnedTotalIn applies the In predicate on the "burned_total" field.
func BurnedTotalIn(vs ...int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldIn(FieldBurnedTotal, vs...))
}

// BurnedTotalNotIn applies the NotIn predicate on the "burned_total" field.
func BurnedTotalNotIn(vs ...int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldNotIn(FieldBurnedTotal, vs...))
}

// BurnedTotalGT applies the GT predicate on the "burned_total" field.
func BurnedTotalGT(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldGT(FieldBurnedTotal, v))
}

// BurnedTotalGTE applies the GTE predicate on the "burned_total" field.
func BurnedTotalGTE(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldGTE(FieldBurnedTotal, v))
}

// BurnedTotalLT applies the LT predicate on the "burned_total" field.
func BurnedTotalLT(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldLT(FieldBurnedTotal, v))
}

// BurnedTotalLTE applies the LTE predicate on the "burned_total" field.
func BurnedTotalLTE(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldLTE(FieldBurnedTotal, v))
}

// DailyIssuanceDateEQ applies the EQ predicate on the "daily_issuance_date" field.
func DailyIssuanceDateEQ(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldDailyIssuanceDate, v))
}

// DailyIssuanceDateNEQ applies the NEQ predicate on the "daily_issuance_date" field.
func DailyIssuanceDateNEQ(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldNEQ(FieldDailyIssuanceDate, v))
}

// DailyIssuanceDateIn applies the In predicate on the "daily_issuance_date" field.
func DailyIssuanceDateIn(vs ...string) predicate.MarketState {
	return predicate.MarketState(sql.FieldIn(FieldDailyIssuanceDate, vs...))
}

// DailyIssuanceDateNotIn applies the NotIn predicate on the "daily_issuance_date" field.
func DailyIssuanceDateNotIn(vs ...string) predicate.MarketState {
	return predicate.MarketState(sql.FieldNotIn(FieldDailyIssuanceDate, vs...))
}

// DailyIssuanceDateGT applies the GT predicate on the "daily_issuance_date" field.
func DailyIssuanceDateGT(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldGT(FieldDailyIssuanceDate, v))
}

// DailyIssuanceDateGTE applies the GTE predicate on the "daily_issuance_date" field.
func DailyIssuanceDateGTE(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldGTE(FieldDailyIssuanceDate, v))
}

// DailyIssuanceDateLT applies the LT predicate on the "daily_issuance_date" field.
func DailyIssuanceDateLT(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldLT(FieldDailyIssuanceDate, v))
}

// DailyIssuanceDateLTE applies the LTE predicate on the "daily_issuance_date" field.
func DailyIssuanceDateLTE(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldLTE(FieldDailyIssuanceDate, v))
}

// DailyIssuanceDateContains applies the Contains predicate on the "daily_issuance_date" field.
func DailyIssuanceDateContains(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldContains(FieldDailyIssuanceDate, v))
}

// DailyIssuanceDateHasPrefix applies the HasPrefix predicate on the "daily_issuance_date" field.
func DailyIssuanceDateHasPrefix(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldHasPrefix(FieldDailyIssuanceDate, v))
}

// DailyIssuanceDateHasSuffix applies the HasSuffix predicate on the "daily_issuance_date" field.
func DailyIssuanceDateHasSuffix(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldHasSuffix(FieldDailyIssuanceDate, v))
}

// DailyIssuanceDateEqualFold applies the EqualFold predicate on the "daily_issuance_date" field.
func DailyIssuanceDateEqualFold(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldEqualFold(FieldDailyIssuanceDate, v))
}

// DailyIssuanceDateContainsFold applies the ContainsFold predicate on the "daily_issuance_date" field.
func DailyIssuanceDateContainsFold(v string) predicate.MarketState {
	return predicate.MarketState(sql.FieldContainsFold(FieldDailyIssuanceDate, v))
}

// DailyIssuedEQ applies the EQ predicate on the "daily_issued" field.
func DailyIssuedEQ(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldDailyIssued, v))
}

// DailyIssuedNEQ applies the NEQ predicate on the "daily_issued" field.
func DailyIssuedNEQ(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldNEQ(FieldDailyIssued, v))
}

// DailyIssuedIn applies the In predicate on the "daily_issued" field.
func DailyIssuedIn(vs ...int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldIn(FieldDailyIssued, vs...))
}

// DailyIssuedNotIn applies the NotIn predicate on the "daily_issued" field.
func DailyIssuedNotIn(vs ...int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldNotIn(FieldDailyIssued, vs...))
}

// DailyIssuedGT applies the GT predicate on the "daily_issued" field.
func DailyIssuedGT(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldGT(FieldDailyIssued, v))
}

// DailyIssuedGTE applies the GTE predicate on the "daily_issued" field.
func DailyIssuedGTE(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldGTE(FieldDailyIssued, v))
}

// DailyIssuedLT applies the LT predicate on the "daily_issued" field.
func DailyIssuedLT(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldLT(FieldDailyIssued, v))
}

// DailyIssuedLTE applies the LTE predicate on the "daily_issued" field.
func DailyIssuedLTE(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldLTE(FieldDailyIssued, v))
}

// DailyCapEQ applies the EQ predicate on the "daily_cap" field.
func DailyCapEQ(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldDailyCap, v))
}

// DailyCapNEQ applies the NEQ predicate on the "daily_cap" field.
func DailyCapNEQ(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldNEQ(FieldDailyCap, v))
}

// DailyCapIn applies the In predicate on the "daily_cap" field.
func DailyCapIn(vs ...int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldIn(FieldDailyCap, vs...))
}

// DailyCapNotIn applies the NotIn predicate on the "daily_cap" field.
func DailyCapNotIn(vs ...int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldNotIn(FieldDailyCap, vs...))
}

// DailyCapGT applies the GT predicate on the "daily_cap" field.
func DailyCapGT(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldGT(FieldDailyCap, v))
}

// DailyCapGTE applies the GTE predicate on the "daily_cap" field.
func DailyCapGTE(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldGTE(FieldDailyCap, v))
}

// DailyCapLT applies the LT predicate on the "daily_cap" field.
func DailyCapLT(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldLT(FieldDailyCap, v))
}

// DailyCapLTE applies the LTE predicate on the "daily_cap" field.
func DailyCapLTE(v int64) predicate.MarketState {
	return predicate.MarketState(sql.FieldLTE(FieldDailyCap, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MarketState {
	return predicate.MarketState(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MarketState) predicate.MarketState {
	return predicate.MarketState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MarketState) predicate.MarketState {
	return predicate.MarketState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MarketState) predicate.MarketState {
	return predicate.MarketState(sql.NotPredicates(p))
}
