apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yml
  - serviceaccount.yml
  - sealed-secret.yml
  - configmap.yml
  - psql-service.yml
  - psql-statefulset.yml
  - deployment.yml
  - pdb.yml

images:
  - name: docker.io/kemar1/alt-bot
    newTag: 1.2.1
