// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GuildsColumns holds the columns for the "guilds" table.
	GuildsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "guild_id", Type: field.TypeString, Unique: true},
		{Name: "news_channel_id", Type: field.TypeString},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GuildsTable holds the schema information for the "guilds" table.
	GuildsTable = &schema.Table{
		Name:       "guilds",
		Columns:    GuildsColumns,
		PrimaryKey: []*schema.Column{GuildsColumns[0]},
	}
	// MarketStatesColumns holds the columns for the "market_states" table.
	MarketStatesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "current_event", Type: field.TypeString, Default: ""},
		{Name: "event_remaining_ticks", Type: field.TypeInt, Default: 0},
		{Name: "pity_counter", Type: field.TypeInt, Default: 0},
		{Name: "circuit_level", Type: field.TypeString, Default: "NORMAL"},
		{Name: "last_breach_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_price", Type: field.TypeFloat64, Default: 100},
		{Name: "reserve_balance", Type: field.TypeInt64, Default: 0},
		{Name: "revenue_balance", Type: field.TypeInt64, Default: 0},
		{Name: "burned_total", Type: field.TypeInt64, Default: 0},
		{Name: "daily_issuance_date", Type: field.TypeString, Default: ""},
		{Name: "daily_issued", Type: field.TypeInt64, Default: 0},
		{Name: "daily_cap", Type: field.TypeInt64, Default: 20000},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// MarketStatesTable holds the schema information for the "market_states" table.
	MarketStatesTable = &schema.Table{
		Name:       "market_states",
		Columns:    MarketStatesColumns,
		PrimaryKey: []*schema.Column{MarketStatesColumns[0]},
	}
	// PriceHistoriesColumns holds the columns for the "price_histories" table.
	PriceHistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "created_at", Type: field.TypeTime},
	}
	// PriceHistoriesTable holds the schema information for the "price_histories" table.
	PriceHistoriesTable = &schema.Table{
		Name:       "price_histories",
		Columns:    PriceHistoriesColumns,
		PrimaryKey: []*schema.Column{PriceHistoriesColumns[0]},
	}
	// TransactionLogsColumns holds the columns for the "transaction_logs" table.
	TransactionLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "tx_id", Type: field.TypeString, Unique: true},
		{Name: "user_discord_id", Type: field.TypeString},
		{Name: "kind", Type: field.TypeString},
		{Name: "yen_delta", Type: field.TypeInt64, Default: 0},
		{Name: "alt_delta", Type: field.TypeInt64, Default: 0},
		{Name: "xp_delta", Type: field.TypeInt64, Default: 0},
		{Name: "amount", Type: field.TypeInt64, Default: 0},
		{Name: "settled_price", Type: field.TypeFloat64, Default: 0},
		{Name: "price_after", Type: field.TypeFloat64, Default: 0},
		{Name: "balance_after", Type: field.TypeInt64, Default: 0},
		{Name: "crypto_after", Type: field.TypeInt64, Default: 0},
		{Name: "prev_hash", Type: field.TypeString, Default: ""},
		{Name: "hash", Type: field.TypeString},
		{Name: "signature", Type: field.TypeString},
		{Name: "public_key", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// TransactionLogsTable holds the schema information for the "transaction_logs" table.
	TransactionLogsTable = &schema.Table{
		Name:       "transaction_logs",
		Columns:    TransactionLogsColumns,
		PrimaryKey: []*schema.Column{TransactionLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "transactionlog_created_at",
				Unique:  false,
				Columns: []*schema.Column{TransactionLogsColumns[16]},
			},
			{
				Name:    "transactionlog_user_discord_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{TransactionLogsColumns[2], TransactionLogsColumns[16]},
			},
			{
				Name:    "transactionlog_kind_created_at",
				Unique:  false,
				Columns: []*schema.Column{TransactionLogsColumns[3], TransactionLogsColumns[16]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "discord_id", Type: field.TypeString, Unique: true},
		{Name: "balance", Type: field.TypeInt64, Default: 0},
		{Name: "crypto_balance", Type: field.TypeInt64, Default: 0},
		{Name: "xp", Type: field.TypeInt64, Default: 0},
		{Name: "work_end_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_discord_id",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GuildsTable,
		MarketStatesTable,
		PriceHistoriesTable,
		TransactionLogsTable,
		UsersTable,
	}
)

func init() {
}
