// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"alt-bot/ent/migrate"

	"alt-bot/ent/guild"
	"alt-bot/ent/marketstate"
	"alt-bot/ent/pricehistory"
	"alt-bot/ent/transactionlog"
	"alt-bot/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Guild is the client for interacting with the Guild builders.
	Guild *GuildClient
	// MarketState is the client for interacting with the MarketState builders.
	MarketState *MarketStateClient
	// PriceHistory is the client for interacting with the PriceHistory builders.
	PriceHistory *PriceHistoryClient
	// TransactionLog is the client for interacting with the TransactionLog builders.
	TransactionLog *TransactionLogClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Guild = NewGuildClient(c.config)
	c.MarketState = NewMarketStateClient(c.config)
	c.PriceHistory = NewPriceHistoryClient(c.config)
	c.TransactionLog = NewTransactionLogClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Guild:          NewGuildClient(cfg),
		MarketState:    NewMarketStateClient(cfg),
		PriceHistory:   NewPriceHistoryClient(cfg),
		TransactionLog: NewTransactionLogClient(cfg),
		User:           NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		Guild:          NewGuildClient(cfg),
		MarketState:    NewMarketStateClient(cfg),
		PriceHistory:   NewPriceHistoryClient(cfg),
		TransactionLog: NewTransactionLogClient(cfg),
		User:           NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Guild.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Guild.Use(hooks...)
	c.MarketState.Use(hooks...)
	c.PriceHistory.Use(hooks...)
	c.TransactionLog.Use(hooks...)
	c.User.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Guild.Intercept(interceptors...)
	c.MarketState.Intercept(interceptors...)
	c.PriceHistory.Intercept(interceptors...)
	c.TransactionLog.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *GuildMutation:
		return c.Guild.mutate(ctx, m)
	case *MarketStateMutation:
		return c.MarketState.mutate(ctx, m)
	case *PriceHistoryMutation:
		return c.PriceHistory.mutate(ctx, m)
	case *TransactionLogMutation:
		return c.TransactionLog.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// GuildClient is a client for the Guild schema.
type GuildClient struct {
	config
}

// NewGuildClient returns a client for the Guild from the given config.
func NewGuildClient(c config) *GuildClient {
	return &GuildClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `guild.Hooks(f(g(h())))`.
func (c *GuildClient) Use(hooks ...Hook) {
	c.hooks.Guild = append(c.hooks.Guild, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `guild.Intercept(f(g(h())))`.
func (c *GuildClient) Intercept(interceptors ...Interceptor) {
	c.inters.Guild = append(c.inters.Guild, interceptors...)
}

// Create returns a builder for creating a Guild entity.
func (c *GuildClient) Create() *GuildCreate {
	mutation := newGuildMutation(c.config, OpCreate)
	return &GuildCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Guild entities.
func (c *GuildClient) CreateBulk(builders ...*GuildCreate) *GuildCreateBulk {
	return &GuildCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GuildClient) MapCreateBulk(slice any, setFunc func(*GuildCreate, int)) *GuildCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GuildCreateBulk{err: fmt.Errorf("calling to GuildClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GuildCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GuildCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Guild.
func (c *GuildClient) Update() *GuildUpdate {
	mutation := newGuildMutation(c.config, OpUpdate)
	return &GuildUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GuildClient) UpdateOne(_m *Guild) *GuildUpdateOne {
	mutation := newGuildMutation(c.config, OpUpdateOne, withGuild(_m))
	return &GuildUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GuildClient) UpdateOneID(id int) *GuildUpdateOne {
	mutation := newGuildMutation(c.config, OpUpdateOne, withGuildID(id))
	return &GuildUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Guild.
func (c *GuildClient) Delete() *GuildDelete {
	mutation := newGuildMutation(c.config, OpDelete)
	return &GuildDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GuildClient) DeleteOne(_m *Guild) *GuildDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GuildClient) DeleteOneID(id int) *GuildDeleteOne {
	builder := c.Delete().Where(guild.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GuildDeleteOne{builder}
}

// Query returns a query builder for Guild.
func (c *GuildClient) Query() *GuildQuery {
	return &GuildQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGuild},
		inters: c.Interceptors(),
	}
}

// Get returns a Guild entity by its id.
func (c *GuildClient) Get(ctx context.Context, id int) (*Guild, error) {
	return c.Query().Where(guild.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GuildClient) GetX(ctx context.Context, id int) *Guild {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *GuildClient) Hooks() []Hook {
	return c.hooks.Guild
}

// Interceptors returns the client interceptors.
func (c *GuildClient) Interceptors() []Interceptor {
	return c.inters.Guild
}

func (c *GuildClient) mutate(ctx context.Context, m *GuildMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GuildCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GuildUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GuildUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GuildDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Guild mutation op: %q", m.Op())
	}
}

// MarketStateClient is a client for the MarketState schema.
type MarketStateClient struct {
	config
}

// NewMarketStateClient returns a client for the MarketState from the given config.
func NewMarketStateClient(c config) *MarketStateClient {
	return &MarketStateClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `marketstate.Hooks(f(g(h())))`.
func (c *MarketStateClient) Use(hooks ...Hook) {
	c.hooks.MarketState = append(c.hooks.MarketState, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `marketstate.Intercept(f(g(h())))`.
func (c *MarketStateClient) Intercept(interceptors ...Interceptor) {
	c.inters.MarketState = append(c.inters.MarketState, interceptors...)
}

// Create returns a builder for creating a MarketState entity.
func (c *MarketStateClient) Create() *MarketStateCreate {
	mutation := newMarketStateMutation(c.config, OpCreate)
	return &MarketStateCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MarketState entities.
func (c *MarketStateClient) CreateBulk(builders ...*MarketStateCreate) *MarketStateCreateBulk {
	return &MarketStateCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MarketStateClient) MapCreateBulk(slice any, setFunc func(*MarketStateCreate, int)) *MarketStateCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MarketStateCreateBulk{err: fmt.Errorf("calling to MarketStateClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MarketStateCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MarketStateCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MarketState.
func (c *MarketStateClient) Update() *MarketStateUpdate {
	mutation := newMarketStateMutation(c.config, OpUpdate)
	return &MarketStateUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MarketStateClient) UpdateOne(_m *MarketState) *MarketStateUpdateOne {
	mutation := newMarketStateMutation(c.config, OpUpdateOne, withMarketState(_m))
	return &MarketStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MarketStateClient) UpdateOneID(id int) *MarketStateUpdateOne {
	mutation := newMarketStateMutation(c.config, OpUpdateOne, withMarketStateID(id))
	return &MarketStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MarketState.
func (c *MarketStateClient) Delete() *MarketStateDelete {
	mutation := newMarketStateMutation(c.config, OpDelete)
	return &MarketStateDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MarketStateClient) DeleteOne(_m *MarketState) *MarketStateDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MarketStateClient) DeleteOneID(id int) *MarketStateDeleteOne {
	builder := c.Delete().Where(marketstate.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MarketStateDeleteOne{builder}
}

// Query returns a query builder for MarketState.
func (c *MarketStateClient) Query() *MarketStateQuery {
	return &MarketStateQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMarketState},
		inters: c.Interceptors(),
	}
}

// Get returns a MarketState entity by its id.
func (c *MarketStateClient) Get(ctx context.Context, id int) (*MarketState, error) {
	return c.Query().Where(marketstate.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MarketStateClient) GetX(ctx context.Context, id int) *MarketState {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MarketStateClient) Hooks() []Hook {
	return c.hooks.MarketState
}

// Interceptors returns the client interceptors.
func (c *MarketStateClient) Interceptors() []Interceptor {
	return c.inters.MarketState
}

func (c *MarketStateClient) mutate(ctx context.Context, m *MarketStateMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MarketStateCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MarketStateUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MarketStateUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MarketStateDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown MarketState mutation op: %q", m.Op())
	}
}

// PriceHistoryClient is a client for the PriceHistory schema.
type PriceHistoryClient struct {
	config
}

// NewPriceHistoryClient returns a client for the PriceHistory from the given config.
func NewPriceHistoryClient(c config) *PriceHistoryClient {
	return &PriceHistoryClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `pricehistory.Hooks(f(g(h())))`.
func (c *PriceHistoryClient) Use(hooks ...Hook) {
	c.hooks.PriceHistory = append(c.hooks.PriceHistory, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `pricehistory.Intercept(f(g(h())))`.
func (c *PriceHistoryClient) Intercept(interceptors ...Interceptor) {
	c.inters.PriceHistory = append(c.inters.PriceHistory, interceptors...)
}

// Create returns a builder for creating a PriceHistory entity.
func (c *PriceHistoryClient) Create() *PriceHistoryCreate {
	mutation := newPriceHistoryMutation(c.config, OpCreate)
	return &PriceHistoryCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PriceHistory entities.
func (c *PriceHistoryClient) CreateBulk(builders ...*PriceHistoryCreate) *PriceHistoryCreateBulk {
	return &PriceHistoryCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PriceHistoryClient) MapCreateBulk(slice any, setFunc func(*PriceHistoryCreate, int)) *PriceHistoryCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PriceHistoryCreateBulk{err: fmt.Errorf("calling to PriceHistoryClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PriceHistoryCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PriceHistoryCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PriceHistory.
func (c *PriceHistoryClient) Update() *PriceHistoryUpdate {
	mutation := newPriceHistoryMutation(c.config, OpUpdate)
	return &PriceHistoryUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PriceHistoryClient) UpdateOne(_m *PriceHistory) *PriceHistoryUpdateOne {
	mutation := newPriceHistoryMutation(c.config, OpUpdateOne, withPriceHistory(_m))
	return &PriceHistoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PriceHistoryClient) UpdateOneID(id int) *PriceHistoryUpdateOne {
	mutation := newPriceHistoryMutation(c.config, OpUpdateOne, withPriceHistoryID(id))
	return &PriceHistoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PriceHistory.
func (c *PriceHistoryClient) Delete() *PriceHistoryDelete {
	mutation := newPriceHistoryMutation(c.config, OpDelete)
	return &PriceHistoryDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PriceHistoryClient) DeleteOne(_m *PriceHistory) *PriceHistoryDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PriceHistoryClient) DeleteOneID(id int) *PriceHistoryDeleteOne {
	builder := c.Delete().Where(pricehistory.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PriceHistoryDeleteOne{builder}
}

// Query returns a query builder for PriceHistory.
func (c *PriceHistoryClient) Query() *PriceHistoryQuery {
	return &PriceHistoryQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePriceHistory},
		inters: c.Interceptors(),
	}
}

// Get returns a PriceHistory entity by its id.
func (c *PriceHistoryClient) Get(ctx context.Context, id int) (*PriceHistory, error) {
	return c.Query().Where(pricehistory.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PriceHistoryClient) GetX(ctx context.Context, id int) *PriceHistory {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PriceHistoryClient) Hooks() []Hook {
	return c.hooks.PriceHistory
}

// Interceptors returns the client interceptors.
func (c *PriceHistoryClient) Interceptors() []Interceptor {
	return c.inters.PriceHistory
}

func (c *PriceHistoryClient) mutate(ctx context.Context, m *PriceHistoryMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PriceHistoryCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PriceHistoryUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PriceHistoryUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PriceHistoryDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PriceHistory mutation op: %q", m.Op())
	}
}

// TransactionLogClient is a client for the TransactionLog schema.
type TransactionLogClient struct {
	config
}

// NewTransactionLogClient returns a client for the TransactionLog from the given config.
func NewTransactionLogClient(c config) *TransactionLogClient {
	return &TransactionLogClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `transactionlog.Hooks(f(g(h())))`.
func (c *TransactionLogClient) Use(hooks ...Hook) {
	c.hooks.TransactionLog = append(c.hooks.TransactionLog, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `transactionlog.Intercept(f(g(h())))`.
func (c *TransactionLogClient) Intercept(interceptors ...Interceptor) {
	c.inters.TransactionLog = append(c.inters.TransactionLog, interceptors...)
}

// Create returns a builder for creating a TransactionLog entity.
func (c *TransactionLogClient) Create() *TransactionLogCreate {
	mutation := newTransactionLogMutation(c.config, OpCreate)
	return &TransactionLogCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TransactionLog entities.
func (c *TransactionLogClient) CreateBulk(builders ...*TransactionLogCreate) *TransactionLogCreateBulk {
	return &TransactionLogCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TransactionLogClient) MapCreateBulk(slice any, setFunc func(*TransactionLogCreate, int)) *TransactionLogCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TransactionLogCreateBulk{err: fmt.Errorf("calling to TransactionLogClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TransactionLogCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TransactionLogCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TransactionLog.
func (c *TransactionLogClient) Update() *TransactionLogUpdate {
	mutation := newTransactionLogMutation(c.config, OpUpdate)
	return &TransactionLogUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TransactionLogClient) UpdateOne(_m *TransactionLog) *TransactionLogUpdateOne {
	mutation := newTransactionLogMutation(c.config, OpUpdateOne, withTransactionLog(_m))
	return &TransactionLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TransactionLogClient) UpdateOneID(id int) *TransactionLogUpdateOne {
	mutation := newTransactionLogMutation(c.config, OpUpdateOne, withTransactionLogID(id))
	return &TransactionLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TransactionLog.
func (c *TransactionLogClient) Delete() *TransactionLogDelete {
	mutation := newTransactionLogMutation(c.config, OpDelete)
	return &TransactionLogDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TransactionLogClient) DeleteOne(_m *TransactionLog) *TransactionLogDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TransactionLogClient) DeleteOneID(id int) *TransactionLogDeleteOne {
	builder := c.Delete().Where(transactionlog.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TransactionLogDeleteOne{builder}
}

// Query returns a query builder for TransactionLog.
func (c *TransactionLogClient) Query() *TransactionLogQuery {
	return &TransactionLogQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTransactionLog},
		inters: c.Interceptors(),
	}
}

// Get returns a TransactionLog entity by its id.
func (c *TransactionLogClient) Get(ctx context.Context, id int) (*TransactionLog, error) {
	return c.Query().Where(transactionlog.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TransactionLogClient) GetX(ctx context.Context, id int) *TransactionLog {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TransactionLogClient) Hooks() []Hook {
	return c.hooks.TransactionLog
}

// Interceptors returns the client interceptors.
func (c *TransactionLogClient) Interceptors() []Interceptor {
	return c.inters.TransactionLog
}

func (c *TransactionLogClient) mutate(ctx context.Context, m *TransactionLogMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TransactionLogCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TransactionLogUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TransactionLogUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TransactionLogDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TransactionLog mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Guild, MarketState, PriceHistory, TransactionLog, User []ent.Hook
	}
	inters struct {
		Guild, MarketState, PriceHistory, TransactionLog, User []ent.Interceptor
	}
)
