// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alt-bot/ent/guild"
	"alt-bot/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GuildUpdate is the builder for updating Guild entities.
type GuildUpdate struct {
	config
	hooks    []Hook
	mutation *GuildMutation
}

// Where appends a list predicates to the GuildUpdate builder.
func (_u *GuildUpdate) Where(ps ...predicate.Guild) *GuildUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGuildID sets the "guild_id" field.
func (_u *GuildUpdate) SetGuildID(v string) *GuildUpdate {
	_u.mutation.SetGuildID(v)
	return _u
}

// SetNillableGuildID sets the "guild_id" field if the given value is not nil.
func (_u *GuildUpdate) SetNillableGuildID(v *string) *GuildUpdate {
	if v != nil {
		_u.SetGuildID(*v)
	}
	return _u
}

// SetNewsChannelID sets the "news_channel_id" field.
func (_u *GuildUpdate) SetNewsChannelID(v string) *GuildUpdate {
	_u.mutation.SetNewsChannelID(v)
	return _u
}

// SetNillableNewsChannelID sets the "news_channel_id" field if the given value is not nil.
func (_u *GuildUpdate) SetNillableNewsChannelID(v *string) *GuildUpdate {
	if v != nil {
		_u.SetNewsChannelID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GuildUpdate) SetUpdatedAt(v time.Time) *GuildUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GuildMutation object of the builder.
func (_u *GuildUpdate) Mutation() *GuildMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GuildUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GuildUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GuildUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GuildUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GuildUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := guild.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GuildUpdate) check() error {
	if v, ok := _u.mutation.GuildID(); ok {
		if err := guild.GuildIDValidator(v); err != nil {
			return &ValidationError{Name: "guild_id", err: fmt.Errorf(`ent: validator failed for field "Guild.guild_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NewsChannelID(); ok {
		if err := guild.NewsChannelIDValidator(v); err != nil {
			return &ValidationError{Name: "news_channel_id", err: fmt.Errorf(`ent: validator failed for field "Guild.news_channel_id": %w`, err)}
		}
	}
	return nil
}

func (_u *GuildUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(guild.Table, guild.Columns, sqlgraph.NewFieldSpec(guild.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GuildID(); ok {
		_spec.SetField(guild.FieldGuildID, field.TypeString, value)
	}
	if value, ok := _u.mutation.NewsChannelID(); ok {
		_spec.SetField(guild.FieldNewsChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(guild.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{guild.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GuildUpdateOne is the builder for updating a single Guild entity.
type GuildUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GuildMutation
}

// SetGuildID sets the "guild_id" field.
func (_u *GuildUpdateOne) SetGuildID(v string) *GuildUpdateOne {
	_u.mutation.SetGuildID(v)
	return _u
}

// SetNillableGuildID sets the "guild_id" field if the given value is not nil.
func (_u *GuildUpdateOne) SetNillableGuildID(v *string) *GuildUpdateOne {
	if v != nil {
		_u.SetGuildID(*v)
	}
	return _u
}

// SetNewsChannelID sets the "news_channel_id" field.
func (_u *GuildUpdateOne) SetNewsChannelID(v string) *GuildUpdateOne {
	_u.mutation.SetNewsChannelID(v)
	return _u
}

// SetNillableNewsChannelID sets the "news_channel_id" field if the given value is not nil.
func (_u *GuildUpdateOne) SetNillableNewsChannelID(v *string) *GuildUpdateOne {
	if v != nil {
		_u.SetNewsChannelID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GuildUpdateOne) SetUpdatedAt(v time.Time) *GuildUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GuildMutation object of the builder.
func (_u *GuildUpdateOne) Mutation() *GuildMutation {
	return _u.mutation
}

// Where appends a list predicates to the GuildUpdate builder.
func (_u *GuildUpdateOne) Where(ps ...predicate.Guild) *GuildUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GuildUpdateOne) Select(field string, fields ...string) *GuildUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Guild entity.
func (_u *GuildUpdateOne) Save(ctx context.Context) (*Guild, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GuildUpdateOne) SaveX(ctx context.Context) *Guild {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GuildUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GuildUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GuildUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := guild.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GuildUpdateOne) check() error {
	if v, ok := _u.mutation.GuildID(); ok {
		if err := guild.GuildIDValidator(v); err != nil {
			return &ValidationError{Name: "guild_id", err: fmt.Errorf(`ent: validator failed for field "Guild.guild_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NewsChannelID(); ok {
		if err := guild.NewsChannelIDValidator(v); err != nil {
			return &ValidationError{Name: "news_channel_id", err: fmt.Errorf(`ent: validator failed for field "Guild.news_channel_id": %w`, err)}
		}
	}
	return nil
}

func (_u *GuildUpdateOne) sqlSave(ctx context.Context) (_node *Guild, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(guild.Table, guild.Columns, sqlgraph.NewFieldSpec(guild.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Guild.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, guild.FieldID)
		for _, f := range fields {
			if !guild.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != guild.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GuildID(); ok {
		_spec.SetField(guild.FieldGuildID, field.TypeString, value)
	}
	if value, ok := _u.mutation.NewsChannelID(); ok {
		_spec.SetField(guild.FieldNewsChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(guild.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Guild{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{guild.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
