// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alt-bot/ent/guild"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GuildCreate is the builder for creating a Guild entity.
type GuildCreate struct {
	config
	mutation *GuildMutation
	hooks    []Hook
}

// SetGuildID sets the "guild_id" field.
func (_c *GuildCreate) SetGuildID(v string) *GuildCreate {
	_c.mutation.SetGuildID(v)
	return _c
}

// SetNewsChannelID sets the "news_channel_id" field.
func (_c *GuildCreate) SetNewsChannelID(v string) *GuildCreate {
	_c.mutation.SetNewsChannelID(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GuildCreate) SetUpdatedAt(v time.Time) *GuildCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GuildCreate) SetNillableUpdatedAt(v *time.Time) *GuildCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the GuildMutation object of the builder.
func (_c *GuildCreate) Mutation() *GuildMutation {
	return _c.mutation
}

// Save creates the Guild in the database.
func (_c *GuildCreate) Save(ctx context.Context) (*Guild, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GuildCreate) SaveX(ctx context.Context) *Guild {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GuildCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GuildCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GuildCreate) defaults() {
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := guild.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GuildCreate) check() error {
	if _, ok := _c.mutation.GuildID(); !ok {
		return &ValidationError{Name: "guild_id", err: errors.New(`ent: missing required field "Guild.guild_id"`)}
	}
	if v, ok := _c.mutation.GuildID(); ok {
		if err := guild.GuildIDValidator(v); err != nil {
			return &ValidationError{Name: "guild_id", err: fmt.Errorf(`ent: validator failed for field "Guild.guild_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NewsChannelID(); !ok {
		return &ValidationError{Name: "news_channel_id", err: errors.New(`ent: missing required field "Guild.news_channel_id"`)}
	}
	if v, ok := _c.mutation.NewsChannelID(); ok {
		if err := guild.NewsChannelIDValidator(v); err != nil {
			return &ValidationError{Name: "news_channel_id", err: fmt.Errorf(`ent: validator failed for field "Guild.news_channel_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Guild.updated_at"`)}
	}
	return nil
}

func (_c *GuildCreate) sqlSave(ctx context.Context) (*Guild, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GuildCreate) createSpec() (*Guild, *sqlgraph.CreateSpec) {
	var (
		_node = &Guild{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(guild.Table, sqlgraph.NewFieldSpec(guild.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GuildID(); ok {
		_spec.SetField(guild.FieldGuildID, field.TypeString, value)
		_node.GuildID = value
	}
	if value, ok := _c.mutation.NewsChannelID(); ok {
		_spec.SetField(guild.FieldNewsChannelID, field.TypeString, value)
		_node.NewsChannelID = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(guild.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// GuildCreateBulk is the builder for creating many Guild entities in bulk.
type GuildCreateBulk struct {
	config
	err      error
	builders []*GuildCreate
}

// Save creates the Guild entities in the database.
func (_c *GuildCreateBulk) Save(ctx context.Context) ([]*Guild, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Guild, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GuildMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GuildCreateBulk) SaveX(ctx context.Context) []*Guild {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GuildCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GuildCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
