// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alt-bot/ent/marketstate"
	"alt-bot/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MarketStateDelete is the builder for deleting a MarketState entity.
type MarketStateDelete struct {
	config
	hooks    []Hook
	mutation *MarketStateMutation
}

// Where appends a list predicates to the MarketStateDelete builder.
func (_d *MarketStateDelete) Where(ps ...predicate.MarketState) *MarketStateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MarketStateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MarketStateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MarketStateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(marketstate.Table, sqlgraph.NewFieldSpec(marketstate.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MarketStateDeleteOne is the builder for deleting a single MarketState entity.
type MarketStateDeleteOne struct {
	_d *MarketStateDelete
}

// Where appends a list predicates to the MarketStateDelete builder.
func (_d *MarketStateDeleteOne) Where(ps ...predicate.MarketState) *MarketStateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MarketStateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{marketstate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MarketStateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
