// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alt-bot/ent/marketstate"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// MarketState is the model entity for the MarketState schema.
type MarketState struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CurrentEvent holds the value of the "current_event" field.
	CurrentEvent string `json:"current_event,omitempty"`
	// EventRemainingTicks holds the value of the "event_remaining_ticks" field.
	EventRemainingTicks int `json:"event_remaining_ticks,omitempty"`
	// PityCounter holds the value of the "pity_counter" field.
	PityCounter int `json:"pity_counter,omitempty"`
	// CircuitLevel holds the value of the "circuit_level" field.
	CircuitLevel string `json:"circuit_level,omitempty"`
	// LastBreachAt holds the value of the "last_breach_at" field.
	LastBreachAt *time.Time `json:"last_breach_at,omitempty"`
	// LastPrice holds the value of the "last_price" field.
	LastPrice float64 `json:"last_price,omitempty"`
	// ReserveBalance holds the value of the "reserve_balance" field.
	ReserveBalance int64 `json:"reserve_balance,omitempty"`
	// RevenueBalance holds the value of the "revenue_balance" field.
	RevenueBalance int64 `json:"revenue_balance,omitempty"`
	// BurnedTotal holds the value of the "burned_total" field.
	BurnedTotal int64 `json:"burned_total,omitempty"`
	// DailyIssuanceDate holds the value of the "daily_issuance_date" field.
	DailyIssuanceDate string `json:"daily_issuance_date,omitempty"`
	// DailyIssued holds the value of the "daily_issued" field.
	DailyIssued int64 `json:"daily_issued,omitempty"`
	// DailyCap holds the value of the "daily_cap" field.
	DailyCap int64 `json:"daily_cap,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MarketState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case marketstate.FieldLastPrice:
			values[i] = new(sql.NullFloat64)
		case marketstate.FieldID, marketstate.FieldEventRemainingTicks, marketstate.FieldPityCounter, marketstate.FieldReserveBalance, marketstate.FieldRevenueBalance, marketstate.FieldBurnedTotal, marketstate.FieldDailyIssued, marketstate.FieldDailyCap:
			values[i] = new(sql.NullInt64)
		case marketstate.FieldCurrentEvent, marketstate.FieldCircuitLevel, marketstate.FieldDailyIssuanceDate:
			values[i] = new(sql.NullString)
		case marketstate.FieldLastBreachAt, marketstate.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MarketState fields.
func (_m *MarketState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case marketstate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case marketstate.FieldCurrentEvent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field current_event", values[i])
			} else if value.Valid {
				_m.CurrentEvent = value.String
			}
		case marketstate.FieldEventRemainingTicks:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field event_remaining_ticks", values[i])
			} else if value.Valid {
				_m.EventRemainingTicks = int(value.Int64)
			}
		case marketstate.FieldPityCounter:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pity_counter", values[i])
			} else if value.Valid {
				_m.PityCounter = int(value.Int64)
			}
		case marketstate.FieldCircuitLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field circuit_level", values[i])
			} else if value.Valid {
				_m.CircuitLevel = value.String
			}
		case marketstate.FieldLastBreachAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_breach_at", values[i])
			} else if value.Valid {
				_m.LastBreachAt = new(time.Time)
				*_m.LastBreachAt = value.Time
			}
		case marketstate.FieldLastPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field last_price", values[i])
			} else if value.Valid {
				_m.LastPrice = value.Float64
			}
		case marketstate.FieldReserveBalance:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reserve_balance", values[i])
			} else if value.Valid {
				_m.ReserveBalance = value.Int64
			}
		case marketstate.FieldRevenueBalance:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revenue_balance", values[i])
			} else if value.Valid {
				_m.RevenueBalance = value.Int64
			}
		case marketstate.FieldBurnedTotal:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field burned_total", values[i])
			} else if value.Valid {
				_m.BurnedTotal = value.Int64
			}
		case marketstate.FieldDailyIssuanceDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field daily_issuance_date", values[i])
			} else if value.Valid {
				_m.DailyIssuanceDate = value.String
			}
		case marketstate.FieldDailyIssued:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_issued", values[i])
			} else if value.Valid {
				_m.DailyIssued = value.Int64
			}
		case marketstate.FieldDailyCap:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field daily_cap", values[i])
			} else if value.Valid {
				_m.DailyCap = value.Int64
			}
		case marketstate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MarketState.
// This includes values selected through modifiers, order, etc.
func (_m *MarketState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MarketState.
// Note that you need to call MarketState.Unwrap() before calling this method if this MarketState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MarketState) Update() *MarketStateUpdateOne {
	return NewMarketStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MarketState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MarketState) Unwrap() *MarketState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MarketState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MarketState) String() string {
	var builder strings.Builder
	builder.WriteString("MarketState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("current_event=")
	builder.WriteString(_m.CurrentEvent)
	builder.WriteString(", ")
	builder.WriteString("event_remaining_ticks=")
	builder.WriteString(fmt.Sprintf("%v", _m.EventRemainingTicks))
	builder.WriteString(", ")
	builder.WriteString("pity_counter=")
	builder.WriteString(fmt.Sprintf("%v", _m.PityCounter))
	builder.WriteString(", ")
	builder.WriteString("circuit_level=")
	builder.WriteString(_m.CircuitLevel)
	builder.WriteString(", ")
	if v := _m.LastBreachAt; v != nil {
		builder.WriteString("last_breach_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastPrice))
	builder.WriteString(", ")
	builder.WriteString("reserve_balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReserveBalance))
	builder.WriteString(", ")
	builder.WriteString("revenue_balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.RevenueBalance))
	builder.WriteString(", ")
	builder.WriteString("burned_total=")
	builder.WriteString(fmt.Sprintf("%v", _m.BurnedTotal))
	builder.WriteString(", ")
	builder.WriteString("daily_issuance_date=")
	builder.WriteString(_m.DailyIssuanceDate)
	builder.WriteString(", ")
	builder.WriteString("daily_issued=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyIssued))
	builder.WriteString(", ")
	builder.WriteString("daily_cap=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyCap))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MarketStates is a parsable slice of MarketState.
type MarketStates []*MarketState
