// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alt-bot/ent/predicate"
	"alt-bot/ent/pricehistory"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PriceHistoryUpdate is the builder for updating PriceHistory entities.
type PriceHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *PriceHistoryMutation
}

// Where appends a list predicates to the PriceHistoryUpdate builder.
func (_u *PriceHistoryUpdate) Where(ps ...predicate.PriceHistory) *PriceHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPrice sets the "price" field.
func (_u *PriceHistoryUpdate) SetPrice(v float64) *PriceHistoryUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PriceHistoryUpdate) SetNillablePrice(v *float64) *PriceHistoryUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *PriceHistoryUpdate) AddPrice(v float64) *PriceHistoryUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PriceHistoryUpdate) SetCreatedAt(v time.Time) *PriceHistoryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PriceHistoryUpdate) SetNillableCreatedAt(v *time.Time) *PriceHistoryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the PriceHistoryMutation object of the builder.
func (_u *PriceHistoryUpdate) Mutation() *PriceHistoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PriceHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PriceHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PriceHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PriceHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PriceHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(pricehistory.Table, pricehistory.Columns, sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(pricehistory.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(pricehistory.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(pricehistory.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PriceHistoryUpdateOne is the builder for updating a single PriceHistory entity.
type PriceHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PriceHistoryMutation
}

// SetPrice sets the "price" field.
func (_u *PriceHistoryUpdateOne) SetPrice(v float64) *PriceHistoryUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PriceHistoryUpdateOne) SetNillablePrice(v *float64) *PriceHistoryUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *PriceHistoryUpdateOne) AddPrice(v float64) *PriceHistoryUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *PriceHistoryUpdateOne) SetCreatedAt(v time.Time) *PriceHistoryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *PriceHistoryUpdateOne) SetNillableCreatedAt(v *time.Time) *PriceHistoryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the PriceHistoryMutation object of the builder.
func (_u *PriceHistoryUpdateOne) Mutation() *PriceHistoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the PriceHistoryUpdate builder.
func (_u *PriceHistoryUpdateOne) Where(ps ...predicate.PriceHistory) *PriceHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PriceHistoryUpdateOne) Select(field string, fields ...string) *PriceHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PriceHistory entity.
func (_u *PriceHistoryUpdateOne) Save(ctx context.Context) (*PriceHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PriceHistoryUpdateOne) SaveX(ctx context.Context) *PriceHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PriceHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PriceHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PriceHistoryUpdateOne) sqlSave(ctx context.Context) (_node *PriceHistory, err error) {
	_spec := sqlgraph.NewUpdateSpec(pricehistory.Table, pricehistory.Columns, sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PriceHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricehistory.FieldID)
		for _, f := range fields {
			if !pricehistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pricehistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(pricehistory.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(pricehistory.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(pricehistory.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &PriceHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
