// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alt-bot/ent/rolepanel"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// RolePanel is the model entity for the RolePanel schema.
type RolePanel struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// GuildID holds the value of the "guild_id" field.
	GuildID string `json:"guild_id,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID string `json:"channel_id,omitempty"`
	// MessageID holds the value of the "message_id" field.
	MessageID string `json:"message_id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// RoleIds holds the value of the "role_ids" field.
	RoleIds string `json:"role_ids,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RolePanel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rolepanel.FieldID:
			values[i] = new(sql.NullInt64)
		case rolepanel.FieldGuildID, rolepanel.FieldChannelID, rolepanel.FieldMessageID, rolepanel.FieldTitle, rolepanel.FieldDescription, rolepanel.FieldRoleIds:
			values[i] = new(sql.NullString)
		case rolepanel.FieldCreatedAt, rolepanel.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RolePanel fields.
func (_m *RolePanel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rolepanel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case rolepanel.FieldGuildID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field guild_id", values[i])
			} else if value.Valid {
				_m.GuildID = value.String
			}
		case rolepanel.FieldChannelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = value.String
			}
		case rolepanel.FieldMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value.Valid {
				_m.MessageID = value.String
			}
		case rolepanel.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case rolepanel.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case rolepanel.FieldRoleIds:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role_ids", values[i])
			} else if value.Valid {
				_m.RoleIds = value.String
			}
		case rolepanel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case rolepanel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RolePanel.
// This includes values selected through modifiers, order, etc.
func (_m *RolePanel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RolePanel.
// Note that you need to call RolePanel.Unwrap() before calling this method if this RolePanel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RolePanel) Update() *RolePanelUpdateOne {
	return NewRolePanelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RolePanel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RolePanel) Unwrap() *RolePanel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RolePanel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RolePanel) String() string {
	var builder strings.Builder
	builder.WriteString("RolePanel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("guild_id=")
	builder.WriteString(_m.GuildID)
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(_m.ChannelID)
	builder.WriteString(", ")
	builder.WriteString("message_id=")
	builder.WriteString(_m.MessageID)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("role_ids=")
	builder.WriteString(_m.RoleIds)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RolePanels is a parsable slice of RolePanel.
type RolePanels []*RolePanel
