// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alt-bot/ent/rolepanel"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RolePanelCreate is the builder for creating a RolePanel entity.
type RolePanelCreate struct {
	config
	mutation *RolePanelMutation
	hooks    []Hook
}

// SetGuildID sets the "guild_id" field.
func (_c *RolePanelCreate) SetGuildID(v string) *RolePanelCreate {
	_c.mutation.SetGuildID(v)
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *RolePanelCreate) SetChannelID(v string) *RolePanelCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *RolePanelCreate) SetMessageID(v string) *RolePanelCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *RolePanelCreate) SetTitle(v string) *RolePanelCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *RolePanelCreate) SetDescription(v string) *RolePanelCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RolePanelCreate) SetNillableDescription(v *string) *RolePanelCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetRoleIds sets the "role_ids" field.
func (_c *RolePanelCreate) SetRoleIds(v string) *RolePanelCreate {
	_c.mutation.SetRoleIds(v)
	return _c
}

// SetNillableRoleIds sets the "role_ids" field if the given value is not nil.
func (_c *RolePanelCreate) SetNillableRoleIds(v *string) *RolePanelCreate {
	if v != nil {
		_c.SetRoleIds(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RolePanelCreate) SetCreatedAt(v time.Time) *RolePanelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RolePanelCreate) SetNillableCreatedAt(v *time.Time) *RolePanelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RolePanelCreate) SetUpdatedAt(v time.Time) *RolePanelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RolePanelCreate) SetNillableUpdatedAt(v *time.Time) *RolePanelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the RolePanelMutation object of the builder.
func (_c *RolePanelCreate) Mutation() *RolePanelMutation {
	return _c.mutation
}

// Save creates the RolePanel in the database.
func (_c *RolePanelCreate) Save(ctx context.Context) (*RolePanel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RolePanelCreate) SaveX(ctx context.Context) *RolePanel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RolePanelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RolePanelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RolePanelCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := rolepanel.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.RoleIds(); !ok {
		v := rolepanel.DefaultRoleIds
		_c.mutation.SetRoleIds(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rolepanel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rolepanel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RolePanelCreate) check() error {
	if _, ok := _c.mutation.GuildID(); !ok {
		return &ValidationError{Name: "guild_id", err: errors.New(`ent: missing required field "RolePanel.guild_id"`)}
	}
	if v, ok := _c.mutation.GuildID(); ok {
		if err := rolepanel.GuildIDValidator(v); err != nil {
			return &ValidationError{Name: "guild_id", err: fmt.Errorf(`ent: validator failed for field "RolePanel.guild_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "RolePanel.channel_id"`)}
	}
	if v, ok := _c.mutation.ChannelID(); ok {
		if err := rolepanel.ChannelIDValidator(v); err != nil {
			return &ValidationError{Name: "channel_id", err: fmt.Errorf(`ent: validator failed for field "RolePanel.channel_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "RolePanel.message_id"`)}
	}
	if v, ok := _c.mutation.MessageID(); ok {
		if err := rolepanel.MessageIDValidator(v); err != nil {
			return &ValidationError{Name: "message_id", err: fmt.Errorf(`ent: validator failed for field "RolePanel.message_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "RolePanel.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := rolepanel.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "RolePanel.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "RolePanel.description"`)}
	}
	if _, ok := _c.mutation.RoleIds(); !ok {
		return &ValidationError{Name: "role_ids", err: errors.New(`ent: missing required field "RolePanel.role_ids"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RolePanel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RolePanel.updated_at"`)}
	}
	return nil
}

func (_c *RolePanelCreate) sqlSave(ctx context.Context) (*RolePanel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RolePanelCreate) createSpec() (*RolePanel, *sqlgraph.CreateSpec) {
	var (
		_node = &RolePanel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rolepanel.Table, sqlgraph.NewFieldSpec(rolepanel.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.GuildID(); ok {
		_spec.SetField(rolepanel.FieldGuildID, field.TypeString, value)
		_node.GuildID = value
	}
	if value, ok := _c.mutation.ChannelID(); ok {
		_spec.SetField(rolepanel.FieldChannelID, field.TypeString, value)
		_node.ChannelID = value
	}
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(rolepanel.FieldMessageID, field.TypeString, value)
		_node.MessageID = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(rolepanel.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(rolepanel.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.RoleIds(); ok {
		_spec.SetField(rolepanel.FieldRoleIds, field.TypeString, value)
		_node.RoleIds = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rolepanel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rolepanel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// RolePanelCreateBulk is the builder for creating many RolePanel entities in bulk.
type RolePanelCreateBulk struct {
	config
	err      error
	builders []*RolePanelCreate
}

// Save creates the RolePanel entities in the database.
func (_c *RolePanelCreateBulk) Save(ctx context.Context) ([]*RolePanel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RolePanel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RolePanelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RolePanelCreateBulk) SaveX(ctx context.Context) []*RolePanel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RolePanelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RolePanelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
