// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alt-bot/ent/predicate"
	"alt-bot/ent/rolepanel"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RolePanelUpdate is the builder for updating RolePanel entities.
type RolePanelUpdate struct {
	config
	hooks    []Hook
	mutation *RolePanelMutation
}

// Where appends a list predicates to the RolePanelUpdate builder.
func (_u *RolePanelUpdate) Where(ps ...predicate.RolePanel) *RolePanelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGuildID sets the "guild_id" field.
func (_u *RolePanelUpdate) SetGuildID(v string) *RolePanelUpdate {
	_u.mutation.SetGuildID(v)
	return _u
}

// SetNillableGuildID sets the "guild_id" field if the given value is not nil.
func (_u *RolePanelUpdate) SetNillableGuildID(v *string) *RolePanelUpdate {
	if v != nil {
		_u.SetGuildID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *RolePanelUpdate) SetChannelID(v string) *RolePanelUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *RolePanelUpdate) SetNillableChannelID(v *string) *RolePanelUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *RolePanelUpdate) SetMessageID(v string) *RolePanelUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *RolePanelUpdate) SetNillableMessageID(v *string) *RolePanelUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *RolePanelUpdate) SetTitle(v string) *RolePanelUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *RolePanelUpdate) SetNillableTitle(v *string) *RolePanelUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RolePanelUpdate) SetDescription(v string) *RolePanelUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RolePanelUpdate) SetNillableDescription(v *string) *RolePanelUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetRoleIds sets the "role_ids" field.
func (_u *RolePanelUpdate) SetRoleIds(v string) *RolePanelUpdate {
	_u.mutation.SetRoleIds(v)
	return _u
}

// SetNillableRoleIds sets the "role_ids" field if the given value is not nil.
func (_u *RolePanelUpdate) SetNillableRoleIds(v *string) *RolePanelUpdate {
	if v != nil {
		_u.SetRoleIds(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RolePanelUpdate) SetCreatedAt(v time.Time) *RolePanelUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RolePanelUpdate) SetNillableCreatedAt(v *time.Time) *RolePanelUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RolePanelUpdate) SetUpdatedAt(v time.Time) *RolePanelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RolePanelMutation object of the builder.
func (_u *RolePanelUpdate) Mutation() *RolePanelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RolePanelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RolePanelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RolePanelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RolePanelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RolePanelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rolepanel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RolePanelUpdate) check() error {
	if v, ok := _u.mutation.GuildID(); ok {
		if err := rolepanel.GuildIDValidator(v); err != nil {
			return &ValidationError{Name: "guild_id", err: fmt.Errorf(`ent: validator failed for field "RolePanel.guild_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChannelID(); ok {
		if err := rolepanel.ChannelIDValidator(v); err != nil {
			return &ValidationError{Name: "channel_id", err: fmt.Errorf(`ent: validator failed for field "RolePanel.channel_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MessageID(); ok {
		if err := rolepanel.MessageIDValidator(v); err != nil {
			return &ValidationError{Name: "message_id", err: fmt.Errorf(`ent: validator failed for field "RolePanel.message_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := rolepanel.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "RolePanel.title": %w`, err)}
		}
	}
	return nil
}

func (_u *RolePanelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rolepanel.Table, rolepanel.Columns, sqlgraph.NewFieldSpec(rolepanel.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GuildID(); ok {
		_spec.SetField(rolepanel.FieldGuildID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(rolepanel.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(rolepanel.FieldMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(rolepanel.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rolepanel.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoleIds(); ok {
		_spec.SetField(rolepanel.FieldRoleIds, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(rolepanel.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rolepanel.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rolepanel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RolePanelUpdateOne is the builder for updating a single RolePanel entity.
type RolePanelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RolePanelMutation
}

// SetGuildID sets the "guild_id" field.
func (_u *RolePanelUpdateOne) SetGuildID(v string) *RolePanelUpdateOne {
	_u.mutation.SetGuildID(v)
	return _u
}

// SetNillableGuildID sets the "guild_id" field if the given value is not nil.
func (_u *RolePanelUpdateOne) SetNillableGuildID(v *string) *RolePanelUpdateOne {
	if v != nil {
		_u.SetGuildID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *RolePanelUpdateOne) SetChannelID(v string) *RolePanelUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *RolePanelUpdateOne) SetNillableChannelID(v *string) *RolePanelUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *RolePanelUpdateOne) SetMessageID(v string) *RolePanelUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *RolePanelUpdateOne) SetNillableMessageID(v *string) *RolePanelUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *RolePanelUpdateOne) SetTitle(v string) *RolePanelUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *RolePanelUpdateOne) SetNillableTitle(v *string) *RolePanelUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RolePanelUpdateOne) SetDescription(v string) *RolePanelUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RolePanelUpdateOne) SetNillableDescription(v *string) *RolePanelUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetRoleIds sets the "role_ids" field.
func (_u *RolePanelUpdateOne) SetRoleIds(v string) *RolePanelUpdateOne {
	_u.mutation.SetRoleIds(v)
	return _u
}

// SetNillableRoleIds sets the "role_ids" field if the given value is not nil.
func (_u *RolePanelUpdateOne) SetNillableRoleIds(v *string) *RolePanelUpdateOne {
	if v != nil {
		_u.SetRoleIds(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RolePanelUpdateOne) SetCreatedAt(v time.Time) *RolePanelUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RolePanelUpdateOne) SetNillableCreatedAt(v *time.Time) *RolePanelUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RolePanelUpdateOne) SetUpdatedAt(v time.Time) *RolePanelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RolePanelMutation object of the builder.
func (_u *RolePanelUpdateOne) Mutation() *RolePanelMutation {
	return _u.mutation
}

// Where appends a list predicates to the RolePanelUpdate builder.
func (_u *RolePanelUpdateOne) Where(ps ...predicate.RolePanel) *RolePanelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RolePanelUpdateOne) Select(field string, fields ...string) *RolePanelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RolePanel entity.
func (_u *RolePanelUpdateOne) Save(ctx context.Context) (*RolePanel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RolePanelUpdateOne) SaveX(ctx context.Context) *RolePanel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RolePanelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RolePanelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RolePanelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rolepanel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RolePanelUpdateOne) check() error {
	if v, ok := _u.mutation.GuildID(); ok {
		if err := rolepanel.GuildIDValidator(v); err != nil {
			return &ValidationError{Name: "guild_id", err: fmt.Errorf(`ent: validator failed for field "RolePanel.guild_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChannelID(); ok {
		if err := rolepanel.ChannelIDValidator(v); err != nil {
			return &ValidationError{Name: "channel_id", err: fmt.Errorf(`ent: validator failed for field "RolePanel.channel_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MessageID(); ok {
		if err := rolepanel.MessageIDValidator(v); err != nil {
			return &ValidationError{Name: "message_id", err: fmt.Errorf(`ent: validator failed for field "RolePanel.message_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := rolepanel.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "RolePanel.title": %w`, err)}
		}
	}
	return nil
}

func (_u *RolePanelUpdateOne) sqlSave(ctx context.Context) (_node *RolePanel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rolepanel.Table, rolepanel.Columns, sqlgraph.NewFieldSpec(rolepanel.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RolePanel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rolepanel.FieldID)
		for _, f := range fields {
			if !rolepanel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rolepanel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GuildID(); ok {
		_spec.SetField(rolepanel.FieldGuildID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(rolepanel.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(rolepanel.FieldMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(rolepanel.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rolepanel.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.RoleIds(); ok {
		_spec.SetField(rolepanel.FieldRoleIds, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(rolepanel.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rolepanel.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &RolePanel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rolepanel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
