// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alt-bot/ent/guild"
	"alt-bot/ent/marketstate"
	"alt-bot/ent/pricehistory"
	"alt-bot/ent/schema"
	"alt-bot/ent/transactionlog"
	"alt-bot/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	guildFields := schema.Guild{}.Fields()
	_ = guildFields
	// guildDescGuildID is the schema descriptor for guild_id field.
	guildDescGuildID := guildFields[0].Descriptor()
	// guild.GuildIDValidator is a validator for the "guild_id" field. It is called by the builders before save.
	guild.GuildIDValidator = guildDescGuildID.Validators[0].(func(string) error)
	// guildDescNewsChannelID is the schema descriptor for news_channel_id field.
	guildDescNewsChannelID := guildFields[1].Descriptor()
	// guild.NewsChannelIDValidator is a validator for the "news_channel_id" field. It is called by the builders before save.
	guild.NewsChannelIDValidator = guildDescNewsChannelID.Validators[0].(func(string) error)
	// guildDescUpdatedAt is the schema descriptor for updated_at field.
	guildDescUpdatedAt := guildFields[2].Descriptor()
	// guild.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	guild.DefaultUpdatedAt = guildDescUpdatedAt.Default.(func() time.Time)
	// guild.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	guild.UpdateDefaultUpdatedAt = guildDescUpdatedAt.UpdateDefault.(func() time.Time)
	marketstateFields := schema.MarketState{}.Fields()
	_ = marketstateFields
	// marketstateDescCurrentEvent is the schema descriptor for current_event field.
	marketstateDescCurrentEvent := marketstateFields[1].Descriptor()
	// marketstate.DefaultCurrentEvent holds the default value on creation for the current_event field.
	marketstate.DefaultCurrentEvent = marketstateDescCurrentEvent.Default.(string)
	// marketstateDescEventRemainingTicks is the schema descriptor for event_remaining_ticks field.
	marketstateDescEventRemainingTicks := marketstateFields[2].Descriptor()
	// marketstate.DefaultEventRemainingTicks holds the default value on creation for the event_remaining_ticks field.
	marketstate.DefaultEventRemainingTicks = marketstateDescEventRemainingTicks.Default.(int)
	// marketstateDescPityCounter is the schema descriptor for pity_counter field.
	marketstateDescPityCounter := marketstateFields[3].Descriptor()
	// marketstate.DefaultPityCounter holds the default value on creation for the pity_counter field.
	marketstate.DefaultPityCounter = marketstateDescPityCounter.Default.(int)
	// marketstateDescCircuitLevel is the schema descriptor for circuit_level field.
	marketstateDescCircuitLevel := marketstateFields[4].Descriptor()
	// marketstate.DefaultCircuitLevel holds the default value on creation for the circuit_level field.
	marketstate.DefaultCircuitLevel = marketstateDescCircuitLevel.Default.(string)
	// marketstateDescLastPrice is the schema descriptor for last_price field.
	marketstateDescLastPrice := marketstateFields[6].Descriptor()
	// marketstate.DefaultLastPrice holds the default value on creation for the last_price field.
	marketstate.DefaultLastPrice = marketstateDescLastPrice.Default.(float64)
	// marketstateDescReserveBalance is the schema descriptor for reserve_balance field.
	marketstateDescReserveBalance := marketstateFields[7].Descriptor()
	// marketstate.DefaultReserveBalance holds the default value on creation for the reserve_balance field.
	marketstate.DefaultReserveBalance = marketstateDescReserveBalance.Default.(int64)
	// marketstateDescRevenueBalance is the schema descriptor for revenue_balance field.
	marketstateDescRevenueBalance := marketstateFields[8].Descriptor()
	// marketstate.DefaultRevenueBalance holds the default value on creation for the revenue_balance field.
	marketstate.DefaultRevenueBalance = marketstateDescRevenueBalance.Default.(int64)
	// marketstateDescBurnedTotal is the schema descriptor for burned_total field.
	marketstateDescBurnedTotal := marketstateFields[9].Descriptor()
	// marketstate.DefaultBurnedTotal holds the default value on creation for the burned_total field.
	marketstate.DefaultBurnedTotal = marketstateDescBurnedTotal.Default.(int64)
	// marketstateDescDailyIssuanceDate is the schema descriptor for daily_issuance_date field.
	marketstateDescDailyIssuanceDate := marketstateFields[10].Descriptor()
	// marketstate.DefaultDailyIssuanceDate holds the default value on creation for the daily_issuance_date field.
	marketstate.DefaultDailyIssuanceDate = marketstateDescDailyIssuanceDate.Default.(string)
	// marketstateDescDailyIssued is the schema descriptor for daily_issued field.
	marketstateDescDailyIssued := marketstateFields[11].Descriptor()
	// marketstate.DefaultDailyIssued holds the default value on creation for the daily_issued field.
	marketstate.DefaultDailyIssued = marketstateDescDailyIssued.Default.(int64)
	// marketstateDescDailyCap is the schema descriptor for daily_cap field.
	marketstateDescDailyCap := marketstateFields[12].Descriptor()
	// marketstate.DefaultDailyCap holds the default value on creation for the daily_cap field.
	marketstate.DefaultDailyCap = marketstateDescDailyCap.Default.(int64)
	// marketstateDescUpdatedAt is the schema descriptor for updated_at field.
	marketstateDescUpdatedAt := marketstateFields[13].Descriptor()
	// marketstate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	marketstate.DefaultUpdatedAt = marketstateDescUpdatedAt.Default.(func() time.Time)
	// marketstate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	marketstate.UpdateDefaultUpdatedAt = marketstateDescUpdatedAt.UpdateDefault.(func() time.Time)
	pricehistoryFields := schema.PriceHistory{}.Fields()
	_ = pricehistoryFields
	// pricehistoryDescCreatedAt is the schema descriptor for created_at field.
	pricehistoryDescCreatedAt := pricehistoryFields[1].Descriptor()
	// pricehistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	pricehistory.DefaultCreatedAt = pricehistoryDescCreatedAt.Default.(func() time.Time)
	transactionlogFields := schema.TransactionLog{}.Fields()
	_ = transactionlogFields
	// transactionlogDescTxID is the schema descriptor for tx_id field.
	transactionlogDescTxID := transactionlogFields[0].Descriptor()
	// transactionlog.TxIDValidator is a validator for the "tx_id" field. It is called by the builders before save.
	transactionlog.TxIDValidator = transactionlogDescTxID.Validators[0].(func(string) error)
	// transactionlogDescUserDiscordID is the schema descriptor for user_discord_id field.
	transactionlogDescUserDiscordID := transactionlogFields[1].Descriptor()
	// transactionlog.UserDiscordIDValidator is a validator for the "user_discord_id" field. It is called by the builders before save.
	transactionlog.UserDiscordIDValidator = transactionlogDescUserDiscordID.Validators[0].(func(string) error)
	// transactionlogDescKind is the schema descriptor for kind field.
	transactionlogDescKind := transactionlogFields[2].Descriptor()
	// transactionlog.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	transactionlog.KindValidator = transactionlogDescKind.Validators[0].(func(string) error)
	// transactionlogDescYenDelta is the schema descriptor for yen_delta field.
	transactionlogDescYenDelta := transactionlogFields[3].Descriptor()
	// transactionlog.DefaultYenDelta holds the default value on creation for the yen_delta field.
	transactionlog.DefaultYenDelta = transactionlogDescYenDelta.Default.(int64)
	// transactionlogDescAltDelta is the schema descriptor for alt_delta field.
	transactionlogDescAltDelta := transactionlogFields[4].Descriptor()
	// transactionlog.DefaultAltDelta holds the default value on creation for the alt_delta field.
	transactionlog.DefaultAltDelta = transactionlogDescAltDelta.Default.(int64)
	// transactionlogDescXpDelta is the schema descriptor for xp_delta field.
	transactionlogDescXpDelta := transactionlogFields[5].Descriptor()
	// transactionlog.DefaultXpDelta holds the default value on creation for the xp_delta field.
	transactionlog.DefaultXpDelta = transactionlogDescXpDelta.Default.(int64)
	// transactionlogDescAmount is the schema descriptor for amount field.
	transactionlogDescAmount := transactionlogFields[6].Descriptor()
	// transactionlog.DefaultAmount holds the default value on creation for the amount field.
	transactionlog.DefaultAmount = transactionlogDescAmount.Default.(int64)
	// transactionlogDescSettledPrice is the schema descriptor for settled_price field.
	transactionlogDescSettledPrice := transactionlogFields[7].Descriptor()
	// transactionlog.DefaultSettledPrice holds the default value on creation for the settled_price field.
	transactionlog.DefaultSettledPrice = transactionlogDescSettledPrice.Default.(float64)
	// transactionlogDescPriceAfter is the schema descriptor for price_after field.
	transactionlogDescPriceAfter := transactionlogFields[8].Descriptor()
	// transactionlog.DefaultPriceAfter holds the default value on creation for the price_after field.
	transactionlog.DefaultPriceAfter = transactionlogDescPriceAfter.Default.(float64)
	// transactionlogDescBalanceAfter is the schema descriptor for balance_after field.
	transactionlogDescBalanceAfter := transactionlogFields[9].Descriptor()
	// transactionlog.DefaultBalanceAfter holds the default value on creation for the balance_after field.
	transactionlog.DefaultBalanceAfter = transactionlogDescBalanceAfter.Default.(int64)
	// transactionlogDescCryptoAfter is the schema descriptor for crypto_after field.
	transactionlogDescCryptoAfter := transactionlogFields[10].Descriptor()
	// transactionlog.DefaultCryptoAfter holds the default value on creation for the crypto_after field.
	transactionlog.DefaultCryptoAfter = transactionlogDescCryptoAfter.Default.(int64)
	// transactionlogDescPrevHash is the schema descriptor for prev_hash field.
	transactionlogDescPrevHash := transactionlogFields[11].Descriptor()
	// transactionlog.DefaultPrevHash holds the default value on creation for the prev_hash field.
	transactionlog.DefaultPrevHash = transactionlogDescPrevHash.Default.(string)
	// transactionlogDescHash is the schema descriptor for hash field.
	transactionlogDescHash := transactionlogFields[12].Descriptor()
	// transactionlog.HashValidator is a validator for the "hash" field. It is called by the builders before save.
	transactionlog.HashValidator = transactionlogDescHash.Validators[0].(func(string) error)
	// transactionlogDescSignature is the schema descriptor for signature field.
	transactionlogDescSignature := transactionlogFields[13].Descriptor()
	// transactionlog.SignatureValidator is a validator for the "signature" field. It is called by the builders before save.
	transactionlog.SignatureValidator = transactionlogDescSignature.Validators[0].(func(string) error)
	// transactionlogDescPublicKey is the schema descriptor for public_key field.
	transactionlogDescPublicKey := transactionlogFields[14].Descriptor()
	// transactionlog.PublicKeyValidator is a validator for the "public_key" field. It is called by the builders before save.
	transactionlog.PublicKeyValidator = transactionlogDescPublicKey.Validators[0].(func(string) error)
	// transactionlogDescCreatedAt is the schema descriptor for created_at field.
	transactionlogDescCreatedAt := transactionlogFields[15].Descriptor()
	// transactionlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	transactionlog.DefaultCreatedAt = transactionlogDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescDiscordID is the schema descriptor for discord_id field.
	userDescDiscordID := userFields[0].Descriptor()
	// user.DiscordIDValidator is a validator for the "discord_id" field. It is called by the builders before save.
	user.DiscordIDValidator = userDescDiscordID.Validators[0].(func(string) error)
	// userDescBalance is the schema descriptor for balance field.
	userDescBalance := userFields[1].Descriptor()
	// user.DefaultBalance holds the default value on creation for the balance field.
	user.DefaultBalance = userDescBalance.Default.(int64)
	// userDescCryptoBalance is the schema descriptor for crypto_balance field.
	userDescCryptoBalance := userFields[2].Descriptor()
	// user.DefaultCryptoBalance holds the default value on creation for the crypto_balance field.
	user.DefaultCryptoBalance = userDescCryptoBalance.Default.(int64)
	// userDescXp is the schema descriptor for xp field.
	userDescXp := userFields[3].Descriptor()
	// user.DefaultXp holds the default value on creation for the xp field.
	user.DefaultXp = userDescXp.Default.(int64)
	// userDescWorkEndAt is the schema descriptor for work_end_at field.
	userDescWorkEndAt := userFields[4].Descriptor()
	// user.DefaultWorkEndAt holds the default value on creation for the work_end_at field.
	user.DefaultWorkEndAt = userDescWorkEndAt.Default.(time.Time)
}
