// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alt-bot/ent/predicate"
	"alt-bot/ent/stickymessage"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StickyMessageUpdate is the builder for updating StickyMessage entities.
type StickyMessageUpdate struct {
	config
	hooks    []Hook
	mutation *StickyMessageMutation
}

// Where appends a list predicates to the StickyMessageUpdate builder.
func (_u *StickyMessageUpdate) Where(ps ...predicate.StickyMessage) *StickyMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGuildID sets the "guild_id" field.
func (_u *StickyMessageUpdate) SetGuildID(v string) *StickyMessageUpdate {
	_u.mutation.SetGuildID(v)
	return _u
}

// SetNillableGuildID sets the "guild_id" field if the given value is not nil.
func (_u *StickyMessageUpdate) SetNillableGuildID(v *string) *StickyMessageUpdate {
	if v != nil {
		_u.SetGuildID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *StickyMessageUpdate) SetChannelID(v string) *StickyMessageUpdate {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *StickyMessageUpdate) SetNillableChannelID(v *string) *StickyMessageUpdate {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *StickyMessageUpdate) SetContent(v string) *StickyMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *StickyMessageUpdate) SetNillableContent(v *string) *StickyMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetLastMessageID sets the "last_message_id" field.
func (_u *StickyMessageUpdate) SetLastMessageID(v string) *StickyMessageUpdate {
	_u.mutation.SetLastMessageID(v)
	return _u
}

// SetNillableLastMessageID sets the "last_message_id" field if the given value is not nil.
func (_u *StickyMessageUpdate) SetNillableLastMessageID(v *string) *StickyMessageUpdate {
	if v != nil {
		_u.SetLastMessageID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *StickyMessageUpdate) SetEnabled(v bool) *StickyMessageUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *StickyMessageUpdate) SetNillableEnabled(v *bool) *StickyMessageUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *StickyMessageUpdate) SetCreatedBy(v string) *StickyMessageUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *StickyMessageUpdate) SetNillableCreatedBy(v *string) *StickyMessageUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *StickyMessageUpdate) SetCreatedAt(v time.Time) *StickyMessageUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *StickyMessageUpdate) SetNillableCreatedAt(v *time.Time) *StickyMessageUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StickyMessageUpdate) SetUpdatedAt(v time.Time) *StickyMessageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the StickyMessageMutation object of the builder.
func (_u *StickyMessageUpdate) Mutation() *StickyMessageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StickyMessageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StickyMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StickyMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StickyMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StickyMessageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := stickymessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StickyMessageUpdate) check() error {
	if v, ok := _u.mutation.GuildID(); ok {
		if err := stickymessage.GuildIDValidator(v); err != nil {
			return &ValidationError{Name: "guild_id", err: fmt.Errorf(`ent: validator failed for field "StickyMessage.guild_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChannelID(); ok {
		if err := stickymessage.ChannelIDValidator(v); err != nil {
			return &ValidationError{Name: "channel_id", err: fmt.Errorf(`ent: validator failed for field "StickyMessage.channel_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := stickymessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "StickyMessage.content": %w`, err)}
		}
	}
	return nil
}

func (_u *StickyMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stickymessage.Table, stickymessage.Columns, sqlgraph.NewFieldSpec(stickymessage.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GuildID(); ok {
		_spec.SetField(stickymessage.FieldGuildID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(stickymessage.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(stickymessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageID(); ok {
		_spec.SetField(stickymessage.FieldLastMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(stickymessage.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(stickymessage.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(stickymessage.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(stickymessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stickymessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StickyMessageUpdateOne is the builder for updating a single StickyMessage entity.
type StickyMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StickyMessageMutation
}

// SetGuildID sets the "guild_id" field.
func (_u *StickyMessageUpdateOne) SetGuildID(v string) *StickyMessageUpdateOne {
	_u.mutation.SetGuildID(v)
	return _u
}

// SetNillableGuildID sets the "guild_id" field if the given value is not nil.
func (_u *StickyMessageUpdateOne) SetNillableGuildID(v *string) *StickyMessageUpdateOne {
	if v != nil {
		_u.SetGuildID(*v)
	}
	return _u
}

// SetChannelID sets the "channel_id" field.
func (_u *StickyMessageUpdateOne) SetChannelID(v string) *StickyMessageUpdateOne {
	_u.mutation.SetChannelID(v)
	return _u
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (_u *StickyMessageUpdateOne) SetNillableChannelID(v *string) *StickyMessageUpdateOne {
	if v != nil {
		_u.SetChannelID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *StickyMessageUpdateOne) SetContent(v string) *StickyMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *StickyMessageUpdateOne) SetNillableContent(v *string) *StickyMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetLastMessageID sets the "last_message_id" field.
func (_u *StickyMessageUpdateOne) SetLastMessageID(v string) *StickyMessageUpdateOne {
	_u.mutation.SetLastMessageID(v)
	return _u
}

// SetNillableLastMessageID sets the "last_message_id" field if the given value is not nil.
func (_u *StickyMessageUpdateOne) SetNillableLastMessageID(v *string) *StickyMessageUpdateOne {
	if v != nil {
		_u.SetLastMessageID(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *StickyMessageUpdateOne) SetEnabled(v bool) *StickyMessageUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *StickyMessageUpdateOne) SetNillableEnabled(v *bool) *StickyMessageUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *StickyMessageUpdateOne) SetCreatedBy(v string) *StickyMessageUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *StickyMessageUpdateOne) SetNillableCreatedBy(v *string) *StickyMessageUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *StickyMessageUpdateOne) SetCreatedAt(v time.Time) *StickyMessageUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *StickyMessageUpdateOne) SetNillableCreatedAt(v *time.Time) *StickyMessageUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StickyMessageUpdateOne) SetUpdatedAt(v time.Time) *StickyMessageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the StickyMessageMutation object of the builder.
func (_u *StickyMessageUpdateOne) Mutation() *StickyMessageMutation {
	return _u.mutation
}

// Where appends a list predicates to the StickyMessageUpdate builder.
func (_u *StickyMessageUpdateOne) Where(ps ...predicate.StickyMessage) *StickyMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StickyMessageUpdateOne) Select(field string, fields ...string) *StickyMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StickyMessage entity.
func (_u *StickyMessageUpdateOne) Save(ctx context.Context) (*StickyMessage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StickyMessageUpdateOne) SaveX(ctx context.Context) *StickyMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StickyMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StickyMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StickyMessageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := stickymessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StickyMessageUpdateOne) check() error {
	if v, ok := _u.mutation.GuildID(); ok {
		if err := stickymessage.GuildIDValidator(v); err != nil {
			return &ValidationError{Name: "guild_id", err: fmt.Errorf(`ent: validator failed for field "StickyMessage.guild_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ChannelID(); ok {
		if err := stickymessage.ChannelIDValidator(v); err != nil {
			return &ValidationError{Name: "channel_id", err: fmt.Errorf(`ent: validator failed for field "StickyMessage.channel_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := stickymessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "StickyMessage.content": %w`, err)}
		}
	}
	return nil
}

func (_u *StickyMessageUpdateOne) sqlSave(ctx context.Context) (_node *StickyMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(stickymessage.Table, stickymessage.Columns, sqlgraph.NewFieldSpec(stickymessage.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StickyMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stickymessage.FieldID)
		for _, f := range fields {
			if !stickymessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != stickymessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GuildID(); ok {
		_spec.SetField(stickymessage.FieldGuildID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChannelID(); ok {
		_spec.SetField(stickymessage.FieldChannelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(stickymessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastMessageID(); ok {
		_spec.SetField(stickymessage.FieldLastMessageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(stickymessage.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(stickymessage.FieldCreatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(stickymessage.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(stickymessage.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &StickyMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{stickymessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
