// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alt-bot/ent/predicate"
	"alt-bot/ent/stickymessage"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StickyMessageDelete is the builder for deleting a StickyMessage entity.
type StickyMessageDelete struct {
	config
	hooks    []Hook
	mutation *StickyMessageMutation
}

// Where appends a list predicates to the StickyMessageDelete builder.
func (_d *StickyMessageDelete) Where(ps ...predicate.StickyMessage) *StickyMessageDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *StickyMessageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StickyMessageDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *StickyMessageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(stickymessage.Table, sqlgraph.NewFieldSpec(stickymessage.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// StickyMessageDeleteOne is the builder for deleting a single StickyMessage entity.
type StickyMessageDeleteOne struct {
	_d *StickyMessageDelete
}

// Where appends a list predicates to the StickyMessageDelete builder.
func (_d *StickyMessageDeleteOne) Where(ps ...predicate.StickyMessage) *StickyMessageDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *StickyMessageDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{stickymessage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StickyMessageDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
