// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alt-bot/ent/transactionlog"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TransactionLogCreate is the builder for creating a TransactionLog entity.
type TransactionLogCreate struct {
	config
	mutation *TransactionLogMutation
	hooks    []Hook
}

// SetTxID sets the "tx_id" field.
func (_c *TransactionLogCreate) SetTxID(v string) *TransactionLogCreate {
	_c.mutation.SetTxID(v)
	return _c
}

// SetUserDiscordID sets the "user_discord_id" field.
func (_c *TransactionLogCreate) SetUserDiscordID(v string) *TransactionLogCreate {
	_c.mutation.SetUserDiscordID(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *TransactionLogCreate) SetKind(v string) *TransactionLogCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetYenDelta sets the "yen_delta" field.
func (_c *TransactionLogCreate) SetYenDelta(v int64) *TransactionLogCreate {
	_c.mutation.SetYenDelta(v)
	return _c
}

// SetNillableYenDelta sets the "yen_delta" field if the given value is not nil.
func (_c *TransactionLogCreate) SetNillableYenDelta(v *int64) *TransactionLogCreate {
	if v != nil {
		_c.SetYenDelta(*v)
	}
	return _c
}

// SetAltDelta sets the "alt_delta" field.
func (_c *TransactionLogCreate) SetAltDelta(v int64) *TransactionLogCreate {
	_c.mutation.SetAltDelta(v)
	return _c
}

// SetNillableAltDelta sets the "alt_delta" field if the given value is not nil.
func (_c *TransactionLogCreate) SetNillableAltDelta(v *int64) *TransactionLogCreate {
	if v != nil {
		_c.SetAltDelta(*v)
	}
	return _c
}

// SetXpDelta sets the "xp_delta" field.
func (_c *TransactionLogCreate) SetXpDelta(v int64) *TransactionLogCreate {
	_c.mutation.SetXpDelta(v)
	return _c
}

// SetNillableXpDelta sets the "xp_delta" field if the given value is not nil.
func (_c *TransactionLogCreate) SetNillableXpDelta(v *int64) *TransactionLogCreate {
	if v != nil {
		_c.SetXpDelta(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *TransactionLogCreate) SetAmount(v int64) *TransactionLogCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *TransactionLogCreate) SetNillableAmount(v *int64) *TransactionLogCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetSettledPrice sets the "settled_price" field.
func (_c *TransactionLogCreate) SetSettledPrice(v float64) *TransactionLogCreate {
	_c.mutation.SetSettledPrice(v)
	return _c
}

// SetNillableSettledPrice sets the "settled_price" field if the given value is not nil.
func (_c *TransactionLogCreate) SetNillableSettledPrice(v *float64) *TransactionLogCreate {
	if v != nil {
		_c.SetSettledPrice(*v)
	}
	return _c
}

// SetPriceAfter sets the "price_after" field.
func (_c *TransactionLogCreate) SetPriceAfter(v float64) *TransactionLogCreate {
	_c.mutation.SetPriceAfter(v)
	return _c
}

// SetNillablePriceAfter sets the "price_after" field if the given value is not nil.
func (_c *TransactionLogCreate) SetNillablePriceAfter(v *float64) *TransactionLogCreate {
	if v != nil {
		_c.SetPriceAfter(*v)
	}
	return _c
}

// SetBalanceAfter sets the "balance_after" field.
func (_c *TransactionLogCreate) SetBalanceAfter(v int64) *TransactionLogCreate {
	_c.mutation.SetBalanceAfter(v)
	return _c
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_c *TransactionLogCreate) SetNillableBalanceAfter(v *int64) *TransactionLogCreate {
	if v != nil {
		_c.SetBalanceAfter(*v)
	}
	return _c
}

// SetCryptoAfter sets the "crypto_after" field.
func (_c *TransactionLogCreate) SetCryptoAfter(v int64) *TransactionLogCreate {
	_c.mutation.SetCryptoAfter(v)
	return _c
}

// SetNillableCryptoAfter sets the "crypto_after" field if the given value is not nil.
func (_c *TransactionLogCreate) SetNillableCryptoAfter(v *int64) *TransactionLogCreate {
	if v != nil {
		_c.SetCryptoAfter(*v)
	}
	return _c
}

// SetPrevHash sets the "prev_hash" field.
func (_c *TransactionLogCreate) SetPrevHash(v string) *TransactionLogCreate {
	_c.mutation.SetPrevHash(v)
	return _c
}

// SetNillablePrevHash sets the "prev_hash" field if the given value is not nil.
func (_c *TransactionLogCreate) SetNillablePrevHash(v *string) *TransactionLogCreate {
	if v != nil {
		_c.SetPrevHash(*v)
	}
	return _c
}

// SetHash sets the "hash" field.
func (_c *TransactionLogCreate) SetHash(v string) *TransactionLogCreate {
	_c.mutation.SetHash(v)
	return _c
}

// SetSignature sets the "signature" field.
func (_c *TransactionLogCreate) SetSignature(v string) *TransactionLogCreate {
	_c.mutation.SetSignature(v)
	return _c
}

// SetPublicKey sets the "public_key" field.
func (_c *TransactionLogCreate) SetPublicKey(v string) *TransactionLogCreate {
	_c.mutation.SetPublicKey(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TransactionLogCreate) SetCreatedAt(v time.Time) *TransactionLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TransactionLogCreate) SetNillableCreatedAt(v *time.Time) *TransactionLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the TransactionLogMutation object of the builder.
func (_c *TransactionLogCreate) Mutation() *TransactionLogMutation {
	return _c.mutation
}

// Save creates the TransactionLog in the database.
func (_c *TransactionLogCreate) Save(ctx context.Context) (*TransactionLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TransactionLogCreate) SaveX(ctx context.Context) *TransactionLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransactionLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransactionLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TransactionLogCreate) defaults() {
	if _, ok := _c.mutation.YenDelta(); !ok {
		v := transactionlog.DefaultYenDelta
		_c.mutation.SetYenDelta(v)
	}
	if _, ok := _c.mutation.AltDelta(); !ok {
		v := transactionlog.DefaultAltDelta
		_c.mutation.SetAltDelta(v)
	}
	if _, ok := _c.mutation.XpDelta(); !ok {
		v := transactionlog.DefaultXpDelta
		_c.mutation.SetXpDelta(v)
	}
	if _, ok := _c.mutation.Amount(); !ok {
		v := transactionlog.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.SettledPrice(); !ok {
		v := transactionlog.DefaultSettledPrice
		_c.mutation.SetSettledPrice(v)
	}
	if _, ok := _c.mutation.PriceAfter(); !ok {
		v := transactionlog.DefaultPriceAfter
		_c.mutation.SetPriceAfter(v)
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		v := transactionlog.DefaultBalanceAfter
		_c.mutation.SetBalanceAfter(v)
	}
	if _, ok := _c.mutation.CryptoAfter(); !ok {
		v := transactionlog.DefaultCryptoAfter
		_c.mutation.SetCryptoAfter(v)
	}
	if _, ok := _c.mutation.PrevHash(); !ok {
		v := transactionlog.DefaultPrevHash
		_c.mutation.SetPrevHash(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := transactionlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TransactionLogCreate) check() error {
	if _, ok := _c.mutation.TxID(); !ok {
		return &ValidationError{Name: "tx_id", err: errors.New(`ent: missing required field "TransactionLog.tx_id"`)}
	}
	if v, ok := _c.mutation.TxID(); ok {
		if err := transactionlog.TxIDValidator(v); err != nil {
			return &ValidationError{Name: "tx_id", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.tx_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserDiscordID(); !ok {
		return &ValidationError{Name: "user_discord_id", err: errors.New(`ent: missing required field "TransactionLog.user_discord_id"`)}
	}
	if v, ok := _c.mutation.UserDiscordID(); ok {
		if err := transactionlog.UserDiscordIDValidator(v); err != nil {
			return &ValidationError{Name: "user_discord_id", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.user_discord_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "TransactionLog.kind"`)}
	}
	if v, ok := _c.mutation.Kind(); ok {
		if err := transactionlog.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.YenDelta(); !ok {
		return &ValidationError{Name: "yen_delta", err: errors.New(`ent: missing required field "TransactionLog.yen_delta"`)}
	}
	if _, ok := _c.mutation.AltDelta(); !ok {
		return &ValidationError{Name: "alt_delta", err: errors.New(`ent: missing required field "TransactionLog.alt_delta"`)}
	}
	if _, ok := _c.mutation.XpDelta(); !ok {
		return &ValidationError{Name: "xp_delta", err: errors.New(`ent: missing required field "TransactionLog.xp_delta"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "TransactionLog.amount"`)}
	}
	if _, ok := _c.mutation.SettledPrice(); !ok {
		return &ValidationError{Name: "settled_price", err: errors.New(`ent: missing required field "TransactionLog.settled_price"`)}
	}
	if _, ok := _c.mutation.PriceAfter(); !ok {
		return &ValidationError{Name: "price_after", err: errors.New(`ent: missing required field "TransactionLog.price_after"`)}
	}
	if _, ok := _c.mutation.BalanceAfter(); !ok {
		return &ValidationError{Name: "balance_after", err: errors.New(`ent: missing required field "TransactionLog.balance_after"`)}
	}
	if _, ok := _c.mutation.CryptoAfter(); !ok {
		return &ValidationError{Name: "crypto_after", err: errors.New(`ent: missing required field "TransactionLog.crypto_after"`)}
	}
	if _, ok := _c.mutation.PrevHash(); !ok {
		return &ValidationError{Name: "prev_hash", err: errors.New(`ent: missing required field "TransactionLog.prev_hash"`)}
	}
	if _, ok := _c.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "TransactionLog.hash"`)}
	}
	if v, ok := _c.mutation.Hash(); ok {
		if err := transactionlog.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Signature(); !ok {
		return &ValidationError{Name: "signature", err: errors.New(`ent: missing required field "TransactionLog.signature"`)}
	}
	if v, ok := _c.mutation.Signature(); ok {
		if err := transactionlog.SignatureValidator(v); err != nil {
			return &ValidationError{Name: "signature", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.signature": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublicKey(); !ok {
		return &ValidationError{Name: "public_key", err: errors.New(`ent: missing required field "TransactionLog.public_key"`)}
	}
	if v, ok := _c.mutation.PublicKey(); ok {
		if err := transactionlog.PublicKeyValidator(v); err != nil {
			return &ValidationError{Name: "public_key", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.public_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TransactionLog.created_at"`)}
	}
	return nil
}

func (_c *TransactionLogCreate) sqlSave(ctx context.Context) (*TransactionLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TransactionLogCreate) createSpec() (*TransactionLog, *sqlgraph.CreateSpec) {
	var (
		_node = &TransactionLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(transactionlog.Table, sqlgraph.NewFieldSpec(transactionlog.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.TxID(); ok {
		_spec.SetField(transactionlog.FieldTxID, field.TypeString, value)
		_node.TxID = value
	}
	if value, ok := _c.mutation.UserDiscordID(); ok {
		_spec.SetField(transactionlog.FieldUserDiscordID, field.TypeString, value)
		_node.UserDiscordID = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(transactionlog.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.YenDelta(); ok {
		_spec.SetField(transactionlog.FieldYenDelta, field.TypeInt64, value)
		_node.YenDelta = value
	}
	if value, ok := _c.mutation.AltDelta(); ok {
		_spec.SetField(transactionlog.FieldAltDelta, field.TypeInt64, value)
		_node.AltDelta = value
	}
	if value, ok := _c.mutation.XpDelta(); ok {
		_spec.SetField(transactionlog.FieldXpDelta, field.TypeInt64, value)
		_node.XpDelta = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(transactionlog.FieldAmount, field.TypeInt64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.SettledPrice(); ok {
		_spec.SetField(transactionlog.FieldSettledPrice, field.TypeFloat64, value)
		_node.SettledPrice = value
	}
	if value, ok := _c.mutation.PriceAfter(); ok {
		_spec.SetField(transactionlog.FieldPriceAfter, field.TypeFloat64, value)
		_node.PriceAfter = value
	}
	if value, ok := _c.mutation.BalanceAfter(); ok {
		_spec.SetField(transactionlog.FieldBalanceAfter, field.TypeInt64, value)
		_node.BalanceAfter = value
	}
	if value, ok := _c.mutation.CryptoAfter(); ok {
		_spec.SetField(transactionlog.FieldCryptoAfter, field.TypeInt64, value)
		_node.CryptoAfter = value
	}
	if value, ok := _c.mutation.PrevHash(); ok {
		_spec.SetField(transactionlog.FieldPrevHash, field.TypeString, value)
		_node.PrevHash = value
	}
	if value, ok := _c.mutation.Hash(); ok {
		_spec.SetField(transactionlog.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	if value, ok := _c.mutation.Signature(); ok {
		_spec.SetField(transactionlog.FieldSignature, field.TypeString, value)
		_node.Signature = value
	}
	if value, ok := _c.mutation.PublicKey(); ok {
		_spec.SetField(transactionlog.FieldPublicKey, field.TypeString, value)
		_node.PublicKey = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(transactionlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// TransactionLogCreateBulk is the builder for creating many TransactionLog entities in bulk.
type TransactionLogCreateBulk struct {
	config
	err      error
	builders []*TransactionLogCreate
}

// Save creates the TransactionLog entities in the database.
func (_c *TransactionLogCreateBulk) Save(ctx context.Context) ([]*TransactionLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TransactionLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TransactionLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TransactionLogCreateBulk) SaveX(ctx context.Context) []*TransactionLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TransactionLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TransactionLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
