// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alt-bot/ent/predicate"
	"alt-bot/ent/transactionlog"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TransactionLogUpdate is the builder for updating TransactionLog entities.
type TransactionLogUpdate struct {
	config
	hooks    []Hook
	mutation *TransactionLogMutation
}

// Where appends a list predicates to the TransactionLogUpdate builder.
func (_u *TransactionLogUpdate) Where(ps ...predicate.TransactionLog) *TransactionLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTxID sets the "tx_id" field.
func (_u *TransactionLogUpdate) SetTxID(v string) *TransactionLogUpdate {
	_u.mutation.SetTxID(v)
	return _u
}

// SetNillableTxID sets the "tx_id" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableTxID(v *string) *TransactionLogUpdate {
	if v != nil {
		_u.SetTxID(*v)
	}
	return _u
}

// SetUserDiscordID sets the "user_discord_id" field.
func (_u *TransactionLogUpdate) SetUserDiscordID(v string) *TransactionLogUpdate {
	_u.mutation.SetUserDiscordID(v)
	return _u
}

// SetNillableUserDiscordID sets the "user_discord_id" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableUserDiscordID(v *string) *TransactionLogUpdate {
	if v != nil {
		_u.SetUserDiscordID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *TransactionLogUpdate) SetKind(v string) *TransactionLogUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableKind(v *string) *TransactionLogUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetYenDelta sets the "yen_delta" field.
func (_u *TransactionLogUpdate) SetYenDelta(v int64) *TransactionLogUpdate {
	_u.mutation.ResetYenDelta()
	_u.mutation.SetYenDelta(v)
	return _u
}

// SetNillableYenDelta sets the "yen_delta" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableYenDelta(v *int64) *TransactionLogUpdate {
	if v != nil {
		_u.SetYenDelta(*v)
	}
	return _u
}

// AddYenDelta adds value to the "yen_delta" field.
func (_u *TransactionLogUpdate) AddYenDelta(v int64) *TransactionLogUpdate {
	_u.mutation.AddYenDelta(v)
	return _u
}

// SetAltDelta sets the "alt_delta" field.
func (_u *TransactionLogUpdate) SetAltDelta(v int64) *TransactionLogUpdate {
	_u.mutation.ResetAltDelta()
	_u.mutation.SetAltDelta(v)
	return _u
}

// SetNillableAltDelta sets the "alt_delta" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableAltDelta(v *int64) *TransactionLogUpdate {
	if v != nil {
		_u.SetAltDelta(*v)
	}
	return _u
}

// AddAltDelta adds value to the "alt_delta" field.
func (_u *TransactionLogUpdate) AddAltDelta(v int64) *TransactionLogUpdate {
	_u.mutation.AddAltDelta(v)
	return _u
}

// SetXpDelta sets the "xp_delta" field.
func (_u *TransactionLogUpdate) SetXpDelta(v int64) *TransactionLogUpdate {
	_u.mutation.ResetXpDelta()
	_u.mutation.SetXpDelta(v)
	return _u
}

// SetNillableXpDelta sets the "xp_delta" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableXpDelta(v *int64) *TransactionLogUpdate {
	if v != nil {
		_u.SetXpDelta(*v)
	}
	return _u
}

// AddXpDelta adds value to the "xp_delta" field.
func (_u *TransactionLogUpdate) AddXpDelta(v int64) *TransactionLogUpdate {
	_u.mutation.AddXpDelta(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TransactionLogUpdate) SetAmount(v int64) *TransactionLogUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableAmount(v *int64) *TransactionLogUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TransactionLogUpdate) AddAmount(v int64) *TransactionLogUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetSettledPrice sets the "settled_price" field.
func (_u *TransactionLogUpdate) SetSettledPrice(v float64) *TransactionLogUpdate {
	_u.mutation.ResetSettledPrice()
	_u.mutation.SetSettledPrice(v)
	return _u
}

// SetNillableSettledPrice sets the "settled_price" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableSettledPrice(v *float64) *TransactionLogUpdate {
	if v != nil {
		_u.SetSettledPrice(*v)
	}
	return _u
}

// AddSettledPrice adds value to the "settled_price" field.
func (_u *TransactionLogUpdate) AddSettledPrice(v float64) *TransactionLogUpdate {
	_u.mutation.AddSettledPrice(v)
	return _u
}

// SetPriceAfter sets the "price_after" field.
func (_u *TransactionLogUpdate) SetPriceAfter(v float64) *TransactionLogUpdate {
	_u.mutation.ResetPriceAfter()
	_u.mutation.SetPriceAfter(v)
	return _u
}

// SetNillablePriceAfter sets the "price_after" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillablePriceAfter(v *float64) *TransactionLogUpdate {
	if v != nil {
		_u.SetPriceAfter(*v)
	}
	return _u
}

// AddPriceAfter adds value to the "price_after" field.
func (_u *TransactionLogUpdate) AddPriceAfter(v float64) *TransactionLogUpdate {
	_u.mutation.AddPriceAfter(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *TransactionLogUpdate) SetBalanceAfter(v int64) *TransactionLogUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableBalanceAfter(v *int64) *TransactionLogUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *TransactionLogUpdate) AddBalanceAfter(v int64) *TransactionLogUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetCryptoAfter sets the "crypto_after" field.
func (_u *TransactionLogUpdate) SetCryptoAfter(v int64) *TransactionLogUpdate {
	_u.mutation.ResetCryptoAfter()
	_u.mutation.SetCryptoAfter(v)
	return _u
}

// SetNillableCryptoAfter sets the "crypto_after" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableCryptoAfter(v *int64) *TransactionLogUpdate {
	if v != nil {
		_u.SetCryptoAfter(*v)
	}
	return _u
}

// AddCryptoAfter adds value to the "crypto_after" field.
func (_u *TransactionLogUpdate) AddCryptoAfter(v int64) *TransactionLogUpdate {
	_u.mutation.AddCryptoAfter(v)
	return _u
}

// SetPrevHash sets the "prev_hash" field.
func (_u *TransactionLogUpdate) SetPrevHash(v string) *TransactionLogUpdate {
	_u.mutation.SetPrevHash(v)
	return _u
}

// SetNillablePrevHash sets the "prev_hash" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillablePrevHash(v *string) *TransactionLogUpdate {
	if v != nil {
		_u.SetPrevHash(*v)
	}
	return _u
}

// SetHash sets the "hash" field.
func (_u *TransactionLogUpdate) SetHash(v string) *TransactionLogUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableHash(v *string) *TransactionLogUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetSignature sets the "signature" field.
func (_u *TransactionLogUpdate) SetSignature(v string) *TransactionLogUpdate {
	_u.mutation.SetSignature(v)
	return _u
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillableSignature(v *string) *TransactionLogUpdate {
	if v != nil {
		_u.SetSignature(*v)
	}
	return _u
}

// SetPublicKey sets the "public_key" field.
func (_u *TransactionLogUpdate) SetPublicKey(v string) *TransactionLogUpdate {
	_u.mutation.SetPublicKey(v)
	return _u
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (_u *TransactionLogUpdate) SetNillablePublicKey(v *string) *TransactionLogUpdate {
	if v != nil {
		_u.SetPublicKey(*v)
	}
	return _u
}

// Mutation returns the TransactionLogMutation object of the builder.
func (_u *TransactionLogUpdate) Mutation() *TransactionLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TransactionLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TransactionLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransactionLogUpdate) check() error {
	if v, ok := _u.mutation.TxID(); ok {
		if err := transactionlog.TxIDValidator(v); err != nil {
			return &ValidationError{Name: "tx_id", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.tx_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserDiscordID(); ok {
		if err := transactionlog.UserDiscordIDValidator(v); err != nil {
			return &ValidationError{Name: "user_discord_id", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.user_discord_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := transactionlog.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hash(); ok {
		if err := transactionlog.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Signature(); ok {
		if err := transactionlog.SignatureValidator(v); err != nil {
			return &ValidationError{Name: "signature", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.signature": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicKey(); ok {
		if err := transactionlog.PublicKeyValidator(v); err != nil {
			return &ValidationError{Name: "public_key", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.public_key": %w`, err)}
		}
	}
	return nil
}

func (_u *TransactionLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transactionlog.Table, transactionlog.Columns, sqlgraph.NewFieldSpec(transactionlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TxID(); ok {
		_spec.SetField(transactionlog.FieldTxID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserDiscordID(); ok {
		_spec.SetField(transactionlog.FieldUserDiscordID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(transactionlog.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.YenDelta(); ok {
		_spec.SetField(transactionlog.FieldYenDelta, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedYenDelta(); ok {
		_spec.AddField(transactionlog.FieldYenDelta, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AltDelta(); ok {
		_spec.SetField(transactionlog.FieldAltDelta, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAltDelta(); ok {
		_spec.AddField(transactionlog.FieldAltDelta, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.XpDelta(); ok {
		_spec.SetField(transactionlog.FieldXpDelta, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedXpDelta(); ok {
		_spec.AddField(transactionlog.FieldXpDelta, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(transactionlog.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(transactionlog.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SettledPrice(); ok {
		_spec.SetField(transactionlog.FieldSettledPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSettledPrice(); ok {
		_spec.AddField(transactionlog.FieldSettledPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PriceAfter(); ok {
		_spec.SetField(transactionlog.FieldPriceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPriceAfter(); ok {
		_spec.AddField(transactionlog.FieldPriceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(transactionlog.FieldBalanceAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(transactionlog.FieldBalanceAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CryptoAfter(); ok {
		_spec.SetField(transactionlog.FieldCryptoAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCryptoAfter(); ok {
		_spec.AddField(transactionlog.FieldCryptoAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PrevHash(); ok {
		_spec.SetField(transactionlog.FieldPrevHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(transactionlog.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Signature(); ok {
		_spec.SetField(transactionlog.FieldSignature, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicKey(); ok {
		_spec.SetField(transactionlog.FieldPublicKey, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transactionlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TransactionLogUpdateOne is the builder for updating a single TransactionLog entity.
type TransactionLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TransactionLogMutation
}

// SetTxID sets the "tx_id" field.
func (_u *TransactionLogUpdateOne) SetTxID(v string) *TransactionLogUpdateOne {
	_u.mutation.SetTxID(v)
	return _u
}

// SetNillableTxID sets the "tx_id" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableTxID(v *string) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetTxID(*v)
	}
	return _u
}

// SetUserDiscordID sets the "user_discord_id" field.
func (_u *TransactionLogUpdateOne) SetUserDiscordID(v string) *TransactionLogUpdateOne {
	_u.mutation.SetUserDiscordID(v)
	return _u
}

// SetNillableUserDiscordID sets the "user_discord_id" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableUserDiscordID(v *string) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetUserDiscordID(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *TransactionLogUpdateOne) SetKind(v string) *TransactionLogUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableKind(v *string) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetYenDelta sets the "yen_delta" field.
func (_u *TransactionLogUpdateOne) SetYenDelta(v int64) *TransactionLogUpdateOne {
	_u.mutation.ResetYenDelta()
	_u.mutation.SetYenDelta(v)
	return _u
}

// SetNillableYenDelta sets the "yen_delta" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableYenDelta(v *int64) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetYenDelta(*v)
	}
	return _u
}

// AddYenDelta adds value to the "yen_delta" field.
func (_u *TransactionLogUpdateOne) AddYenDelta(v int64) *TransactionLogUpdateOne {
	_u.mutation.AddYenDelta(v)
	return _u
}

// SetAltDelta sets the "alt_delta" field.
func (_u *TransactionLogUpdateOne) SetAltDelta(v int64) *TransactionLogUpdateOne {
	_u.mutation.ResetAltDelta()
	_u.mutation.SetAltDelta(v)
	return _u
}

// SetNillableAltDelta sets the "alt_delta" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableAltDelta(v *int64) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetAltDelta(*v)
	}
	return _u
}

// AddAltDelta adds value to the "alt_delta" field.
func (_u *TransactionLogUpdateOne) AddAltDelta(v int64) *TransactionLogUpdateOne {
	_u.mutation.AddAltDelta(v)
	return _u
}

// SetXpDelta sets the "xp_delta" field.
func (_u *TransactionLogUpdateOne) SetXpDelta(v int64) *TransactionLogUpdateOne {
	_u.mutation.ResetXpDelta()
	_u.mutation.SetXpDelta(v)
	return _u
}

// SetNillableXpDelta sets the "xp_delta" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableXpDelta(v *int64) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetXpDelta(*v)
	}
	return _u
}

// AddXpDelta adds value to the "xp_delta" field.
func (_u *TransactionLogUpdateOne) AddXpDelta(v int64) *TransactionLogUpdateOne {
	_u.mutation.AddXpDelta(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *TransactionLogUpdateOne) SetAmount(v int64) *TransactionLogUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableAmount(v *int64) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *TransactionLogUpdateOne) AddAmount(v int64) *TransactionLogUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetSettledPrice sets the "settled_price" field.
func (_u *TransactionLogUpdateOne) SetSettledPrice(v float64) *TransactionLogUpdateOne {
	_u.mutation.ResetSettledPrice()
	_u.mutation.SetSettledPrice(v)
	return _u
}

// SetNillableSettledPrice sets the "settled_price" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableSettledPrice(v *float64) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetSettledPrice(*v)
	}
	return _u
}

// AddSettledPrice adds value to the "settled_price" field.
func (_u *TransactionLogUpdateOne) AddSettledPrice(v float64) *TransactionLogUpdateOne {
	_u.mutation.AddSettledPrice(v)
	return _u
}

// SetPriceAfter sets the "price_after" field.
func (_u *TransactionLogUpdateOne) SetPriceAfter(v float64) *TransactionLogUpdateOne {
	_u.mutation.ResetPriceAfter()
	_u.mutation.SetPriceAfter(v)
	return _u
}

// SetNillablePriceAfter sets the "price_after" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillablePriceAfter(v *float64) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetPriceAfter(*v)
	}
	return _u
}

// AddPriceAfter adds value to the "price_after" field.
func (_u *TransactionLogUpdateOne) AddPriceAfter(v float64) *TransactionLogUpdateOne {
	_u.mutation.AddPriceAfter(v)
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *TransactionLogUpdateOne) SetBalanceAfter(v int64) *TransactionLogUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableBalanceAfter(v *int64) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *TransactionLogUpdateOne) AddBalanceAfter(v int64) *TransactionLogUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// SetCryptoAfter sets the "crypto_after" field.
func (_u *TransactionLogUpdateOne) SetCryptoAfter(v int64) *TransactionLogUpdateOne {
	_u.mutation.ResetCryptoAfter()
	_u.mutation.SetCryptoAfter(v)
	return _u
}

// SetNillableCryptoAfter sets the "crypto_after" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableCryptoAfter(v *int64) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetCryptoAfter(*v)
	}
	return _u
}

// AddCryptoAfter adds value to the "crypto_after" field.
func (_u *TransactionLogUpdateOne) AddCryptoAfter(v int64) *TransactionLogUpdateOne {
	_u.mutation.AddCryptoAfter(v)
	return _u
}

// SetPrevHash sets the "prev_hash" field.
func (_u *TransactionLogUpdateOne) SetPrevHash(v string) *TransactionLogUpdateOne {
	_u.mutation.SetPrevHash(v)
	return _u
}

// SetNillablePrevHash sets the "prev_hash" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillablePrevHash(v *string) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetPrevHash(*v)
	}
	return _u
}

// SetHash sets the "hash" field.
func (_u *TransactionLogUpdateOne) SetHash(v string) *TransactionLogUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableHash(v *string) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetSignature sets the "signature" field.
func (_u *TransactionLogUpdateOne) SetSignature(v string) *TransactionLogUpdateOne {
	_u.mutation.SetSignature(v)
	return _u
}

// SetNillableSignature sets the "signature" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillableSignature(v *string) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetSignature(*v)
	}
	return _u
}

// SetPublicKey sets the "public_key" field.
func (_u *TransactionLogUpdateOne) SetPublicKey(v string) *TransactionLogUpdateOne {
	_u.mutation.SetPublicKey(v)
	return _u
}

// SetNillablePublicKey sets the "public_key" field if the given value is not nil.
func (_u *TransactionLogUpdateOne) SetNillablePublicKey(v *string) *TransactionLogUpdateOne {
	if v != nil {
		_u.SetPublicKey(*v)
	}
	return _u
}

// Mutation returns the TransactionLogMutation object of the builder.
func (_u *TransactionLogUpdateOne) Mutation() *TransactionLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the TransactionLogUpdate builder.
func (_u *TransactionLogUpdateOne) Where(ps ...predicate.TransactionLog) *TransactionLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TransactionLogUpdateOne) Select(field string, fields ...string) *TransactionLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TransactionLog entity.
func (_u *TransactionLogUpdateOne) Save(ctx context.Context) (*TransactionLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TransactionLogUpdateOne) SaveX(ctx context.Context) *TransactionLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TransactionLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TransactionLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TransactionLogUpdateOne) check() error {
	if v, ok := _u.mutation.TxID(); ok {
		if err := transactionlog.TxIDValidator(v); err != nil {
			return &ValidationError{Name: "tx_id", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.tx_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserDiscordID(); ok {
		if err := transactionlog.UserDiscordIDValidator(v); err != nil {
			return &ValidationError{Name: "user_discord_id", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.user_discord_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Kind(); ok {
		if err := transactionlog.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Hash(); ok {
		if err := transactionlog.HashValidator(v); err != nil {
			return &ValidationError{Name: "hash", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Signature(); ok {
		if err := transactionlog.SignatureValidator(v); err != nil {
			return &ValidationError{Name: "signature", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.signature": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicKey(); ok {
		if err := transactionlog.PublicKeyValidator(v); err != nil {
			return &ValidationError{Name: "public_key", err: fmt.Errorf(`ent: validator failed for field "TransactionLog.public_key": %w`, err)}
		}
	}
	return nil
}

func (_u *TransactionLogUpdateOne) sqlSave(ctx context.Context) (_node *TransactionLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(transactionlog.Table, transactionlog.Columns, sqlgraph.NewFieldSpec(transactionlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TransactionLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, transactionlog.FieldID)
		for _, f := range fields {
			if !transactionlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != transactionlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TxID(); ok {
		_spec.SetField(transactionlog.FieldTxID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserDiscordID(); ok {
		_spec.SetField(transactionlog.FieldUserDiscordID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(transactionlog.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.YenDelta(); ok {
		_spec.SetField(transactionlog.FieldYenDelta, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedYenDelta(); ok {
		_spec.AddField(transactionlog.FieldYenDelta, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AltDelta(); ok {
		_spec.SetField(transactionlog.FieldAltDelta, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAltDelta(); ok {
		_spec.AddField(transactionlog.FieldAltDelta, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.XpDelta(); ok {
		_spec.SetField(transactionlog.FieldXpDelta, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedXpDelta(); ok {
		_spec.AddField(transactionlog.FieldXpDelta, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(transactionlog.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(transactionlog.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SettledPrice(); ok {
		_spec.SetField(transactionlog.FieldSettledPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSettledPrice(); ok {
		_spec.AddField(transactionlog.FieldSettledPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PriceAfter(); ok {
		_spec.SetField(transactionlog.FieldPriceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPriceAfter(); ok {
		_spec.AddField(transactionlog.FieldPriceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(transactionlog.FieldBalanceAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(transactionlog.FieldBalanceAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CryptoAfter(); ok {
		_spec.SetField(transactionlog.FieldCryptoAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCryptoAfter(); ok {
		_spec.AddField(transactionlog.FieldCryptoAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PrevHash(); ok {
		_spec.SetField(transactionlog.FieldPrevHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(transactionlog.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Signature(); ok {
		_spec.SetField(transactionlog.FieldSignature, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicKey(); ok {
		_spec.SetField(transactionlog.FieldPublicKey, field.TypeString, value)
	}
	_node = &TransactionLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{transactionlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
