// Code generated by ent, DO NOT EDIT.

package ent

import (
	"alt-bot/ent/predicate"
	"alt-bot/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDiscordID sets the "discord_id" field.
func (_u *UserUpdate) SetDiscordID(v string) *UserUpdate {
	_u.mutation.SetDiscordID(v)
	return _u
}

// SetNillableDiscordID sets the "discord_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDiscordID(v *string) *UserUpdate {
	if v != nil {
		_u.SetDiscordID(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *UserUpdate) SetBalance(v int64) *UserUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *UserUpdate) SetNillableBalance(v *int64) *UserUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *UserUpdate) AddBalance(v int64) *UserUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetCryptoBalance sets the "crypto_balance" field.
func (_u *UserUpdate) SetCryptoBalance(v int64) *UserUpdate {
	_u.mutation.ResetCryptoBalance()
	_u.mutation.SetCryptoBalance(v)
	return _u
}

// SetNillableCryptoBalance sets the "crypto_balance" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCryptoBalance(v *int64) *UserUpdate {
	if v != nil {
		_u.SetCryptoBalance(*v)
	}
	return _u
}

// AddCryptoBalance adds value to the "crypto_balance" field.
func (_u *UserUpdate) AddCryptoBalance(v int64) *UserUpdate {
	_u.mutation.AddCryptoBalance(v)
	return _u
}

// SetXp sets the "xp" field.
func (_u *UserUpdate) SetXp(v int64) *UserUpdate {
	_u.mutation.ResetXp()
	_u.mutation.SetXp(v)
	return _u
}

// SetNillableXp sets the "xp" field if the given value is not nil.
func (_u *UserUpdate) SetNillableXp(v *int64) *UserUpdate {
	if v != nil {
		_u.SetXp(*v)
	}
	return _u
}

// AddXp adds value to the "xp" field.
func (_u *UserUpdate) AddXp(v int64) *UserUpdate {
	_u.mutation.AddXp(v)
	return _u
}

// SetWorkEndAt sets the "work_end_at" field.
func (_u *UserUpdate) SetWorkEndAt(v time.Time) *UserUpdate {
	_u.mutation.SetWorkEndAt(v)
	return _u
}

// SetNillableWorkEndAt sets the "work_end_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableWorkEndAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetWorkEndAt(*v)
	}
	return _u
}

// SetDailyProfitEarned sets the "daily_profit_earned" field.
func (_u *UserUpdate) SetDailyProfitEarned(v int64) *UserUpdate {
	_u.mutation.ResetDailyProfitEarned()
	_u.mutation.SetDailyProfitEarned(v)
	return _u
}

// SetNillableDailyProfitEarned sets the "daily_profit_earned" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDailyProfitEarned(v *int64) *UserUpdate {
	if v != nil {
		_u.SetDailyProfitEarned(*v)
	}
	return _u
}

// AddDailyProfitEarned adds value to the "daily_profit_earned" field.
func (_u *UserUpdate) AddDailyProfitEarned(v int64) *UserUpdate {
	_u.mutation.AddDailyProfitEarned(v)
	return _u
}

// SetLastDailyResetAt sets the "last_daily_reset_at" field.
func (_u *UserUpdate) SetLastDailyResetAt(v time.Time) *UserUpdate {
	_u.mutation.SetLastDailyResetAt(v)
	return _u
}

// SetNillableLastDailyResetAt sets the "last_daily_reset_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLastDailyResetAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetLastDailyResetAt(*v)
	}
	return _u
}

// SetWeeklyProfitEarned sets the "weekly_profit_earned" field.
func (_u *UserUpdate) SetWeeklyProfitEarned(v int64) *UserUpdate {
	_u.mutation.ResetWeeklyProfitEarned()
	_u.mutation.SetWeeklyProfitEarned(v)
	return _u
}

// SetNillableWeeklyProfitEarned sets the "weekly_profit_earned" field if the given value is not nil.
func (_u *UserUpdate) SetNillableWeeklyProfitEarned(v *int64) *UserUpdate {
	if v != nil {
		_u.SetWeeklyProfitEarned(*v)
	}
	return _u
}

// AddWeeklyProfitEarned adds value to the "weekly_profit_earned" field.
func (_u *UserUpdate) AddWeeklyProfitEarned(v int64) *UserUpdate {
	_u.mutation.AddWeeklyProfitEarned(v)
	return _u
}

// SetLastWeeklyResetAt sets the "last_weekly_reset_at" field.
func (_u *UserUpdate) SetLastWeeklyResetAt(v time.Time) *UserUpdate {
	_u.mutation.SetLastWeeklyResetAt(v)
	return _u
}

// SetNillableLastWeeklyResetAt sets the "last_weekly_reset_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableLastWeeklyResetAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetLastWeeklyResetAt(*v)
	}
	return _u
}

// SetSecurityCameraCount sets the "security_camera_count" field.
func (_u *UserUpdate) SetSecurityCameraCount(v int64) *UserUpdate {
	_u.mutation.ResetSecurityCameraCount()
	_u.mutation.SetSecurityCameraCount(v)
	return _u
}

// SetNillableSecurityCameraCount sets the "security_camera_count" field if the given value is not nil.
func (_u *UserUpdate) SetNillableSecurityCameraCount(v *int64) *UserUpdate {
	if v != nil {
		_u.SetSecurityCameraCount(*v)
	}
	return _u
}

// AddSecurityCameraCount adds value to the "security_camera_count" field.
func (_u *UserUpdate) AddSecurityCameraCount(v int64) *UserUpdate {
	_u.mutation.AddSecurityCameraCount(v)
	return _u
}

// SetRobEndAt sets the "rob_end_at" field.
func (_u *UserUpdate) SetRobEndAt(v time.Time) *UserUpdate {
	_u.mutation.SetRobEndAt(v)
	return _u
}

// SetNillableRobEndAt sets the "rob_end_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableRobEndAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetRobEndAt(*v)
	}
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.DiscordID(); ok {
		if err := user.DiscordIDValidator(v); err != nil {
			return &ValidationError{Name: "discord_id", err: fmt.Errorf(`ent: validator failed for field "User.discord_id": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DiscordID(); ok {
		_spec.SetField(user.FieldDiscordID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(user.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(user.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CryptoBalance(); ok {
		_spec.SetField(user.FieldCryptoBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCryptoBalance(); ok {
		_spec.AddField(user.FieldCryptoBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Xp(); ok {
		_spec.SetField(user.FieldXp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedXp(); ok {
		_spec.AddField(user.FieldXp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WorkEndAt(); ok {
		_spec.SetField(user.FieldWorkEndAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DailyProfitEarned(); ok {
		_spec.SetField(user.FieldDailyProfitEarned, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDailyProfitEarned(); ok {
		_spec.AddField(user.FieldDailyProfitEarned, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastDailyResetAt(); ok {
		_spec.SetField(user.FieldLastDailyResetAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WeeklyProfitEarned(); ok {
		_spec.SetField(user.FieldWeeklyProfitEarned, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyProfitEarned(); ok {
		_spec.AddField(user.FieldWeeklyProfitEarned, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastWeeklyResetAt(); ok {
		_spec.SetField(user.FieldLastWeeklyResetAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SecurityCameraCount(); ok {
		_spec.SetField(user.FieldSecurityCameraCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSecurityCameraCount(); ok {
		_spec.AddField(user.FieldSecurityCameraCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RobEndAt(); ok {
		_spec.SetField(user.FieldRobEndAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetDiscordID sets the "discord_id" field.
func (_u *UserUpdateOne) SetDiscordID(v string) *UserUpdateOne {
	_u.mutation.SetDiscordID(v)
	return _u
}

// SetNillableDiscordID sets the "discord_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDiscordID(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetDiscordID(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *UserUpdateOne) SetBalance(v int64) *UserUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableBalance(v *int64) *UserUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *UserUpdateOne) AddBalance(v int64) *UserUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetCryptoBalance sets the "crypto_balance" field.
func (_u *UserUpdateOne) SetCryptoBalance(v int64) *UserUpdateOne {
	_u.mutation.ResetCryptoBalance()
	_u.mutation.SetCryptoBalance(v)
	return _u
}

// SetNillableCryptoBalance sets the "crypto_balance" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCryptoBalance(v *int64) *UserUpdateOne {
	if v != nil {
		_u.SetCryptoBalance(*v)
	}
	return _u
}

// AddCryptoBalance adds value to the "crypto_balance" field.
func (_u *UserUpdateOne) AddCryptoBalance(v int64) *UserUpdateOne {
	_u.mutation.AddCryptoBalance(v)
	return _u
}

// SetXp sets the "xp" field.
func (_u *UserUpdateOne) SetXp(v int64) *UserUpdateOne {
	_u.mutation.ResetXp()
	_u.mutation.SetXp(v)
	return _u
}

// SetNillableXp sets the "xp" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableXp(v *int64) *UserUpdateOne {
	if v != nil {
		_u.SetXp(*v)
	}
	return _u
}

// AddXp adds value to the "xp" field.
func (_u *UserUpdateOne) AddXp(v int64) *UserUpdateOne {
	_u.mutation.AddXp(v)
	return _u
}

// SetWorkEndAt sets the "work_end_at" field.
func (_u *UserUpdateOne) SetWorkEndAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetWorkEndAt(v)
	return _u
}

// SetNillableWorkEndAt sets the "work_end_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableWorkEndAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetWorkEndAt(*v)
	}
	return _u
}

// SetDailyProfitEarned sets the "daily_profit_earned" field.
func (_u *UserUpdateOne) SetDailyProfitEarned(v int64) *UserUpdateOne {
	_u.mutation.ResetDailyProfitEarned()
	_u.mutation.SetDailyProfitEarned(v)
	return _u
}

// SetNillableDailyProfitEarned sets the "daily_profit_earned" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDailyProfitEarned(v *int64) *UserUpdateOne {
	if v != nil {
		_u.SetDailyProfitEarned(*v)
	}
	return _u
}

// AddDailyProfitEarned adds value to the "daily_profit_earned" field.
func (_u *UserUpdateOne) AddDailyProfitEarned(v int64) *UserUpdateOne {
	_u.mutation.AddDailyProfitEarned(v)
	return _u
}

// SetLastDailyResetAt sets the "last_daily_reset_at" field.
func (_u *UserUpdateOne) SetLastDailyResetAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetLastDailyResetAt(v)
	return _u
}

// SetNillableLastDailyResetAt sets the "last_daily_reset_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastDailyResetAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetLastDailyResetAt(*v)
	}
	return _u
}

// SetWeeklyProfitEarned sets the "weekly_profit_earned" field.
func (_u *UserUpdateOne) SetWeeklyProfitEarned(v int64) *UserUpdateOne {
	_u.mutation.ResetWeeklyProfitEarned()
	_u.mutation.SetWeeklyProfitEarned(v)
	return _u
}

// SetNillableWeeklyProfitEarned sets the "weekly_profit_earned" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableWeeklyProfitEarned(v *int64) *UserUpdateOne {
	if v != nil {
		_u.SetWeeklyProfitEarned(*v)
	}
	return _u
}

// AddWeeklyProfitEarned adds value to the "weekly_profit_earned" field.
func (_u *UserUpdateOne) AddWeeklyProfitEarned(v int64) *UserUpdateOne {
	_u.mutation.AddWeeklyProfitEarned(v)
	return _u
}

// SetLastWeeklyResetAt sets the "last_weekly_reset_at" field.
func (_u *UserUpdateOne) SetLastWeeklyResetAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetLastWeeklyResetAt(v)
	return _u
}

// SetNillableLastWeeklyResetAt sets the "last_weekly_reset_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableLastWeeklyResetAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetLastWeeklyResetAt(*v)
	}
	return _u
}

// SetSecurityCameraCount sets the "security_camera_count" field.
func (_u *UserUpdateOne) SetSecurityCameraCount(v int64) *UserUpdateOne {
	_u.mutation.ResetSecurityCameraCount()
	_u.mutation.SetSecurityCameraCount(v)
	return _u
}

// SetNillableSecurityCameraCount sets the "security_camera_count" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableSecurityCameraCount(v *int64) *UserUpdateOne {
	if v != nil {
		_u.SetSecurityCameraCount(*v)
	}
	return _u
}

// AddSecurityCameraCount adds value to the "security_camera_count" field.
func (_u *UserUpdateOne) AddSecurityCameraCount(v int64) *UserUpdateOne {
	_u.mutation.AddSecurityCameraCount(v)
	return _u
}

// SetRobEndAt sets the "rob_end_at" field.
func (_u *UserUpdateOne) SetRobEndAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetRobEndAt(v)
	return _u
}

// SetNillableRobEndAt sets the "rob_end_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableRobEndAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetRobEndAt(*v)
	}
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.DiscordID(); ok {
		if err := user.DiscordIDValidator(v); err != nil {
			return &ValidationError{Name: "discord_id", err: fmt.Errorf(`ent: validator failed for field "User.discord_id": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DiscordID(); ok {
		_spec.SetField(user.FieldDiscordID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(user.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(user.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CryptoBalance(); ok {
		_spec.SetField(user.FieldCryptoBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCryptoBalance(); ok {
		_spec.AddField(user.FieldCryptoBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Xp(); ok {
		_spec.SetField(user.FieldXp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedXp(); ok {
		_spec.AddField(user.FieldXp, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WorkEndAt(); ok {
		_spec.SetField(user.FieldWorkEndAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DailyProfitEarned(); ok {
		_spec.SetField(user.FieldDailyProfitEarned, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDailyProfitEarned(); ok {
		_spec.AddField(user.FieldDailyProfitEarned, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastDailyResetAt(); ok {
		_spec.SetField(user.FieldLastDailyResetAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WeeklyProfitEarned(); ok {
		_spec.SetField(user.FieldWeeklyProfitEarned, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedWeeklyProfitEarned(); ok {
		_spec.AddField(user.FieldWeeklyProfitEarned, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.LastWeeklyResetAt(); ok {
		_spec.SetField(user.FieldLastWeeklyResetAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SecurityCameraCount(); ok {
		_spec.SetField(user.FieldSecurityCameraCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSecurityCameraCount(); ok {
		_spec.AddField(user.FieldSecurityCameraCount, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RobEndAt(); ok {
		_spec.SetField(user.FieldRobEndAt, field.TypeTime, value)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
