// Code generated by ent, DO NOT EDIT.

package guild

import (
	"alt-bot/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Guild {
	return predicate.Guild(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Guild {
	return predicate.Guild(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Guild {
	return predicate.Guild(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Guild {
	return predicate.Guild(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Guild {
	return predicate.Guild(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Guild {
	return predicate.Guild(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Guild {
	return predicate.Guild(sql.FieldLTE(FieldID, id))
}

// GuildID applies equality check predicate on the "guild_id" field. It's identical to GuildIDEQ.
func GuildID(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldGuildID, v))
}

// NewsChannelID applies equality check predicate on the "news_channel_id" field. It's identical to NewsChannelIDEQ.
func NewsChannelID(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldNewsChannelID, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldUpdatedAt, v))
}

// GuildIDEQ applies the EQ predicate on the "guild_id" field.
func GuildIDEQ(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldGuildID, v))
}

// GuildIDNEQ applies the NEQ predicate on the "guild_id" field.
func GuildIDNEQ(v string) predicate.Guild {
	return predicate.Guild(sql.FieldNEQ(FieldGuildID, v))
}

// GuildIDIn applies the In predicate on the "guild_id" field.
func GuildIDIn(vs ...string) predicate.Guild {
	return predicate.Guild(sql.FieldIn(FieldGuildID, vs...))
}

// GuildIDNotIn applies the NotIn predicate on the "guild_id" field.
func GuildIDNotIn(vs ...string) predicate.Guild {
	return predicate.Guild(sql.FieldNotIn(FieldGuildID, vs...))
}

// GuildIDGT applies the GT predicate on the "guild_id" field.
func GuildIDGT(v string) predicate.Guild {
	return predicate.Guild(sql.FieldGT(FieldGuildID, v))
}

// GuildIDGTE applies the GTE predicate on the "guild_id" field.
func GuildIDGTE(v string) predicate.Guild {
	return predicate.Guild(sql.FieldGTE(FieldGuildID, v))
}

// GuildIDLT applies the LT predicate on the "guild_id" field.
func GuildIDLT(v string) predicate.Guild {
	return predicate.Guild(sql.FieldLT(FieldGuildID, v))
}

// GuildIDLTE applies the LTE predicate on the "guild_id" field.
func GuildIDLTE(v string) predicate.Guild {
	return predicate.Guild(sql.FieldLTE(FieldGuildID, v))
}

// GuildIDContains applies the Contains predicate on the "guild_id" field.
func GuildIDContains(v string) predicate.Guild {
	return predicate.Guild(sql.FieldContains(FieldGuildID, v))
}

// GuildIDHasPrefix applies the HasPrefix predicate on the "guild_id" field.
func GuildIDHasPrefix(v string) predicate.Guild {
	return predicate.Guild(sql.FieldHasPrefix(FieldGuildID, v))
}

// GuildIDHasSuffix applies the HasSuffix predicate on the "guild_id" field.
func GuildIDHasSuffix(v string) predicate.Guild {
	return predicate.Guild(sql.FieldHasSuffix(FieldGuildID, v))
}

// GuildIDEqualFold applies the EqualFold predicate on the "guild_id" field.
func GuildIDEqualFold(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEqualFold(FieldGuildID, v))
}

// GuildIDContainsFold applies the ContainsFold predicate on the "guild_id" field.
func GuildIDContainsFold(v string) predicate.Guild {
	return predicate.Guild(sql.FieldContainsFold(FieldGuildID, v))
}

// NewsChannelIDEQ applies the EQ predicate on the "news_channel_id" field.
func NewsChannelIDEQ(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldNewsChannelID, v))
}

// NewsChannelIDNEQ applies the NEQ predicate on the "news_channel_id" field.
func NewsChannelIDNEQ(v string) predicate.Guild {
	return predicate.Guild(sql.FieldNEQ(FieldNewsChannelID, v))
}

// NewsChannelIDIn applies the In predicate on the "news_channel_id" field.
func NewsChannelIDIn(vs ...string) predicate.Guild {
	return predicate.Guild(sql.FieldIn(FieldNewsChannelID, vs...))
}

// NewsChannelIDNotIn applies the NotIn predicate on the "news_channel_id" field.
func NewsChannelIDNotIn(vs ...string) predicate.Guild {
	return predicate.Guild(sql.FieldNotIn(FieldNewsChannelID, vs...))
}

// NewsChannelIDGT applies the GT predicate on the "news_channel_id" field.
func NewsChannelIDGT(v string) predicate.Guild {
	return predicate.Guild(sql.FieldGT(FieldNewsChannelID, v))
}

// NewsChannelIDGTE applies the GTE predicate on the "news_channel_id" field.
func NewsChannelIDGTE(v string) predicate.Guild {
	return predicate.Guild(sql.FieldGTE(FieldNewsChannelID, v))
}

// NewsChannelIDLT applies the LT predicate on the "news_channel_id" field.
func NewsChannelIDLT(v string) predicate.Guild {
	return predicate.Guild(sql.FieldLT(FieldNewsChannelID, v))
}

// NewsChannelIDLTE applies the LTE predicate on the "news_channel_id" field.
func NewsChannelIDLTE(v string) predicate.Guild {
	return predicate.Guild(sql.FieldLTE(FieldNewsChannelID, v))
}

// NewsChannelIDContains applies the Contains predicate on the "news_channel_id" field.
func NewsChannelIDContains(v string) predicate.Guild {
	return predicate.Guild(sql.FieldContains(FieldNewsChannelID, v))
}

// NewsChannelIDHasPrefix applies the HasPrefix predicate on the "news_channel_id" field.
func NewsChannelIDHasPrefix(v string) predicate.Guild {
	return predicate.Guild(sql.FieldHasPrefix(FieldNewsChannelID, v))
}

// NewsChannelIDHasSuffix applies the HasSuffix predicate on the "news_channel_id" field.
func NewsChannelIDHasSuffix(v string) predicate.Guild {
	return predicate.Guild(sql.FieldHasSuffix(FieldNewsChannelID, v))
}

// NewsChannelIDEqualFold applies the EqualFold predicate on the "news_channel_id" field.
func NewsChannelIDEqualFold(v string) predicate.Guild {
	return predicate.Guild(sql.FieldEqualFold(FieldNewsChannelID, v))
}

// NewsChannelIDContainsFold applies the ContainsFold predicate on the "news_channel_id" field.
func NewsChannelIDContainsFold(v string) predicate.Guild {
	return predicate.Guild(sql.FieldContainsFold(FieldNewsChannelID, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Guild {
	return predicate.Guild(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Guild {
	return predicate.Guild(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Guild {
	return predicate.Guild(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Guild {
	return predicate.Guild(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Guild {
	return predicate.Guild(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Guild {
	return predicate.Guild(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Guild {
	return predicate.Guild(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Guild {
	return predicate.Guild(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Guild) predicate.Guild {
	return predicate.Guild(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Guild) predicate.Guild {
	return predicate.Guild(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Guild) predicate.Guild {
	return predicate.Guild(sql.NotPredicates(p))
}
