// Code generated by ent, DO NOT EDIT.

package chainstate

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the chainstate type in the database.
	Label = "chain_state"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLatestHash holds the string denoting the latest_hash field in the database.
	FieldLatestHash = "latest_hash"
	// Table holds the table name of the chainstate in the database.
	Table = "chain_states"
)

// Columns holds all SQL columns for chainstate fields.
var Columns = []string{
	FieldID,
	FieldLatestHash,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLatestHash holds the default value on creation for the "latest_hash" field.
	DefaultLatestHash string
)

// OrderOption defines the ordering options for the ChainState queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByLatestHash orders the results by the latest_hash field.
func ByLatestHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatestHash, opts...).ToFunc()
}
