// Code generated by ent, DO NOT EDIT.

package chainstate

import (
	"alt-bot/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ChainState {
	return predicate.ChainState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ChainState {
	return predicate.ChainState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ChainState {
	return predicate.ChainState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ChainState {
	return predicate.ChainState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ChainState {
	return predicate.ChainState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ChainState {
	return predicate.ChainState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ChainState {
	return predicate.ChainState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ChainState {
	return predicate.ChainState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ChainState {
	return predicate.ChainState(sql.FieldLTE(FieldID, id))
}

// LatestHash applies equality check predicate on the "latest_hash" field. It's identical to LatestHashEQ.
func LatestHash(v string) predicate.ChainState {
	return predicate.ChainState(sql.FieldEQ(FieldLatestHash, v))
}

// LatestHashEQ applies the EQ predicate on the "latest_hash" field.
func LatestHashEQ(v string) predicate.ChainState {
	return predicate.ChainState(sql.FieldEQ(FieldLatestHash, v))
}

// LatestHashNEQ applies the NEQ predicate on the "latest_hash" field.
func LatestHashNEQ(v string) predicate.ChainState {
	return predicate.ChainState(sql.FieldNEQ(FieldLatestHash, v))
}

// LatestHashIn applies the In predicate on the "latest_hash" field.
func LatestHashIn(vs ...string) predicate.ChainState {
	return predicate.ChainState(sql.FieldIn(FieldLatestHash, vs...))
}

// LatestHashNotIn applies the NotIn predicate on the "latest_hash" field.
func LatestHashNotIn(vs ...string) predicate.ChainState {
	return predicate.ChainState(sql.FieldNotIn(FieldLatestHash, vs...))
}

// LatestHashGT applies the GT predicate on the "latest_hash" field.
func LatestHashGT(v string) predicate.ChainState {
	return predicate.ChainState(sql.FieldGT(FieldLatestHash, v))
}

// LatestHashGTE applies the GTE predicate on the "latest_hash" field.
func LatestHashGTE(v string) predicate.ChainState {
	return predicate.ChainState(sql.FieldGTE(FieldLatestHash, v))
}

// LatestHashLT applies the LT predicate on the "latest_hash" field.
func LatestHashLT(v string) predicate.ChainState {
	return predicate.ChainState(sql.FieldLT(FieldLatestHash, v))
}

// LatestHashLTE applies the LTE predicate on the "latest_hash" field.
func LatestHashLTE(v string) predicate.ChainState {
	return predicate.ChainState(sql.FieldLTE(FieldLatestHash, v))
}

// LatestHashContains applies the Contains predicate on the "latest_hash" field.
func LatestHashContains(v string) predicate.ChainState {
	return predicate.ChainState(sql.FieldContains(FieldLatestHash, v))
}

// LatestHashHasPrefix applies the HasPrefix predicate on the "latest_hash" field.
func LatestHashHasPrefix(v string) predicate.ChainState {
	return predicate.ChainState(sql.FieldHasPrefix(FieldLatestHash, v))
}

// LatestHashHasSuffix applies the HasSuffix predicate on the "latest_hash" field.
func LatestHashHasSuffix(v string) predicate.ChainState {
	return predicate.ChainState(sql.FieldHasSuffix(FieldLatestHash, v))
}

// LatestHashEqualFold applies the EqualFold predicate on the "latest_hash" field.
func LatestHashEqualFold(v string) predicate.ChainState {
	return predicate.ChainState(sql.FieldEqualFold(FieldLatestHash, v))
}

// LatestHashContainsFold applies the ContainsFold predicate on the "latest_hash" field.
func LatestHashContainsFold(v string) predicate.ChainState {
	return predicate.ChainState(sql.FieldContainsFold(FieldLatestHash, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChainState) predicate.ChainState {
	return predicate.ChainState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChainState) predicate.ChainState {
	return predicate.ChainState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChainState) predicate.ChainState {
	return predicate.ChainState(sql.NotPredicates(p))
}
