// Code generated by ent, DO NOT EDIT.

package transactionlog

import (
	"alt-bot/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldID, id))
}

// TxID applies equality check predicate on the "tx_id" field. It's identical to TxIDEQ.
func TxID(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldTxID, v))
}

// UserDiscordID applies equality check predicate on the "user_discord_id" field. It's identical to UserDiscordIDEQ.
func UserDiscordID(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldUserDiscordID, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldKind, v))
}

// YenDelta applies equality check predicate on the "yen_delta" field. It's identical to YenDeltaEQ.
func YenDelta(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldYenDelta, v))
}

// AltDelta applies equality check predicate on the "alt_delta" field. It's identical to AltDeltaEQ.
func AltDelta(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldAltDelta, v))
}

// XpDelta applies equality check predicate on the "xp_delta" field. It's identical to XpDeltaEQ.
func XpDelta(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldXpDelta, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldAmount, v))
}

// SettledPrice applies equality check predicate on the "settled_price" field. It's identical to SettledPriceEQ.
func SettledPrice(v float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldSettledPrice, v))
}

// PriceAfter applies equality check predicate on the "price_after" field. It's identical to PriceAfterEQ.
func PriceAfter(v float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldPriceAfter, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldBalanceAfter, v))
}

// CryptoAfter applies equality check predicate on the "crypto_after" field. It's identical to CryptoAfterEQ.
func CryptoAfter(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldCryptoAfter, v))
}

// PrevHash applies equality check predicate on the "prev_hash" field. It's identical to PrevHashEQ.
func PrevHash(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldPrevHash, v))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldHash, v))
}

// Signature applies equality check predicate on the "signature" field. It's identical to SignatureEQ.
func Signature(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldSignature, v))
}

// PublicKey applies equality check predicate on the "public_key" field. It's identical to PublicKeyEQ.
func PublicKey(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldPublicKey, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldCreatedAt, v))
}

// TxIDEQ applies the EQ predicate on the "tx_id" field.
func TxIDEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldTxID, v))
}

// TxIDNEQ applies the NEQ predicate on the "tx_id" field.
func TxIDNEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldTxID, v))
}

// TxIDIn applies the In predicate on the "tx_id" field.
func TxIDIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldTxID, vs...))
}

// TxIDNotIn applies the NotIn predicate on the "tx_id" field.
func TxIDNotIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldTxID, vs...))
}

// TxIDGT applies the GT predicate on the "tx_id" field.
func TxIDGT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldTxID, v))
}

// TxIDGTE applies the GTE predicate on the "tx_id" field.
func TxIDGTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldTxID, v))
}

// TxIDLT applies the LT predicate on the "tx_id" field.
func TxIDLT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldTxID, v))
}

// TxIDLTE applies the LTE predicate on the "tx_id" field.
func TxIDLTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldTxID, v))
}

// TxIDContains applies the Contains predicate on the "tx_id" field.
func TxIDContains(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContains(FieldTxID, v))
}

// TxIDHasPrefix applies the HasPrefix predicate on the "tx_id" field.
func TxIDHasPrefix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasPrefix(FieldTxID, v))
}

// TxIDHasSuffix applies the HasSuffix predicate on the "tx_id" field.
func TxIDHasSuffix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasSuffix(FieldTxID, v))
}

// TxIDEqualFold applies the EqualFold predicate on the "tx_id" field.
func TxIDEqualFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEqualFold(FieldTxID, v))
}

// TxIDContainsFold applies the ContainsFold predicate on the "tx_id" field.
func TxIDContainsFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContainsFold(FieldTxID, v))
}

// UserDiscordIDEQ applies the EQ predicate on the "user_discord_id" field.
func UserDiscordIDEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldUserDiscordID, v))
}

// UserDiscordIDNEQ applies the NEQ predicate on the "user_discord_id" field.
func UserDiscordIDNEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldUserDiscordID, v))
}

// UserDiscordIDIn applies the In predicate on the "user_discord_id" field.
func UserDiscordIDIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldUserDiscordID, vs...))
}

// UserDiscordIDNotIn applies the NotIn predicate on the "user_discord_id" field.
func UserDiscordIDNotIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldUserDiscordID, vs...))
}

// UserDiscordIDGT applies the GT predicate on the "user_discord_id" field.
func UserDiscordIDGT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldUserDiscordID, v))
}

// UserDiscordIDGTE applies the GTE predicate on the "user_discord_id" field.
func UserDiscordIDGTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldUserDiscordID, v))
}

// UserDiscordIDLT applies the LT predicate on the "user_discord_id" field.
func UserDiscordIDLT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldUserDiscordID, v))
}

// UserDiscordIDLTE applies the LTE predicate on the "user_discord_id" field.
func UserDiscordIDLTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldUserDiscordID, v))
}

// UserDiscordIDContains applies the Contains predicate on the "user_discord_id" field.
func UserDiscordIDContains(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContains(FieldUserDiscordID, v))
}

// UserDiscordIDHasPrefix applies the HasPrefix predicate on the "user_discord_id" field.
func UserDiscordIDHasPrefix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasPrefix(FieldUserDiscordID, v))
}

// UserDiscordIDHasSuffix applies the HasSuffix predicate on the "user_discord_id" field.
func UserDiscordIDHasSuffix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasSuffix(FieldUserDiscordID, v))
}

// UserDiscordIDEqualFold applies the EqualFold predicate on the "user_discord_id" field.
func UserDiscordIDEqualFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEqualFold(FieldUserDiscordID, v))
}

// UserDiscordIDContainsFold applies the ContainsFold predicate on the "user_discord_id" field.
func UserDiscordIDContainsFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContainsFold(FieldUserDiscordID, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContainsFold(FieldKind, v))
}

// YenDeltaEQ applies the EQ predicate on the "yen_delta" field.
func YenDeltaEQ(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldYenDelta, v))
}

// YenDeltaNEQ applies the NEQ predicate on the "yen_delta" field.
func YenDeltaNEQ(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldYenDelta, v))
}

// YenDeltaIn applies the In predicate on the "yen_delta" field.
func YenDeltaIn(vs ...int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldYenDelta, vs...))
}

// YenDeltaNotIn applies the NotIn predicate on the "yen_delta" field.
func YenDeltaNotIn(vs ...int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldYenDelta, vs...))
}

// YenDeltaGT applies the GT predicate on the "yen_delta" field.
func YenDeltaGT(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldYenDelta, v))
}

// YenDeltaGTE applies the GTE predicate on the "yen_delta" field.
func YenDeltaGTE(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldYenDelta, v))
}

// YenDeltaLT applies the LT predicate on the "yen_delta" field.
func YenDeltaLT(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldYenDelta, v))
}

// YenDeltaLTE applies the LTE predicate on the "yen_delta" field.
func YenDeltaLTE(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldYenDelta, v))
}

// AltDeltaEQ applies the EQ predicate on the "alt_delta" field.
func AltDeltaEQ(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldAltDelta, v))
}

// AltDeltaNEQ applies the NEQ predicate on the "alt_delta" field.
func AltDeltaNEQ(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldAltDelta, v))
}

// AltDeltaIn applies the In predicate on the "alt_delta" field.
func AltDeltaIn(vs ...int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldAltDelta, vs...))
}

// AltDeltaNotIn applies the NotIn predicate on the "alt_delta" field.
func AltDeltaNotIn(vs ...int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldAltDelta, vs...))
}

// AltDeltaGT applies the GT predicate on the "alt_delta" field.
func AltDeltaGT(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldAltDelta, v))
}

// AltDeltaGTE applies the GTE predicate on the "alt_delta" field.
func AltDeltaGTE(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldAltDelta, v))
}

// AltDeltaLT applies the LT predicate on the "alt_delta" field.
func AltDeltaLT(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldAltDelta, v))
}

// AltDeltaLTE applies the LTE predicate on the "alt_delta" field.
func AltDeltaLTE(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldAltDelta, v))
}

// XpDeltaEQ applies the EQ predicate on the "xp_delta" field.
func XpDeltaEQ(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldXpDelta, v))
}

// XpDeltaNEQ applies the NEQ predicate on the "xp_delta" field.
func XpDeltaNEQ(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldXpDelta, v))
}

// XpDeltaIn applies the In predicate on the "xp_delta" field.
func XpDeltaIn(vs ...int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldXpDelta, vs...))
}

// XpDeltaNotIn applies the NotIn predicate on the "xp_delta" field.
func XpDeltaNotIn(vs ...int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldXpDelta, vs...))
}

// XpDeltaGT applies the GT predicate on the "xp_delta" field.
func XpDeltaGT(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldXpDelta, v))
}

// XpDeltaGTE applies the GTE predicate on the "xp_delta" field.
func XpDeltaGTE(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldXpDelta, v))
}

// XpDeltaLT applies the LT predicate on the "xp_delta" field.
func XpDeltaLT(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldXpDelta, v))
}

// XpDeltaLTE applies the LTE predicate on the "xp_delta" field.
func XpDeltaLTE(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldXpDelta, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldAmount, v))
}

// SettledPriceEQ applies the EQ predicate on the "settled_price" field.
func SettledPriceEQ(v float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldSettledPrice, v))
}

// SettledPriceNEQ applies the NEQ predicate on the "settled_price" field.
func SettledPriceNEQ(v float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldSettledPrice, v))
}

// SettledPriceIn applies the In predicate on the "settled_price" field.
func SettledPriceIn(vs ...float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldSettledPrice, vs...))
}

// SettledPriceNotIn applies the NotIn predicate on the "settled_price" field.
func SettledPriceNotIn(vs ...float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldSettledPrice, vs...))
}

// SettledPriceGT applies the GT predicate on the "settled_price" field.
func SettledPriceGT(v float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldSettledPrice, v))
}

// SettledPriceGTE applies the GTE predicate on the "settled_price" field.
func SettledPriceGTE(v float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldSettledPrice, v))
}

// SettledPriceLT applies the LT predicate on the "settled_price" field.
func SettledPriceLT(v float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldSettledPrice, v))
}

// SettledPriceLTE applies the LTE predicate on the "settled_price" field.
func SettledPriceLTE(v float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldSettledPrice, v))
}

// PriceAfterEQ applies the EQ predicate on the "price_after" field.
func PriceAfterEQ(v float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldPriceAfter, v))
}

// PriceAfterNEQ applies the NEQ predicate on the "price_after" field.
func PriceAfterNEQ(v float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldPriceAfter, v))
}

// PriceAfterIn applies the In predicate on the "price_after" field.
func PriceAfterIn(vs ...float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldPriceAfter, vs...))
}

// PriceAfterNotIn applies the NotIn predicate on the "price_after" field.
func PriceAfterNotIn(vs ...float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldPriceAfter, vs...))
}

// PriceAfterGT applies the GT predicate on the "price_after" field.
func PriceAfterGT(v float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldPriceAfter, v))
}

// PriceAfterGTE applies the GTE predicate on the "price_after" field.
func PriceAfterGTE(v float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldPriceAfter, v))
}

// PriceAfterLT applies the LT predicate on the "price_after" field.
func PriceAfterLT(v float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldPriceAfter, v))
}

// PriceAfterLTE applies the LTE predicate on the "price_after" field.
func PriceAfterLTE(v float64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldPriceAfter, v))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldBalanceAfter, v))
}

// CryptoAfterEQ applies the EQ predicate on the "crypto_after" field.
func CryptoAfterEQ(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldCryptoAfter, v))
}

// CryptoAfterNEQ applies the NEQ predicate on the "crypto_after" field.
func CryptoAfterNEQ(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldCryptoAfter, v))
}

// CryptoAfterIn applies the In predicate on the "crypto_after" field.
func CryptoAfterIn(vs ...int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldCryptoAfter, vs...))
}

// CryptoAfterNotIn applies the NotIn predicate on the "crypto_after" field.
func CryptoAfterNotIn(vs ...int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldCryptoAfter, vs...))
}

// CryptoAfterGT applies the GT predicate on the "crypto_after" field.
func CryptoAfterGT(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldCryptoAfter, v))
}

// CryptoAfterGTE applies the GTE predicate on the "crypto_after" field.
func CryptoAfterGTE(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldCryptoAfter, v))
}

// CryptoAfterLT applies the LT predicate on the "crypto_after" field.
func CryptoAfterLT(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldCryptoAfter, v))
}

// CryptoAfterLTE applies the LTE predicate on the "crypto_after" field.
func CryptoAfterLTE(v int64) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldCryptoAfter, v))
}

// PrevHashEQ applies the EQ predicate on the "prev_hash" field.
func PrevHashEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldPrevHash, v))
}

// PrevHashNEQ applies the NEQ predicate on the "prev_hash" field.
func PrevHashNEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldPrevHash, v))
}

// PrevHashIn applies the In predicate on the "prev_hash" field.
func PrevHashIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldPrevHash, vs...))
}

// PrevHashNotIn applies the NotIn predicate on the "prev_hash" field.
func PrevHashNotIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldPrevHash, vs...))
}

// PrevHashGT applies the GT predicate on the "prev_hash" field.
func PrevHashGT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldPrevHash, v))
}

// PrevHashGTE applies the GTE predicate on the "prev_hash" field.
func PrevHashGTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldPrevHash, v))
}

// PrevHashLT applies the LT predicate on the "prev_hash" field.
func PrevHashLT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldPrevHash, v))
}

// PrevHashLTE applies the LTE predicate on the "prev_hash" field.
func PrevHashLTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldPrevHash, v))
}

// PrevHashContains applies the Contains predicate on the "prev_hash" field.
func PrevHashContains(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContains(FieldPrevHash, v))
}

// PrevHashHasPrefix applies the HasPrefix predicate on the "prev_hash" field.
func PrevHashHasPrefix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasPrefix(FieldPrevHash, v))
}

// PrevHashHasSuffix applies the HasSuffix predicate on the "prev_hash" field.
func PrevHashHasSuffix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasSuffix(FieldPrevHash, v))
}

// PrevHashEqualFold applies the EqualFold predicate on the "prev_hash" field.
func PrevHashEqualFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEqualFold(FieldPrevHash, v))
}

// PrevHashContainsFold applies the ContainsFold predicate on the "prev_hash" field.
func PrevHashContainsFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContainsFold(FieldPrevHash, v))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldHash, v))
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContains(FieldHash, v))
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasPrefix(FieldHash, v))
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasSuffix(FieldHash, v))
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEqualFold(FieldHash, v))
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContainsFold(FieldHash, v))
}

// SignatureEQ applies the EQ predicate on the "signature" field.
func SignatureEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldSignature, v))
}

// SignatureNEQ applies the NEQ predicate on the "signature" field.
func SignatureNEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldSignature, v))
}

// SignatureIn applies the In predicate on the "signature" field.
func SignatureIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldSignature, vs...))
}

// SignatureNotIn applies the NotIn predicate on the "signature" field.
func SignatureNotIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldSignature, vs...))
}

// SignatureGT applies the GT predicate on the "signature" field.
func SignatureGT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldSignature, v))
}

// SignatureGTE applies the GTE predicate on the "signature" field.
func SignatureGTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldSignature, v))
}

// SignatureLT applies the LT predicate on the "signature" field.
func SignatureLT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldSignature, v))
}

// SignatureLTE applies the LTE predicate on the "signature" field.
func SignatureLTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldSignature, v))
}

// SignatureContains applies the Contains predicate on the "signature" field.
func SignatureContains(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContains(FieldSignature, v))
}

// SignatureHasPrefix applies the HasPrefix predicate on the "signature" field.
func SignatureHasPrefix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasPrefix(FieldSignature, v))
}

// SignatureHasSuffix applies the HasSuffix predicate on the "signature" field.
func SignatureHasSuffix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasSuffix(FieldSignature, v))
}

// SignatureEqualFold applies the EqualFold predicate on the "signature" field.
func SignatureEqualFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEqualFold(FieldSignature, v))
}

// SignatureContainsFold applies the ContainsFold predicate on the "signature" field.
func SignatureContainsFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContainsFold(FieldSignature, v))
}

// PublicKeyEQ applies the EQ predicate on the "public_key" field.
func PublicKeyEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldPublicKey, v))
}

// PublicKeyNEQ applies the NEQ predicate on the "public_key" field.
func PublicKeyNEQ(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldPublicKey, v))
}

// PublicKeyIn applies the In predicate on the "public_key" field.
func PublicKeyIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldPublicKey, vs...))
}

// PublicKeyNotIn applies the NotIn predicate on the "public_key" field.
func PublicKeyNotIn(vs ...string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldPublicKey, vs...))
}

// PublicKeyGT applies the GT predicate on the "public_key" field.
func PublicKeyGT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldPublicKey, v))
}

// PublicKeyGTE applies the GTE predicate on the "public_key" field.
func PublicKeyGTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldPublicKey, v))
}

// PublicKeyLT applies the LT predicate on the "public_key" field.
func PublicKeyLT(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldPublicKey, v))
}

// PublicKeyLTE applies the LTE predicate on the "public_key" field.
func PublicKeyLTE(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldPublicKey, v))
}

// PublicKeyContains applies the Contains predicate on the "public_key" field.
func PublicKeyContains(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContains(FieldPublicKey, v))
}

// PublicKeyHasPrefix applies the HasPrefix predicate on the "public_key" field.
func PublicKeyHasPrefix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasPrefix(FieldPublicKey, v))
}

// PublicKeyHasSuffix applies the HasSuffix predicate on the "public_key" field.
func PublicKeyHasSuffix(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldHasSuffix(FieldPublicKey, v))
}

// PublicKeyEqualFold applies the EqualFold predicate on the "public_key" field.
func PublicKeyEqualFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEqualFold(FieldPublicKey, v))
}

// PublicKeyContainsFold applies the ContainsFold predicate on the "public_key" field.
func PublicKeyContainsFold(v string) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldContainsFold(FieldPublicKey, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TransactionLog {
	return predicate.TransactionLog(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TransactionLog) predicate.TransactionLog {
	return predicate.TransactionLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TransactionLog) predicate.TransactionLog {
	return predicate.TransactionLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TransactionLog) predicate.TransactionLog {
	return predicate.TransactionLog(sql.NotPredicates(p))
}
