// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDiscordID holds the string denoting the discord_id field in the database.
	FieldDiscordID = "discord_id"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldCryptoBalance holds the string denoting the crypto_balance field in the database.
	FieldCryptoBalance = "crypto_balance"
	// FieldXp holds the string denoting the xp field in the database.
	FieldXp = "xp"
	// FieldWorkEndAt holds the string denoting the work_end_at field in the database.
	FieldWorkEndAt = "work_end_at"
	// FieldDailyProfitEarned holds the string denoting the daily_profit_earned field in the database.
	FieldDailyProfitEarned = "daily_profit_earned"
	// FieldLastDailyResetAt holds the string denoting the last_daily_reset_at field in the database.
	FieldLastDailyResetAt = "last_daily_reset_at"
	// FieldWeeklyProfitEarned holds the string denoting the weekly_profit_earned field in the database.
	FieldWeeklyProfitEarned = "weekly_profit_earned"
	// FieldLastWeeklyResetAt holds the string denoting the last_weekly_reset_at field in the database.
	FieldLastWeeklyResetAt = "last_weekly_reset_at"
	// FieldSecurityCameraCount holds the string denoting the security_camera_count field in the database.
	FieldSecurityCameraCount = "security_camera_count"
	// FieldRobEndAt holds the string denoting the rob_end_at field in the database.
	FieldRobEndAt = "rob_end_at"
	// Table holds the table name of the user in the database.
	Table = "users"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldDiscordID,
	FieldBalance,
	FieldCryptoBalance,
	FieldXp,
	FieldWorkEndAt,
	FieldDailyProfitEarned,
	FieldLastDailyResetAt,
	FieldWeeklyProfitEarned,
	FieldLastWeeklyResetAt,
	FieldSecurityCameraCount,
	FieldRobEndAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DiscordIDValidator is a validator for the "discord_id" field. It is called by the builders before save.
	DiscordIDValidator func(string) error
	// DefaultBalance holds the default value on creation for the "balance" field.
	DefaultBalance int64
	// DefaultCryptoBalance holds the default value on creation for the "crypto_balance" field.
	DefaultCryptoBalance int64
	// DefaultXp holds the default value on creation for the "xp" field.
	DefaultXp int64
	// DefaultWorkEndAt holds the default value on creation for the "work_end_at" field.
	DefaultWorkEndAt time.Time
	// DefaultDailyProfitEarned holds the default value on creation for the "daily_profit_earned" field.
	DefaultDailyProfitEarned int64
	// DefaultLastDailyResetAt holds the default value on creation for the "last_daily_reset_at" field.
	DefaultLastDailyResetAt time.Time
	// DefaultWeeklyProfitEarned holds the default value on creation for the "weekly_profit_earned" field.
	DefaultWeeklyProfitEarned int64
	// DefaultLastWeeklyResetAt holds the default value on creation for the "last_weekly_reset_at" field.
	DefaultLastWeeklyResetAt time.Time
	// DefaultSecurityCameraCount holds the default value on creation for the "security_camera_count" field.
	DefaultSecurityCameraCount int64
	// DefaultRobEndAt holds the default value on creation for the "rob_end_at" field.
	DefaultRobEndAt time.Time
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDiscordID orders the results by the discord_id field.
func ByDiscordID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDiscordID, opts...).ToFunc()
}

// ByBalance orders the results by the balance field.
func ByBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalance, opts...).ToFunc()
}

// ByCryptoBalance orders the results by the crypto_balance field.
func ByCryptoBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCryptoBalance, opts...).ToFunc()
}

// ByXp orders the results by the xp field.
func ByXp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldXp, opts...).ToFunc()
}

// ByWorkEndAt orders the results by the work_end_at field.
func ByWorkEndAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkEndAt, opts...).ToFunc()
}

// ByDailyProfitEarned orders the results by the daily_profit_earned field.
func ByDailyProfitEarned(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyProfitEarned, opts...).ToFunc()
}

// ByLastDailyResetAt orders the results by the last_daily_reset_at field.
func ByLastDailyResetAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastDailyResetAt, opts...).ToFunc()
}

// ByWeeklyProfitEarned orders the results by the weekly_profit_earned field.
func ByWeeklyProfitEarned(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyProfitEarned, opts...).ToFunc()
}

// ByLastWeeklyResetAt orders the results by the last_weekly_reset_at field.
func ByLastWeeklyResetAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastWeeklyResetAt, opts...).ToFunc()
}

// BySecurityCameraCount orders the results by the security_camera_count field.
func BySecurityCameraCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecurityCameraCount, opts...).ToFunc()
}

// ByRobEndAt orders the results by the rob_end_at field.
func ByRobEndAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRobEndAt, opts...).ToFunc()
}
