// Code generated by ent, DO NOT EDIT.

package user

import (
	"alt-bot/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// DiscordID applies equality check predicate on the "discord_id" field. It's identical to DiscordIDEQ.
func DiscordID(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDiscordID, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBalance, v))
}

// CryptoBalance applies equality check predicate on the "crypto_balance" field. It's identical to CryptoBalanceEQ.
func CryptoBalance(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCryptoBalance, v))
}

// Xp applies equality check predicate on the "xp" field. It's identical to XpEQ.
func Xp(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldXp, v))
}

// WorkEndAt applies equality check predicate on the "work_end_at" field. It's identical to WorkEndAtEQ.
func WorkEndAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldWorkEndAt, v))
}

// DailyProfitEarned applies equality check predicate on the "daily_profit_earned" field. It's identical to DailyProfitEarnedEQ.
func DailyProfitEarned(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDailyProfitEarned, v))
}

// LastDailyResetAt applies equality check predicate on the "last_daily_reset_at" field. It's identical to LastDailyResetAtEQ.
func LastDailyResetAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastDailyResetAt, v))
}

// WeeklyProfitEarned applies equality check predicate on the "weekly_profit_earned" field. It's identical to WeeklyProfitEarnedEQ.
func WeeklyProfitEarned(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldWeeklyProfitEarned, v))
}

// LastWeeklyResetAt applies equality check predicate on the "last_weekly_reset_at" field. It's identical to LastWeeklyResetAtEQ.
func LastWeeklyResetAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastWeeklyResetAt, v))
}

// SecurityCameraCount applies equality check predicate on the "security_camera_count" field. It's identical to SecurityCameraCountEQ.
func SecurityCameraCount(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSecurityCameraCount, v))
}

// RobEndAt applies equality check predicate on the "rob_end_at" field. It's identical to RobEndAtEQ.
func RobEndAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRobEndAt, v))
}

// DiscordIDEQ applies the EQ predicate on the "discord_id" field.
func DiscordIDEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDiscordID, v))
}

// DiscordIDNEQ applies the NEQ predicate on the "discord_id" field.
func DiscordIDNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldDiscordID, v))
}

// DiscordIDIn applies the In predicate on the "discord_id" field.
func DiscordIDIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldDiscordID, vs...))
}

// DiscordIDNotIn applies the NotIn predicate on the "discord_id" field.
func DiscordIDNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldDiscordID, vs...))
}

// DiscordIDGT applies the GT predicate on the "discord_id" field.
func DiscordIDGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldDiscordID, v))
}

// DiscordIDGTE applies the GTE predicate on the "discord_id" field.
func DiscordIDGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldDiscordID, v))
}

// DiscordIDLT applies the LT predicate on the "discord_id" field.
func DiscordIDLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldDiscordID, v))
}

// DiscordIDLTE applies the LTE predicate on the "discord_id" field.
func DiscordIDLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldDiscordID, v))
}

// DiscordIDContains applies the Contains predicate on the "discord_id" field.
func DiscordIDContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldDiscordID, v))
}

// DiscordIDHasPrefix applies the HasPrefix predicate on the "discord_id" field.
func DiscordIDHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldDiscordID, v))
}

// DiscordIDHasSuffix applies the HasSuffix predicate on the "discord_id" field.
func DiscordIDHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldDiscordID, v))
}

// DiscordIDEqualFold applies the EqualFold predicate on the "discord_id" field.
func DiscordIDEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldDiscordID, v))
}

// DiscordIDContainsFold applies the ContainsFold predicate on the "discord_id" field.
func DiscordIDContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldDiscordID, v))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldBalance, v))
}

// CryptoBalanceEQ applies the EQ predicate on the "crypto_balance" field.
func CryptoBalanceEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCryptoBalance, v))
}

// CryptoBalanceNEQ applies the NEQ predicate on the "crypto_balance" field.
func CryptoBalanceNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCryptoBalance, v))
}

// CryptoBalanceIn applies the In predicate on the "crypto_balance" field.
func CryptoBalanceIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldCryptoBalance, vs...))
}

// CryptoBalanceNotIn applies the NotIn predicate on the "crypto_balance" field.
func CryptoBalanceNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCryptoBalance, vs...))
}

// CryptoBalanceGT applies the GT predicate on the "crypto_balance" field.
func CryptoBalanceGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldCryptoBalance, v))
}

// CryptoBalanceGTE applies the GTE predicate on the "crypto_balance" field.
func CryptoBalanceGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCryptoBalance, v))
}

// CryptoBalanceLT applies the LT predicate on the "crypto_balance" field.
func CryptoBalanceLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldCryptoBalance, v))
}

// CryptoBalanceLTE applies the LTE predicate on the "crypto_balance" field.
func CryptoBalanceLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCryptoBalance, v))
}

// XpEQ applies the EQ predicate on the "xp" field.
func XpEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldXp, v))
}

// XpNEQ applies the NEQ predicate on the "xp" field.
func XpNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldXp, v))
}

// XpIn applies the In predicate on the "xp" field.
func XpIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldXp, vs...))
}

// XpNotIn applies the NotIn predicate on the "xp" field.
func XpNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldXp, vs...))
}

// XpGT applies the GT predicate on the "xp" field.
func XpGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldXp, v))
}

// XpGTE applies the GTE predicate on the "xp" field.
func XpGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldXp, v))
}

// XpLT applies the LT predicate on the "xp" field.
func XpLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldXp, v))
}

// XpLTE applies the LTE predicate on the "xp" field.
func XpLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldXp, v))
}

// WorkEndAtEQ applies the EQ predicate on the "work_end_at" field.
func WorkEndAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldWorkEndAt, v))
}

// WorkEndAtNEQ applies the NEQ predicate on the "work_end_at" field.
func WorkEndAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldWorkEndAt, v))
}

// WorkEndAtIn applies the In predicate on the "work_end_at" field.
func WorkEndAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldWorkEndAt, vs...))
}

// WorkEndAtNotIn applies the NotIn predicate on the "work_end_at" field.
func WorkEndAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldWorkEndAt, vs...))
}

// WorkEndAtGT applies the GT predicate on the "work_end_at" field.
func WorkEndAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldWorkEndAt, v))
}

// WorkEndAtGTE applies the GTE predicate on the "work_end_at" field.
func WorkEndAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldWorkEndAt, v))
}

// WorkEndAtLT applies the LT predicate on the "work_end_at" field.
func WorkEndAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldWorkEndAt, v))
}

// WorkEndAtLTE applies the LTE predicate on the "work_end_at" field.
func WorkEndAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldWorkEndAt, v))
}

// DailyProfitEarnedEQ applies the EQ predicate on the "daily_profit_earned" field.
func DailyProfitEarnedEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDailyProfitEarned, v))
}

// DailyProfitEarnedNEQ applies the NEQ predicate on the "daily_profit_earned" field.
func DailyProfitEarnedNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldDailyProfitEarned, v))
}

// DailyProfitEarnedIn applies the In predicate on the "daily_profit_earned" field.
func DailyProfitEarnedIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldDailyProfitEarned, vs...))
}

// DailyProfitEarnedNotIn applies the NotIn predicate on the "daily_profit_earned" field.
func DailyProfitEarnedNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldDailyProfitEarned, vs...))
}

// DailyProfitEarnedGT applies the GT predicate on the "daily_profit_earned" field.
func DailyProfitEarnedGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldDailyProfitEarned, v))
}

// DailyProfitEarnedGTE applies the GTE predicate on the "daily_profit_earned" field.
func DailyProfitEarnedGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldDailyProfitEarned, v))
}

// DailyProfitEarnedLT applies the LT predicate on the "daily_profit_earned" field.
func DailyProfitEarnedLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldDailyProfitEarned, v))
}

// DailyProfitEarnedLTE applies the LTE predicate on the "daily_profit_earned" field.
func DailyProfitEarnedLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldDailyProfitEarned, v))
}

// LastDailyResetAtEQ applies the EQ predicate on the "last_daily_reset_at" field.
func LastDailyResetAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastDailyResetAt, v))
}

// LastDailyResetAtNEQ applies the NEQ predicate on the "last_daily_reset_at" field.
func LastDailyResetAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLastDailyResetAt, v))
}

// LastDailyResetAtIn applies the In predicate on the "last_daily_reset_at" field.
func LastDailyResetAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldLastDailyResetAt, vs...))
}

// LastDailyResetAtNotIn applies the NotIn predicate on the "last_daily_reset_at" field.
func LastDailyResetAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLastDailyResetAt, vs...))
}

// LastDailyResetAtGT applies the GT predicate on the "last_daily_reset_at" field.
func LastDailyResetAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldLastDailyResetAt, v))
}

// LastDailyResetAtGTE applies the GTE predicate on the "last_daily_reset_at" field.
func LastDailyResetAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLastDailyResetAt, v))
}

// LastDailyResetAtLT applies the LT predicate on the "last_daily_reset_at" field.
func LastDailyResetAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldLastDailyResetAt, v))
}

// LastDailyResetAtLTE applies the LTE predicate on the "last_daily_reset_at" field.
func LastDailyResetAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLastDailyResetAt, v))
}

// WeeklyProfitEarnedEQ applies the EQ predicate on the "weekly_profit_earned" field.
func WeeklyProfitEarnedEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldWeeklyProfitEarned, v))
}

// WeeklyProfitEarnedNEQ applies the NEQ predicate on the "weekly_profit_earned" field.
func WeeklyProfitEarnedNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldWeeklyProfitEarned, v))
}

// WeeklyProfitEarnedIn applies the In predicate on the "weekly_profit_earned" field.
func WeeklyProfitEarnedIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldWeeklyProfitEarned, vs...))
}

// WeeklyProfitEarnedNotIn applies the NotIn predicate on the "weekly_profit_earned" field.
func WeeklyProfitEarnedNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldWeeklyProfitEarned, vs...))
}

// WeeklyProfitEarnedGT applies the GT predicate on the "weekly_profit_earned" field.
func WeeklyProfitEarnedGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldWeeklyProfitEarned, v))
}

// WeeklyProfitEarnedGTE applies the GTE predicate on the "weekly_profit_earned" field.
func WeeklyProfitEarnedGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldWeeklyProfitEarned, v))
}

// WeeklyProfitEarnedLT applies the LT predicate on the "weekly_profit_earned" field.
func WeeklyProfitEarnedLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldWeeklyProfitEarned, v))
}

// WeeklyProfitEarnedLTE applies the LTE predicate on the "weekly_profit_earned" field.
func WeeklyProfitEarnedLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldWeeklyProfitEarned, v))
}

// LastWeeklyResetAtEQ applies the EQ predicate on the "last_weekly_reset_at" field.
func LastWeeklyResetAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldLastWeeklyResetAt, v))
}

// LastWeeklyResetAtNEQ applies the NEQ predicate on the "last_weekly_reset_at" field.
func LastWeeklyResetAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldLastWeeklyResetAt, v))
}

// LastWeeklyResetAtIn applies the In predicate on the "last_weekly_reset_at" field.
func LastWeeklyResetAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldLastWeeklyResetAt, vs...))
}

// LastWeeklyResetAtNotIn applies the NotIn predicate on the "last_weekly_reset_at" field.
func LastWeeklyResetAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldLastWeeklyResetAt, vs...))
}

// LastWeeklyResetAtGT applies the GT predicate on the "last_weekly_reset_at" field.
func LastWeeklyResetAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldLastWeeklyResetAt, v))
}

// LastWeeklyResetAtGTE applies the GTE predicate on the "last_weekly_reset_at" field.
func LastWeeklyResetAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldLastWeeklyResetAt, v))
}

// LastWeeklyResetAtLT applies the LT predicate on the "last_weekly_reset_at" field.
func LastWeeklyResetAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldLastWeeklyResetAt, v))
}

// LastWeeklyResetAtLTE applies the LTE predicate on the "last_weekly_reset_at" field.
func LastWeeklyResetAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldLastWeeklyResetAt, v))
}

// SecurityCameraCountEQ applies the EQ predicate on the "security_camera_count" field.
func SecurityCameraCountEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldSecurityCameraCount, v))
}

// SecurityCameraCountNEQ applies the NEQ predicate on the "security_camera_count" field.
func SecurityCameraCountNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldSecurityCameraCount, v))
}

// SecurityCameraCountIn applies the In predicate on the "security_camera_count" field.
func SecurityCameraCountIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldSecurityCameraCount, vs...))
}

// SecurityCameraCountNotIn applies the NotIn predicate on the "security_camera_count" field.
func SecurityCameraCountNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldSecurityCameraCount, vs...))
}

// SecurityCameraCountGT applies the GT predicate on the "security_camera_count" field.
func SecurityCameraCountGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldSecurityCameraCount, v))
}

// SecurityCameraCountGTE applies the GTE predicate on the "security_camera_count" field.
func SecurityCameraCountGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldSecurityCameraCount, v))
}

// SecurityCameraCountLT applies the LT predicate on the "security_camera_count" field.
func SecurityCameraCountLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldSecurityCameraCount, v))
}

// SecurityCameraCountLTE applies the LTE predicate on the "security_camera_count" field.
func SecurityCameraCountLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldSecurityCameraCount, v))
}

// RobEndAtEQ applies the EQ predicate on the "rob_end_at" field.
func RobEndAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRobEndAt, v))
}

// RobEndAtNEQ applies the NEQ predicate on the "rob_end_at" field.
func RobEndAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldRobEndAt, v))
}

// RobEndAtIn applies the In predicate on the "rob_end_at" field.
func RobEndAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldRobEndAt, vs...))
}

// RobEndAtNotIn applies the NotIn predicate on the "rob_end_at" field.
func RobEndAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldRobEndAt, vs...))
}

// RobEndAtGT applies the GT predicate on the "rob_end_at" field.
func RobEndAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldRobEndAt, v))
}

// RobEndAtGTE applies the GTE predicate on the "rob_end_at" field.
func RobEndAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldRobEndAt, v))
}

// RobEndAtLT applies the LT predicate on the "rob_end_at" field.
func RobEndAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldRobEndAt, v))
}

// RobEndAtLTE applies the LTE predicate on the "rob_end_at" field.
func RobEndAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldRobEndAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
