// Code generated by ent, DO NOT EDIT.

package user

import (
	"alt-bot/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// DiscordID applies equality check predicate on the "discord_id" field. It's identical to DiscordIDEQ.
func DiscordID(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDiscordID, v))
}

// Balance applies equality check predicate on the "balance" field. It's identical to BalanceEQ.
func Balance(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBalance, v))
}

// CryptoBalance applies equality check predicate on the "crypto_balance" field. It's identical to CryptoBalanceEQ.
func CryptoBalance(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCryptoBalance, v))
}

// Xp applies equality check predicate on the "xp" field. It's identical to XpEQ.
func Xp(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldXp, v))
}

// WorkEndAt applies equality check predicate on the "work_end_at" field. It's identical to WorkEndAtEQ.
func WorkEndAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldWorkEndAt, v))
}

// DiscordIDEQ applies the EQ predicate on the "discord_id" field.
func DiscordIDEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldDiscordID, v))
}

// DiscordIDNEQ applies the NEQ predicate on the "discord_id" field.
func DiscordIDNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldDiscordID, v))
}

// DiscordIDIn applies the In predicate on the "discord_id" field.
func DiscordIDIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldDiscordID, vs...))
}

// DiscordIDNotIn applies the NotIn predicate on the "discord_id" field.
func DiscordIDNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldDiscordID, vs...))
}

// DiscordIDGT applies the GT predicate on the "discord_id" field.
func DiscordIDGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldDiscordID, v))
}

// DiscordIDGTE applies the GTE predicate on the "discord_id" field.
func DiscordIDGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldDiscordID, v))
}

// DiscordIDLT applies the LT predicate on the "discord_id" field.
func DiscordIDLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldDiscordID, v))
}

// DiscordIDLTE applies the LTE predicate on the "discord_id" field.
func DiscordIDLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldDiscordID, v))
}

// DiscordIDContains applies the Contains predicate on the "discord_id" field.
func DiscordIDContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldDiscordID, v))
}

// DiscordIDHasPrefix applies the HasPrefix predicate on the "discord_id" field.
func DiscordIDHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldDiscordID, v))
}

// DiscordIDHasSuffix applies the HasSuffix predicate on the "discord_id" field.
func DiscordIDHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldDiscordID, v))
}

// DiscordIDEqualFold applies the EqualFold predicate on the "discord_id" field.
func DiscordIDEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldDiscordID, v))
}

// DiscordIDContainsFold applies the ContainsFold predicate on the "discord_id" field.
func DiscordIDContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldDiscordID, v))
}

// BalanceEQ applies the EQ predicate on the "balance" field.
func BalanceEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBalance, v))
}

// BalanceNEQ applies the NEQ predicate on the "balance" field.
func BalanceNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldBalance, v))
}

// BalanceIn applies the In predicate on the "balance" field.
func BalanceIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldBalance, vs...))
}

// BalanceNotIn applies the NotIn predicate on the "balance" field.
func BalanceNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldBalance, vs...))
}

// BalanceGT applies the GT predicate on the "balance" field.
func BalanceGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldBalance, v))
}

// BalanceGTE applies the GTE predicate on the "balance" field.
func BalanceGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldBalance, v))
}

// BalanceLT applies the LT predicate on the "balance" field.
func BalanceLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldBalance, v))
}

// BalanceLTE applies the LTE predicate on the "balance" field.
func BalanceLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldBalance, v))
}

// CryptoBalanceEQ applies the EQ predicate on the "crypto_balance" field.
func CryptoBalanceEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCryptoBalance, v))
}

// CryptoBalanceNEQ applies the NEQ predicate on the "crypto_balance" field.
func CryptoBalanceNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCryptoBalance, v))
}

// CryptoBalanceIn applies the In predicate on the "crypto_balance" field.
func CryptoBalanceIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldCryptoBalance, vs...))
}

// CryptoBalanceNotIn applies the NotIn predicate on the "crypto_balance" field.
func CryptoBalanceNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCryptoBalance, vs...))
}

// CryptoBalanceGT applies the GT predicate on the "crypto_balance" field.
func CryptoBalanceGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldCryptoBalance, v))
}

// CryptoBalanceGTE applies the GTE predicate on the "crypto_balance" field.
func CryptoBalanceGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCryptoBalance, v))
}

// CryptoBalanceLT applies the LT predicate on the "crypto_balance" field.
func CryptoBalanceLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldCryptoBalance, v))
}

// CryptoBalanceLTE applies the LTE predicate on the "crypto_balance" field.
func CryptoBalanceLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCryptoBalance, v))
}

// XpEQ applies the EQ predicate on the "xp" field.
func XpEQ(v int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldXp, v))
}

// XpNEQ applies the NEQ predicate on the "xp" field.
func XpNEQ(v int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldXp, v))
}

// XpIn applies the In predicate on the "xp" field.
func XpIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldXp, vs...))
}

// XpNotIn applies the NotIn predicate on the "xp" field.
func XpNotIn(vs ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldXp, vs...))
}

// XpGT applies the GT predicate on the "xp" field.
func XpGT(v int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldXp, v))
}

// XpGTE applies the GTE predicate on the "xp" field.
func XpGTE(v int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldXp, v))
}

// XpLT applies the LT predicate on the "xp" field.
func XpLT(v int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldXp, v))
}

// XpLTE applies the LTE predicate on the "xp" field.
func XpLTE(v int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldXp, v))
}

// WorkEndAtEQ applies the EQ predicate on the "work_end_at" field.
func WorkEndAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldWorkEndAt, v))
}

// WorkEndAtNEQ applies the NEQ predicate on the "work_end_at" field.
func WorkEndAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldWorkEndAt, v))
}

// WorkEndAtIn applies the In predicate on the "work_end_at" field.
func WorkEndAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldWorkEndAt, vs...))
}

// WorkEndAtNotIn applies the NotIn predicate on the "work_end_at" field.
func WorkEndAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldWorkEndAt, vs...))
}

// WorkEndAtGT applies the GT predicate on the "work_end_at" field.
func WorkEndAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldWorkEndAt, v))
}

// WorkEndAtGTE applies the GTE predicate on the "work_end_at" field.
func WorkEndAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldWorkEndAt, v))
}

// WorkEndAtLT applies the LT predicate on the "work_end_at" field.
func WorkEndAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldWorkEndAt, v))
}

// WorkEndAtLTE applies the LTE predicate on the "work_end_at" field.
func WorkEndAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldWorkEndAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
